CREATE TABLE [stage_csx_csland].[C_OPER_CAPL90] (
    [FILE_NUMBER]      CHAR (10)       NOT NULL,
    [CAPL90_311_RMKS]  VARCHAR (1)     NULL,
    [INSURANCE]        VARCHAR (1)     NULL,
    [CAPL90_604_RMKS]  VARCHAR (1)     NULL,
    [MARKETING]        VARCHAR (1)     NULL,
    [CAPL90_604B_RMKS] VARCHAR (1)     NULL,
    [MKT_A_PERCENT]    NUMERIC (11, 8) NULL,
    [MKT_A_DOLLAR]     NUMERIC (9, 2)  NULL,
    [MKT_B_PERCENT]    NUMERIC (11, 8) NULL,
    [MKT_B_DOLLAR]     NUMERIC (9, 2)  NULL,
    [MKT_C_PERCENT]    NUMERIC (11, 8) NULL,
    [MKT_C_DOLLAR]     NUMERIC (9, 2)  NULL,
    [MKT_D_PERCENT]    NUMERIC (11, 8) NULL,
    [MKT_D_DOLLAR]     NUMERIC (9, 2)  NULL,
    [CAPL90_903_RMKS]  VARCHAR (1)     NULL,
    [CASING_POINT]     VARCHAR (1)     NULL,
    [CAPL90_1007_RMKS] VARCHAR (1)     NULL,
    [PENALTY_DEV]      NUMERIC (11, 8) NULL,
    [PENALTY_EXP]      NUMERIC (11, 8) NULL,
    [CAPL90_1010_RMKS] VARCHAR (1)     NULL,
    [TITLE_WELL]       NUMERIC (3)     NULL,
    [CAPL90_2401_RMKS] VARCHAR (1)     NULL,
    [DISP_OF_INTEREST] VARCHAR (1)     NULL,
    [CAPL90_2404_RMKS] VARCHAR (1)     NULL,
    [ASSIGNMENT]       VARCHAR (1)     NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

