CREATE TABLE [stage_csx_csland].[C_OPER_CAPL81] (
    [FILE_NUMBER]      CHAR (10)       NOT NULL,
    [CAPL81_311_RMKS]  VARCHAR (1)     NULL,
    [INSURANCE]        VARCHAR (1)     NULL,
    [CAPL81_903_RMKS]  VARCHAR (1)     NULL,
    [CASING_POINT]     VARCHAR (1)     NULL,
    [CAPL81_2401_RMKS] VARCHAR (1)     NULL,
    [DISP_OF_INTEREST] VARCHAR (1)     NULL,
    [CAPL81_1007_RMKS] VARCHAR (1)     NULL,
    [PENALTY_DEV]      NUMERIC (11, 8) NULL,
    [PENALTY_EXP]      NUMERIC (11, 8) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

