CREATE TABLE [stage_csx_csland].[C_SERVICE_LOC] (
    [FILE_NUMBER]       CHAR (10)      NOT NULL,
    [LOC_OCCURRENCE]    NUMERIC (6)    NOT NULL,
    [PROD_WL]           VARCHAR (1)    NULL,
    [PROD_WELL_NUMBER]  CHAR (10)      NULL,
    [PROD_UWI]          VARCHAR (16)   NULL,
    [PROD_SORTED_UWI]   VARCHAR (16)   NULL,
    [PROD_DESCRIPTION]  VARCHAR (1910) NULL,
    [PROD_PROJECT]      VARCHAR (16)   NULL,
    [PROD_PRIORITY]     VARCHAR (10)   NULL,
    [PROD_OFF_SRV_DATE] DATE           NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

