CREATE TABLE [stage_csx_csland].[T_ADMIN] (
    [CODE]             CHAR (10)    NOT NULL,
    [DESCRIPTION]      VARCHAR (40) NOT NULL,
    [AI_STATUS]        VARCHAR (1)  NOT NULL,
    [LAST_UPDATE_USER] VARCHAR (20) NULL,
    [LAST_UPDATE_DATE] DATE         NULL,
    [CODE_IN_USE]      NUMERIC (1)  NULL,
    [RESERVED]         NUMERIC (1)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

