CREATE TABLE [stage_csx_csland].[W_DETAIL1] (
    [FILE_NUMBER]        CHAR (10)       NOT NULL,
    [WELL_UWI]           VARCHAR (16)    NOT NULL,
    [FILE_STATUS]        CHAR (10)       NOT NULL,
    [STATUS_DATE]        DATE            NOT NULL,
    [WELL_NAME]          VARCHAR (60)    NOT NULL,
    [WELL_STATUS]        CHAR (10)       NOT NULL,
    [WELL_TYPE]          CHAR (10)       NOT NULL,
    [WELL_STATUS_DATE]   DATE            NOT NULL,
    [PENALTY]            VARCHAR (1)     NULL,
    [GOVERNMENT_STATUS]  VARCHAR (12)    NULL,
    [DIRECTION_DRILLED]  CHAR (10)       NULL,
    [LESSOR_TYPE]        CHAR (10)       NULL,
    [WELL_LICENSEE]      CHAR (6)        NOT NULL,
    [CONFIDENT_FLAG]     VARCHAR (1)     NULL,
    [GOVERN_AGMT_OPER]   CHAR (6)        NULL,
    [GOVERNING_CONTRACT] CHAR (10)       NULL,
    [ADMIN_COMPANY]      CHAR (10)       NOT NULL,
    [AREA]               CHAR (10)       NOT NULL,
    [DISTRICT]           CHAR (10)       NULL,
    [DIVISION]           CHAR (10)       NOT NULL,
    [SPUD_DATE]          DATE            NULL,
    [RIG_RELEASE_DATE]   DATE            NULL,
    [COMPLETION_DATE]    DATE            NULL,
    [ON_PRODUCTION_DATE] DATE            NULL,
    [PAYOUT_DATE]        DATE            NULL,
    [ABANDONED_DATE]     DATE            NULL,
    [SHUTIN_DATE]        DATE            NULL,
    [SHUTIN_REASON]      CHAR (10)       NULL,
    [INJECTION_DATE]     DATE            NULL,
    [LAST_PROD_DATE]     DATE            NULL,
    [SORTED_UWI]         VARCHAR (16)    NOT NULL,
    [LATITUDE]           NUMERIC (8)     NOT NULL,
    [LONGITUDE]          NUMERIC (8)     NOT NULL,
    [MAP_LAT]            NUMERIC (11, 8) NULL,
    [MAP_LONG]           NUMERIC (11, 8) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

