CREATE TABLE [stage].[t_afenav_afe_custom] (
    [DOCUMENT_ID]                          NVARCHAR (50)   NULL,
    [VERSION]                              INT             NULL,
    [COST_CENTER]                          NVARCHAR (50)   NULL,
    [WELL_NAME]                            NVARCHAR (200)  NULL,
    [BUDGETED]                             TINYINT         NULL,
    [BUDGET_TIMING]                        NVARCHAR (50)   NULL,
    [BUDGET_CLASS]                         NVARCHAR (50)   NULL,
    [BUDGET_LINE]                          NVARCHAR (50)   NULL,
    [LAND_VENDOR]                          NVARCHAR (30)   NULL,
    [LAND_PURCHASER]                       NVARCHAR (30)   NULL,
    [LAND_CLOSING_DATE]                    DATETIME        NULL,
    [LAND_EFFECTIVE_DATE]                  DATETIME        NULL,
    [PROVINCE]                             NVARCHAR (50)   NULL,
    [RAISED_ON_BEHALF_OF]                  NVARCHAR (50)   NULL,
    [UNIT_OR_NON_UNIT]                     NVARCHAR (50)   NULL,
    [UNIT_NAME]                            NVARCHAR (50)   NULL,
    [EXCLUDE_FROM_EXPORT]                  NVARCHAR (50)   NULL,
    [E_TI_PIPELINE_CLASSIFICATION]         NVARCHAR (50)   NULL,
    [A_R_PROJECT_TYPE]                     NVARCHAR (50)   NULL,
    [CLASSIFICATION]                       NVARCHAR (50)   NULL,
    [TAX_DESIGNATION]                      NVARCHAR (50)   NULL,
    [GENERAL_COMBO]                        NVARCHAR (50)   NULL,
    [FORM_LETTER_P1]                       NVARCHAR (2000) NULL,
    [FORM_SUPPLEMENT_P1]                   NVARCHAR (2000) NULL,
    [OWA_FLAG]                             NVARCHAR (50)   NULL,
    [AFE_TYPE]                             NVARCHAR (50)   NULL,
    [DISTRICT]                             NVARCHAR (50)   NULL,
    [AREA]                                 NVARCHAR (50)   NULL,
    [FACILITY]                             NVARCHAR (50)   NULL,
    [OPERATED]                             NVARCHAR (50)   NULL,
    [Copy of DOCUMENT_ID]                  VARCHAR (50)    NULL,
    [Copy of COST_CENTER]                  VARCHAR (50)    NULL,
    [Copy of WELL_NAME]                    VARCHAR (200)   NULL,
    [Copy of BUDGET_TIMING]                VARCHAR (50)    NULL,
    [Copy of BUDGET_CLASS]                 VARCHAR (50)    NULL,
    [Copy of BUDGET_LINE]                  VARCHAR (50)    NULL,
    [Copy of LAND_VENDOR]                  VARCHAR (30)    NULL,
    [Copy of LAND_PURCHASER]               VARCHAR (30)    NULL,
    [Copy of PROVINCE]                     VARCHAR (50)    NULL,
    [Copy of RAISED_ON_BEHALF_OF]          VARCHAR (50)    NULL,
    [Copy of UNIT_OR_NON_UNIT]             VARCHAR (50)    NULL,
    [Copy of UNIT_NAME]                    VARCHAR (50)    NULL,
    [Copy of EXCLUDE_FROM_EXPORT]          VARCHAR (50)    NULL,
    [Copy of E_TI_PIPELINE_CLASSIFICATION] VARCHAR (50)    NULL,
    [Copy of A_R_PROJECT_TYPE]             VARCHAR (50)    NULL,
    [Copy of CLASSIFICATION]               VARCHAR (50)    NULL,
    [Copy of TAX_DESIGNATION]              VARCHAR (50)    NULL,
    [Copy of GENERAL_COMBO]                VARCHAR (50)    NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

