CREATE TABLE [stage].[t_afenav_afe] (
    [DOCUMENT_ID]                      NVARCHAR (50)    NULL,
    [VERSION]                          INT              NULL,
    [FIELDCOST_DOC]                    NVARCHAR (50)    NULL,
    [ACTUAL_DOC]                       NVARCHAR (50)    NULL,
    [ACCRUAL_DOC]                      NVARCHAR (50)    NULL,
    [AFENUMBER_DOC]                    NVARCHAR (50)    NULL,
    [COMPLETED]                        DATETIME         NULL,
    [INTERNAL_JUSTIFICATION]           NVARCHAR (4000)  NULL,
    [EXTERNAL_JUSTIFICATION]           NVARCHAR (4000)  NULL,
    [DESCRIPTION]                      NVARCHAR (40)    NULL,
    [START_DATE]                       DATETIME         NULL,
    [CHAIN_GUID]                       NVARCHAR (50)    NULL,
    [END_DATE]                         DATETIME         NULL,
    [BUDGET_YEAR]                      INT              NULL,
    [CURRENCY_CODE]                    NVARCHAR (100)   NULL,
    [ESTIMATE_CONVERSION_DATE]         DATETIME         NULL,
    [OUTSIDE_AFENUMBER]                NVARCHAR (50)    NULL,
    [OP_NOTICE]                        TINYINT          NULL,
    [REQUIRED_BY_DATE]                 DATETIME         NULL,
    [VERSION_STRING]                   NVARCHAR (10)    NULL,
    [BUDGET_MANAGER]                   NVARCHAR (50)    NULL,
    [OWNER]                            NVARCHAR (50)    NULL,
    [CREATOR]                          NVARCHAR (50)    NULL,
    [CREATION_DATE]                    DATETIME         NULL,
    [BASE_CREATION_DATE]               DATETIME         NULL,
    [CLOSED]                           TINYINT          NULL,
    [CLOSED_USER]                      NVARCHAR (50)    NULL,
    [CLOSED_DATE]                      DATETIME         NULL,
    [CLOSED_REASON]                    NVARCHAR (2000)  NULL,
    [SILENT_PARTNER_MODE]              NVARCHAR (50)    NULL,
    [WELL_LIST_TITLE]                  NVARCHAR (100)   NULL,
    [WELL_REPORTING_IDENTIFIER]        NVARCHAR (100)   NULL,
    [TOTAL_GROSS_ESTIMATE]             NUMERIC (28, 14) NULL,
    [STATUS]                           NVARCHAR (50)    NULL,
    [STATUS_DESC]                      NVARCHAR (50)    NULL,
    [TOTAL_NET_ESTIMATE]               NUMERIC (28, 14) NULL,
    [OUR_WI]                           NUMERIC (28, 14) NULL,
    [PARENT_COMPANY]                   NVARCHAR (50)    NULL,
    [OPERATING_COMPANY]                NVARCHAR (50)    NULL,
    [FASTTRACK]                        TINYINT          NULL,
    [SUPERSEDED_STATUS]                NVARCHAR (50)    NULL,
    [SUPERSEDED_STATUS_DESC]           NVARCHAR (50)    NULL,
    [APPROVED_GROSS_ESTIMATE]          NUMERIC (28, 14) NULL,
    [APPROVED_NET_ESTIMATE]            NUMERIC (28, 14) NULL,
    [SUPPLEMENTAL_GROSS_ESTIMATE]      NUMERIC (28, 14) NULL,
    [SUPPLEMENTAL_NET_ESTIMATE]        NUMERIC (28, 14) NULL,
    [PARENT_RTD]                       NVARCHAR (50)    NULL,
    [VN_COST_TYPE]                     NVARCHAR (50)    NULL,
    [VN_ENTITY]                        NVARCHAR (100)   NULL,
    [VN_PLAN]                          NVARCHAR (100)   NULL,
    [VN_SCENARIO]                      NVARCHAR (100)   NULL,
    [VN_RESCAT]                        NVARCHAR (100)   NULL,
    [RELEASE_COMMENT]                  NVARCHAR (4000)  NULL,
    [RELEASED_DATE]                    DATETIME         NULL,
    [RELEASE_USER]                     NVARCHAR (50)    NULL,
    [ROUTED_COMMENT]                   NVARCHAR (4000)  NULL,
    [ROUTED_DATE]                      DATETIME         NULL,
    [ROUTED_USER]                      NVARCHAR (50)    NULL,
    [INTERNAL_APPROVAL_DATE]           DATETIME         NULL,
    [FULL_APPROVAL_DATE]               DATETIME         NULL,
    [REVIEW_COMPLETED_DATE]            DATETIME         NULL,
    [AFELINK_TRACKING_ID]              NVARCHAR (100)   NULL,
    [LEGACY_AFEID]                     INT              NULL,
    [LEGACY_CHAINID]                   INT              NULL,
    [CHAIN_VERSION]                    INT              NULL,
    [REV_SUP_MODE]                     NVARCHAR (1)     NULL,
    [REV_NUMBER]                       INT              NULL,
    [SUP_NUMBER]                       INT              NULL,
    [CORR_NUMBER]                      INT              NULL,
    [SUPERSEDED_DATE]                  DATETIME         NULL,
    [NEXT_APPROVING_POSITIONS]         NVARCHAR (4000)  NULL,
    [NEXT_REVIEWING_POSITIONS]         NVARCHAR (4000)  NULL,
    [AFEID]                            INT              NULL,
    [AFECHAINID]                       INT              NULL,
    [AFEOPERATINGPARTNER]              INT              NULL,
    [AFECASHCALL]                      TINYINT          NULL,
    [AFERELEASEDATE]                   DATETIME         NULL,
    [REVISION]                         INT              NULL,
    [AFESUPERSEDEDDATE]                DATETIME         NULL,
    [HASEXTERNALAPPROVAL]              TINYINT          NULL,
    [ISREVISED]                        TINYINT          NULL,
    [ISSUPPLEMENTED]                   TINYINT          NULL,
    [AFEREVNUMBER]                     INT              NULL,
    [AFESUPNUMBER]                     INT              NULL,
    [AFECORRNUMBER]                    INT              NULL,
    [LAST_UPDATE_USER]                 INT              NULL,
    [LAST_UPDATE_DATE]                 DATETIME         NULL,
    [NEXT_POSITION]                    INT              NULL,
    [ROUTE_FOR_REVIEW_DATE]            DATETIME         NULL,
    [Copy of AFE_GUID]                 VARCHAR (50)     NULL,
    [Copy of AFESTATUS]                VARCHAR (50)     NULL,
    [Copy of AFEREVSUPMODE]            VARCHAR (1)      NULL,
    [Copy of EXTERNAL_ID]              VARCHAR (50)     NULL,
    [Copy of NEXT_REVIEWING_POSITION]  VARCHAR (50)     NULL,
    [Copy of SUPERSEDED_AFESTATUS]     VARCHAR (50)     NULL,
    [Copy of NEXT_APPROVING_POSITIONS] VARCHAR (4000)   NULL,
    [Copy of AFE_DOC]                  VARCHAR (50)     NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

