CREATE TABLE [stage].[t_afe_cost_estimates_qbyte] (
    [afe_num]                     VARCHAR (10)     NULL,
    [afe_name]                    VARCHAR (4000)   NULL,
    [cc_num]                      VARCHAR (100)    NULL,
    [uwi]                         VARCHAR (100)    NULL,
    [gl_account]                  VARCHAR (10)     NULL,
    [gl_net_account]              VARCHAR (10)     NULL,
    [grs_net_indicator]           VARCHAR (3)      NOT NULL,
    [scenario]                    VARCHAR (10)     NOT NULL,
    [project_id]                  VARCHAR (30)     NULL,
    [capital_project_number]      VARCHAR (23)     NULL,
    [organizations]               NVARCHAR (29)    NULL,
    [org_id]                      NUMERIC (4)      NULL,
    [op_flag]                     VARCHAR (3)      NOT NULL,
    [operator_client_id]          NUMERIC (6)      NULL,
    [contract_operator_client_id] NUMERIC (6)      NULL,
    [vendor_id]                   VARCHAR (14)     NOT NULL,
    [afe_job_type]                VARCHAR (20)     NOT NULL,
    [afe_job_subtype]             VARCHAR (23)     NOT NULL,
    [afe_job_status1]             VARCHAR (18)     NOT NULL,
    [afe_job_status2]             VARCHAR (26)     NOT NULL,
    [well_status]                 VARCHAR (14)     NULL,
    [primary_product]             VARCHAR (18)     NULL,
    [tax_stream]                  VARCHAR (34)     NULL,
    [engineer_assigned]           VARCHAR (45)     NULL,
    [run_id]                      VARCHAR (34)     NULL,
    [base_incr]                   VARCHAR (32)     NULL,
    [play]                        VARCHAR (33)     NULL,
    [acquisitions]                VARCHAR (34)     NULL,
    [dispositions]                VARCHAR (35)     NULL,
    [payout_type]                 VARCHAR (33)     NULL,
    [province]                    VARCHAR (12)     NOT NULL,
    [op_curr_code]                VARCHAR (6)      NULL,
    [reporting_curr_code]         VARCHAR (6)      NULL,
    [afe_client_id]               NVARCHAR (28)    NOT NULL,
    [afe_client_name]             NVARCHAR (4000)  NULL,
    [afe_start_date]              NVARCHAR (20)    NULL,
    [afe_approval_date]           DATETIME         NULL,
    [budget_year]                 VARCHAR (8000)   NULL,
    [project_approval_status]     VARCHAR (23)     NOT NULL,
    [project_execution_status]    VARCHAR (24)     NOT NULL,
    [afe_date]                    DATETIME         NULL,
    [acct_mnth]                   NVARCHAR (9)     NULL,
    [acct_yr]                     INT              NULL,
    [prod_mnth]                   NVARCHAR (9)     NULL,
    [prod_yr]                     INT              NULL,
    [major_grs_net_flag]          VARCHAR (3)      NOT NULL,
    [afe_type]                    VARCHAR (18)     NULL,
    [major_class_code]            VARCHAR (2)      NULL,
    [wip_expenses]                VARCHAR (23)     NOT NULL,
    [capital_or_dry_hole_expense] VARCHAR (19)     NOT NULL,
    [tax_code]                    VARCHAR (18)     NULL,
    [afe_status]                  VARCHAR (20)     NULL,
    [start_date]                  NVARCHAR (19)    NULL,
    [us_dollar_amt]               NUMERIC (16, 2)  NULL,
    [can_dollar_amt]              NUMERIC (16, 2)  NULL,
    [net_working_interest]        NUMERIC (14, 10) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

