CREATE TABLE [stage].[t_ctrl_fixed_var_opex] (
    [QBYTE_NET_MAJOR_MINOR]     VARCHAR (10) NULL,
    [QBYTE_MINOR_DESCRIPTION]   VARCHAR (40) NULL,
    [FIXED_OPEX_PERCENT]        NUMERIC (18) NULL,
    [VARIABLE_OPEX_PERCENT]     NUMERIC (18) NULL,
    [TOTAL_OPEX_PERCENT]        NUMERIC (18) NULL,
    [ECON_FIXED_PERCENT]        NUMERIC (18) NULL,
    [ECON_VARIABLE_GAS_PERCENT] NUMERIC (18) NULL,
    [ECON_VARIABLE_OIL_PERCENT] NUMERIC (18) NULL,
    [TOTAL_ECON_PERCENT]        NUMERIC (18) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

