CREATE TABLE [stage].[t_ctrl_etl_variables_20201028] (
    [VARIABLE_NAME]    VARCHAR (200)  NULL,
    [VARIABLE_VALUE]   VARCHAR (200)  NULL,
    [CUBE_NAME]        VARCHAR (50)   NULL,
    [DIMENSION_NAME]   VARCHAR (100)  NULL,
    [DIMENSION_MEMBER] VARCHAR (100)  NULL,
    [TARGET1_NAME]     VARCHAR (100)  NULL,
    [TARGET2_VALUE]    VARCHAR (100)  NULL,
    [COMMENTS]         VARCHAR (1000) NULL,
    [DATE_VALUE]       DATETIME       NULL,
    [INT_VALUE]        INT            NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

