CREATE TABLE [stage].[t_ctrl_special_accounts] (
    [account_id]                        VARCHAR (100)   NULL,
    [parent_id]                         VARCHAR (100)   NULL,
    [account_desc]                      VARCHAR (100)   NULL,
    [account_level_01]                  VARCHAR (500)   NULL,
    [account_level_02]                  VARCHAR (500)   NULL,
    [account_level_03]                  VARCHAR (500)   NULL,
    [account_level_04]                  VARCHAR (500)   NULL,
    [account_level_05]                  VARCHAR (500)   NULL,
    [account_level_06]                  VARCHAR (500)   NULL,
    [account_level_07]                  VARCHAR (500)   NULL,
    [account_level_08]                  VARCHAR (500)   NULL,
    [account_level_09]                  VARCHAR (500)   NULL,
    [account_level_10]                  VARCHAR (500)   NULL,
    [account_formula]                   VARCHAR (4000)  NULL,
    [account_formula_property]          VARCHAR (4000)  NULL,
    [unary_operator]                    VARCHAR (10)    NULL,
    [account_level_01_sort_key]         VARCHAR (500)   NULL,
    [account_level_02_sort_key]         VARCHAR (500)   NULL,
    [account_level_03_sort_key]         VARCHAR (500)   NULL,
    [account_level_04_sort_key]         VARCHAR (500)   NULL,
    [account_level_05_sort_key]         VARCHAR (500)   NULL,
    [account_level_06_sort_key]         VARCHAR (500)   NULL,
    [account_level_07_sort_key]         VARCHAR (500)   NULL,
    [account_level_08_sort_key]         VARCHAR (500)   NULL,
    [account_level_09_sort_key]         VARCHAR (500)   NULL,
    [account_level_10_sort_key]         VARCHAR (500)   NULL,
    [level]                             INT             NULL,
    [is_leaseops]                       INT             NULL,
    [is_volumes]                        INT             NULL,
    [is_capital]                        INT             NULL,
    [is_valnav]                         INT             NULL,
    [is_finance]                        INT             NULL,
    [source]                            VARCHAR (100)   NULL,
    [sort_key]                          VARCHAR (500)   NULL,
    [qbyte_major_minor]                 VARCHAR (50)    NULL,
    [afe_type]                          VARCHAR (50)    NULL,
    [account_level_01_formula]          VARCHAR (4000)  NULL,
    [account_level_01_formula_property] VARCHAR (4000)  NULL,
    [account_level_02_formula]          VARCHAR (4000)  NULL,
    [account_level_02_formula_property] VARCHAR (4000)  NULL,
    [account_level_03_formula]          VARCHAR (4000)  NULL,
    [account_level_03_formula_property] VARCHAR (4000)  NULL,
    [Hierarchy_Path_desc]               NVARCHAR (1000) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

