CREATE TABLE [stage].[t_fact_source_fdc_valnav_glj_volumes] (
    [site_id]                      VARCHAR (200)  NULL,
    [entity_key]                   VARCHAR (200)  NULL,
    [activity_date_key]            INT            NULL,
    [scenario_key]                 VARCHAR (1000) NULL,
    [data_type]                    VARCHAR (100)  NOT NULL,
    [gross_net_key]                INT            NOT NULL,
    [gas_metric_volume]            FLOAT (53)     NULL,
    [gas_imperial_volume]          FLOAT (53)     NULL,
    [gas_boe_volume]               FLOAT (53)     NULL,
    [gas_mcfe_volume]              FLOAT (53)     NULL,
    [oil_metric_volume]            FLOAT (53)     NULL,
    [oil_imperial_volume]          FLOAT (53)     NULL,
    [oil_boe_volume]               FLOAT (53)     NULL,
    [oil_mcfe_volume]              FLOAT (53)     NULL,
    [condensate_metric_volume]     FLOAT (53)     NULL,
    [condensate_imperial_volume]   FLOAT (53)     NULL,
    [condensate_boe_volume]        FLOAT (53)     NULL,
    [condensate_mcfe_volume]       FLOAT (53)     NULL,
    [ethane_metric_volume]         FLOAT (53)     NULL,
    [ethane_imperial_volume]       FLOAT (53)     NULL,
    [ethane_boe_volume]            FLOAT (53)     NULL,
    [ethane_mcfe_volume]           FLOAT (53)     NULL,
    [propane_metric_volume]        FLOAT (53)     NULL,
    [propane_imperial_volume]      FLOAT (53)     NULL,
    [propane_boe_volume]           FLOAT (53)     NULL,
    [propane_mcfe_volume]          FLOAT (53)     NULL,
    [butane_metric_volume]         FLOAT (53)     NULL,
    [butane_imperial_volume]       FLOAT (53)     NULL,
    [butane_boe_volume]            FLOAT (53)     NULL,
    [butane_mcfe_volume]           FLOAT (53)     NULL,
    [pentane_metric_volume]        FLOAT (53)     NULL,
    [pentane_imperial_volume]      FLOAT (53)     NULL,
    [pentane_boe_volume]           FLOAT (53)     NULL,
    [pentane_mcfe_volume]          FLOAT (53)     NULL,
    [total_ngl_metric_volume]      FLOAT (53)     NOT NULL,
    [total_ngl_imperial_volume]    FLOAT (53)     NOT NULL,
    [total_ngl_boe_volume]         FLOAT (53)     NOT NULL,
    [total_ngl_mcfe_volume]        FLOAT (53)     NOT NULL,
    [total_liquid_metric_volume]   FLOAT (53)     NOT NULL,
    [total_liquid_imperial_volume] FLOAT (53)     NOT NULL,
    [total_liquid_boe_volume]      FLOAT (53)     NOT NULL,
    [total_liquid_mcfe_volume]     FLOAT (53)     NOT NULL,
    [total_boe_volume]             FLOAT (53)     NOT NULL,
    [water_metric_volume]          FLOAT (53)     NULL,
    [water_imperial_volume]        FLOAT (53)     NULL,
    [water_boe_volume]             FLOAT (53)     NULL,
    [water_mcfe_volume]            FLOAT (53)     NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

