CREATE TABLE [stage].[t_ihs_xref_status] (
    [CODE]             VARCHAR (20) NULL,
    [SOURCE]           VARCHAR (16) NULL,
    [SOURCE_CODE]      VARCHAR (20) NULL,
    [ABREV]            VARCHAR (20) NULL,
    [NAME]             VARCHAR (60) NULL,
    [PLOT_SYMBOL]      VARCHAR (12) NULL,
    [V80C_CODE]        VARCHAR (20) NULL,
    [V80C_NAME]        VARCHAR (60) NULL,
    [V80C_PLOT_SYMBOL] VARCHAR (12) NULL,
    [IHSE_CODE]        VARCHAR (20) NULL,
    [IHSE_NAME]        VARCHAR (60) NULL,
    [IHSE_PLOT_SYMBOL] VARCHAR (12) NULL,
    [PETRA_FLUID]      VARCHAR (12) NULL,
    [ROW_CREATED_BY]   VARCHAR (30) NULL,
    [ROW_CREATED_DATE] DATETIME     NULL,
    [ROW_CHANGED_BY]   VARCHAR (30) NULL,
    [ROW_CHANGED_DATE] DATETIME     NULL,
    [PETRA_MODE]       VARCHAR (12) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

