CREATE TABLE [stage].[t_ihs_well_license_status] (
    [UWI]                      VARCHAR (20)   NULL,
    [LICENSE_ID]               VARCHAR (20)   NULL,
    [LICENSE_SOURCE]           VARCHAR (20)   NULL,
    [STATUS_ID]                VARCHAR (20)   NULL,
    [ACTIVE_IND]               VARCHAR (1)    NULL,
    [AREA_OFFICE]              VARCHAR (60)   NULL,
    [EFFECTIVE_DATE]           DATETIME       NULL,
    [EXPIRY_DATE]              DATETIME       NULL,
    [FINAL_DRILL_DATE]         DATETIME       NULL,
    [LICENSE_STATUS]           VARCHAR (20)   NULL,
    [LICENSE_STATUS_TYPE]      VARCHAR (20)   NULL,
    [LICENSEE]                 VARCHAR (20)   NULL,
    [PPDM_GUID]                VARCHAR (38)   NULL,
    [PROVINCE_STATE]           VARCHAR (20)   NULL,
    [REMARK]                   VARCHAR (2000) NULL,
    [SOURCE]                   VARCHAR (20)   NULL,
    [SURFACE_LOC]              VARCHAR (20)   NULL,
    [X_COMPLIANCE_STATUS]      VARCHAR (20)   NULL,
    [X_DEEMED_RISK_CLASS]      VARCHAR (20)   NULL,
    [X_INACTIVE_STATUS_DATE]   DATETIME       NULL,
    [X_IWCP]                   VARCHAR (20)   NULL,
    [X_LAST_VOL_ACTIVITY_DATE] DATETIME       NULL,
    [X_NEXT_INSPECTION_DATE]   DATETIME       NULL,
    [X_REPORTED_RISK_CLASS]    VARCHAR (20)   NULL,
    [X_REPORTED_SUSP_DATE]     DATETIME       NULL,
    [ROW_CHANGED_DATE]         DATETIME       NULL,
    [ROW_CHANGED_BY]           VARCHAR (30)   NULL,
    [ROW_CREATED_DATE]         DATETIME       NULL,
    [ROW_CREATED_BY]           VARCHAR (30)   NULL,
    [ROW_QUALITY]              VARCHAR (20)   NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

