CREATE TABLE [stage].[t_ihs_well_description] (
    [UWI]               VARCHAR (20)   NOT NULL,
    [LOCATION]          VARCHAR (24)   NULL,
    [WELL_ID]           VARCHAR (20)   NULL,
    [ROW_CREATED_DATE]  DATETIME       NULL,
    [ROW_CHANGED_DATE]  DATETIME       NULL,
    [CLASS]             VARCHAR (20)   NULL,
    [CLASS_DESC]        VARCHAR (60)   NULL,
    [CRSTATUS]          VARCHAR (20)   NULL,
    [CRSTATUS_DESC]     VARCHAR (60)   NULL,
    [OPERATOR]          VARCHAR (20)   NULL,
    [OPERATOR_DESC]     VARCHAR (60)   NULL,
    [FIELD]             VARCHAR (20)   NULL,
    [FIELD_DESC]        VARCHAR (60)   NULL,
    [POOL]              VARCHAR (20)   NULL,
    [POOL_DESC]         VARCHAR (60)   NULL,
    [UNIT]              VARCHAR (20)   NULL,
    [UNIT_DESC]         VARCHAR (60)   NULL,
    [SURF_LOCATION]     VARCHAR (24)   NULL,
    [KB_ELEV]           NUMERIC (7, 2) NULL,
    [GROUND_ELEV]       NUMERIC (7, 2) NULL,
    [TOTAL_DEPTH]       NUMERIC (7, 2) NULL,
    [TVD_DEPTH]         NUMERIC (7, 2) NULL,
    [NODE_ID]           VARCHAR (20)   NULL,
    [BASE_NODE_ID]      VARCHAR (20)   NULL,
    [WELL_NAME]         VARCHAR (50)   NULL,
    [FORM_AT_TD]        VARCHAR (20)   NULL,
    [FORM_AT_TD_TOP]    NUMERIC (12)   NULL,
    [FORM_AT_TD_DESC]   VARCHAR (60)   NULL,
    [SPUD_DATE]         DATETIME       NULL,
    [RIG_RELEASE]       DATETIME       NULL,
    [LICENSE_DATE]      DATETIME       NULL,
    [LICENSE_NO]        VARCHAR (9)    NULL,
    [DEVIATION_FLAG]    VARCHAR (1)    NULL,
    [BATTERY]           VARCHAR (20)   NULL,
    [LICENSEE]          VARCHAR (20)   NULL,
    [LICENSEE_DESC]     VARCHAR (60)   NULL,
    [OPERATOR_ABREV]    VARCHAR (20)   NULL,
    [OLDEST_FORM]       VARCHAR (20)   NULL,
    [OLDEST_FORM_TOP]   NUMERIC (12)   NULL,
    [OLDEST_FORM_DESC]  VARCHAR (60)   NULL,
    [ZONE]              VARCHAR (20)   NULL,
    [ZONE_TOP]          NUMERIC (12)   NULL,
    [ZONE_DESC]         VARCHAR (60)   NULL,
    [ZONE2]             VARCHAR (20)   NULL,
    [ZONE2_TOP]         NUMERIC (12)   NULL,
    [ZONE2_DESC]        VARCHAR (60)   NULL,
    [ZONE3]             VARCHAR (20)   NULL,
    [ZONE3_TOP]         NUMERIC (12)   NULL,
    [ZONE3_DESC]        VARCHAR (60)   NULL,
    [ZONE4]             VARCHAR (20)   NULL,
    [ZONE4_TOP]         NUMERIC (12)   NULL,
    [ZONE4_DESC]        VARCHAR (60)   NULL,
    [ZONE5]             VARCHAR (20)   NULL,
    [ZONE5_TOP]         NUMERIC (12)   NULL,
    [ZONE5_DESC]        VARCHAR (60)   NULL,
    [ZONE6]             VARCHAR (20)   NULL,
    [ZONE6_TOP]         NUMERIC (12)   NULL,
    [ZONE6_DESC]        VARCHAR (60)   NULL,
    [ZONE7]             VARCHAR (20)   NULL,
    [ZONE7_TOP]         NUMERIC (12)   NULL,
    [ZONE7_DESC]        VARCHAR (60)   NULL,
    [SOURCE]            VARCHAR (20)   NULL,
    [PROVINCE_STATE]    VARCHAR (20)   NOT NULL,
    [ROW_CHANGED_BY]    VARCHAR (30)   NULL,
    [ROW_CREATED_BY]    VARCHAR (30)   NULL,
    [ROW_QUALITY]       VARCHAR (30)   NULL,
    [STRAT_NAME_SET_ID] VARCHAR (20)   NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

