CREATE TABLE [stage].[t_ihs_well_license_incr] (
    [UWI]                      VARCHAR (20)    NULL,
    [LICENSE_ID]               VARCHAR (20)    NULL,
    [SOURCE]                   VARCHAR (20)    NULL,
    [ACTIVE_IND]               VARCHAR (1)     NULL,
    [AGENT]                    VARCHAR (20)    NULL,
    [APPLICATION_ID]           VARCHAR (20)    NULL,
    [AUTHORIZED_STRAT_UNIT_ID] VARCHAR (20)    NULL,
    [BIDDING_ROUND_NUM]        VARCHAR (20)    NULL,
    [CONTRACTOR]               VARCHAR (20)    NULL,
    [DIRECTION_TO_LOC]         NUMERIC (5, 2)  NULL,
    [DIRECTION_TO_LOC_OUOM]    VARCHAR (20)    NULL,
    [DISTANCE_REF_POINT]       VARCHAR (20)    NULL,
    [DISTANCE_TO_LOC]          NUMERIC (7, 2)  NULL,
    [DISTANCE_TO_LOC_OUOM]     VARCHAR (20)    NULL,
    [DRILL_RIG_NUM]            VARCHAR (20)    NULL,
    [DRILL_SLOT_NO]            NUMERIC (4)     NULL,
    [DRILL_TOOL]               VARCHAR (20)    NULL,
    [EFFECTIVE_DATE]           DATETIME        NULL,
    [EXCEPTION_GRANTED]        VARCHAR (20)    NULL,
    [EXCEPTION_REQUESTED]      VARCHAR (20)    NULL,
    [EXPIRED_IND]              VARCHAR (1)     NULL,
    [EXPIRY_DATE]              DATETIME        NULL,
    [FEES_PAID_IND]            VARCHAR (1)     NULL,
    [LICENSEE]                 VARCHAR (20)    NULL,
    [LICENSEE_CONTACT_ID]      VARCHAR (20)    NULL,
    [LICENSE_DATE]             DATETIME        NULL,
    [LICENSE_NUM]              VARCHAR (9)     NULL,
    [NO_OF_WELLS]              NUMERIC (2)     NULL,
    [OFFSHORE_COMPLETION_TYPE] VARCHAR (20)    NULL,
    [PERMIT_REFERENCE_NUM]     VARCHAR (20)    NULL,
    [PERMIT_REISSUE_DATE]      DATETIME        NULL,
    [PERMIT_TYPE]              VARCHAR (20)    NULL,
    [PLATFORM_NAME]            VARCHAR (32)    NULL,
    [PPDM_GUID]                VARCHAR (38)    NULL,
    [PROJECTED_DEPTH]          NUMERIC (10, 5) NULL,
    [PROJECTED_DEPTH_OUOM]     VARCHAR (20)    NULL,
    [PROJECTED_STRAT_UNIT_ID]  VARCHAR (20)    NULL,
    [PROJECTED_TVD]            NUMERIC (10, 5) NULL,
    [PROJECTED_TVD_OUOM]       VARCHAR (20)    NULL,
    [PROPOSED_SPUD_DATE]       DATETIME        NULL,
    [PURPOSE]                  VARCHAR (240)   NULL,
    [RATE_SCHEDULE_ID]         VARCHAR (20)    NULL,
    [REGULATION]               VARCHAR (20)    NULL,
    [REGULATORY_AGENCY]        VARCHAR (20)    NULL,
    [REGULATORY_CONTACT_ID]    VARCHAR (20)    NULL,
    [REMARK]                   VARCHAR (2000)  NULL,
    [RIG_CODE]                 VARCHAR (20)    NULL,
    [RIG_SUBSTR_HEIGHT]        NUMERIC (7, 2)  NULL,
    [RIG_SUBSTR_HEIGHT_OUOM]   VARCHAR (20)    NULL,
    [RIG_TYPE]                 VARCHAR (20)    NULL,
    [SECTION_OF_REGULATION]    VARCHAR (240)   NULL,
    [STRAT_NAME_SET_ID]        VARCHAR (20)    NULL,
    [SURVEYOR]                 VARCHAR (20)    NULL,
    [TARGET_OBJECTIVE_FLUID]   VARCHAR (20)    NULL,
    [ROW_CHANGED_BY]           VARCHAR (30)    NULL,
    [ROW_CHANGED_DATE]         DATETIME        NULL,
    [ROW_CREATED_BY]           VARCHAR (30)    NULL,
    [ROW_CREATED_DATE]         DATETIME        NULL,
    [ROW_QUALITY]              VARCHAR (20)    NULL,
    [PROVINCE_STATE]           VARCHAR (20)    NULL,
    [X_WELL_OBJECTIVE]         VARCHAR (20)    NULL,
    [X_WELL_TYPE]              VARCHAR (20)    NULL,
    [PROJECTED_STRAT_AGE]      NUMERIC (12)    NULL,
    [X_ORIGINAL_LICENSEE]      VARCHAR (20)    NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

