CREATE TABLE [stage].[t_pwv_ap_header_tbl] (
    [DOCUMENT]               VARCHAR (40)     NOT NULL,
    [FOLDER_ID]              DATETIME         NOT NULL,
    [PWR_ID]                 INT              NOT NULL,
    [PWR_CREATE_DATE]        DATETIME         NULL,
    [PWR_STATUS]             INT              NULL,
    [PWR_WF_PATH]            VARCHAR (10)     NULL,
    [PWR_MILESTONE_ID]       VARCHAR (30)     NULL,
    [PWR_BA_INFO]            VARCHAR (254)    NULL,
    [PWR_BA_COMMENTS]        VARCHAR (254)    NULL,
    [PWR_PRE_APPROVED]       INT              NULL,
    [PWR_BYPASS_UPLOAD]      INT              NULL,
    [PWR_QUICK_PAY]          INT              NULL,
    [PWR_QP_BY_APPROVER]     INT              NULL,
    [PWR_LAST_APPROVER]      VARCHAR (40)     NULL,
    [PWR_LAST_APPROVAL_DATE] DATETIME         NULL,
    [SHORT_PAY]              INT              NULL,
    [SHORT_PAY_AMT]          NUMERIC (14, 2)  NULL,
    [INVC_NUM]               VARCHAR (40)     NULL,
    [INVC_DATE]              DATETIME         NULL,
    [INVC_AMT]               NUMERIC (14, 2)  NULL,
    [GST_AMT]                NUMERIC (14, 2)  NULL,
    [DUE_DATE]               DATETIME         NULL,
    [ORG_ID]                 INT              NULL,
    [CREATE_USER]            VARCHAR (32)     NULL,
    [CURR_CODE]              VARCHAR (6)      NULL,
    [INVC_REM]               VARCHAR (120)    NULL,
    [DEPOSIT_DATE]           DATETIME         NULL,
    [SEPARATE_CHQ_FLAG]      INT              NULL,
    [MEDIUM_CODE]            VARCHAR (1)      NULL,
    [BANK_ACCT_ID]           VARCHAR (4)      NULL,
    [VOUCHER_TYPE_CODE]      VARCHAR (5)      NULL,
    [VOUCHER_NUM]            VARCHAR (5)      NULL,
    [ACCT_TYPE]              VARCHAR (254)    NULL,
    [ACCT_PER_DATE]          DATETIME         NULL,
    [PURCHASE_ORDER_NUM]     VARCHAR (20)     NULL,
    [VOUCHER_REM]            VARCHAR (40)     NULL,
    [BA_ID]                  INT              NULL,
    [ALTERNATE_ADDRESS_ID]   INT              NULL,
    [CONTRACT_NUM]           VARCHAR (20)     NULL,
    [RCVD_DATE]              DATETIME         NULL,
    [HOLD_DATE]              DATETIME         NULL,
    [PAYMENT_CODE]           VARCHAR (3)      NULL,
    [PAYMENT_FORMAT_CODE]    VARCHAR (6)      NULL,
    [PAYMENT_HANDLING_CODE]  VARCHAR (2)      NULL,
    [DISCOUNT_DATE]          DATETIME         NULL,
    [DISCOUNT_PCT]           NUMERIC (14, 10) NULL,
    [DISCOUNT_AMT]           NUMERIC (14, 2)  NULL,
    [PST_AMT]                NUMERIC (14, 2)  NULL,
    [PAYMENT_REFERENCE]      VARCHAR (20)     NULL,
    [PAYMENT_DATE]           DATETIME         NULL,
    [PAYMENT_AMOUNT]         NUMERIC (14, 2)  NULL,
    [PAYMENT_METHOD]         VARCHAR (5)      NULL,
    [TAX_PROVINCE]           VARCHAR (2)      NULL,
    [EXCHANGE_RATE]          NUMERIC (14, 10) NULL,
    [FIELD_TICKET_NUMBERS]   VARCHAR (2000)   NULL,
    [POSTED_DATE]            DATE             NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

