CREATE TABLE [stage].[t_qbyte_business_associates] (
    [CREATE_DATE]            DATETIME      NULL,
    [CREATE_USER]            VARCHAR (30)  NULL,
    [LAST_UPDATE_USER]       VARCHAR (30)  NULL,
    [LAST_UPDATE_DATE]       DATETIME      NULL,
    [ID]                     NUMERIC (10)  NULL,
    [NAME_1]                 VARCHAR (40)  NULL,
    [SHORT_NAME]             VARCHAR (40)  NULL,
    [BA_TYPE_CODE]           VARCHAR (8)   NULL,
    [NON_RESIDENT_FLAG]      VARCHAR (1)   NULL,
    [BN_REGISTRATION_NUMBER] VARCHAR (20)  NULL,
    [SIN_SSN]                VARCHAR (9)   NULL,
    [NAME_2]                 VARCHAR (40)  NULL,
    [REF_ORG_ID]             NUMERIC (4)   NULL,
    [CHANGED_TO_BA_ID]       NUMERIC (10)  NULL,
    [DUN_AND_BRADSTREET_REF] VARCHAR (10)  NULL,
    [LEGAL_NAME]             VARCHAR (300) NULL,
    [BA_UDF_1_CODE]          VARCHAR (30)  NULL,
    [BA_UDF_2_CODE]          VARCHAR (30)  NULL,
    [BA_UDF_3_CODE]          VARCHAR (30)  NULL,
    [BA_UDF_4_CODE]          VARCHAR (30)  NULL,
    [BA_UDF_5_CODE]          VARCHAR (30)  NULL,
    [BA_UDF_6_CODE]          VARCHAR (30)  NULL,
    [BA_UDF_7_CODE]          VARCHAR (30)  NULL,
    [BA_UDF_8_CODE]          VARCHAR (30)  NULL,
    [BA_UDF_9_CODE]          VARCHAR (30)  NULL,
    [BA_UDF_10_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_11_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_12_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_13_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_14_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_15_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_16_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_17_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_18_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_19_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_20_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_21_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_22_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_23_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_24_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_25_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_26_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_27_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_28_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_29_CODE]         VARCHAR (30)  NULL,
    [BA_UDF_30_CODE]         VARCHAR (30)  NULL,
    [ALTERNATE_ID]           VARCHAR (12)  NULL,
    [EMPLOYEE_NUM]           VARCHAR (10)  NULL,
    [EFFECTIVE_DATE]         DATETIME      NULL,
    [INACTIVE_DATE]          DATETIME      NULL,
    [INACTIVATED_USER]       VARCHAR (32)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

