CREATE TABLE [stage].[t_qbyte_cost_centre_legals] (
    [ID]                 NUMERIC (10) NULL,
    [CC_NUM]             VARCHAR (10) NULL,
    [CREATE_DATE]        DATETIME     NULL,
    [CREATE_USER]        VARCHAR (30) NULL,
    [LAST_UPDATE_DATE]   DATETIME     NULL,
    [LAST_UPDATE_USER]   VARCHAR (30) NULL,
    [PRIMARY_FLAG]       VARCHAR (1)  NULL,
    [SURVEY_SYSTEM_CODE] VARCHAR (6)  NULL,
    [LOCATION_ELEMENT_1] VARCHAR (7)  NULL,
    [LOCATION_ELEMENT_2] VARCHAR (7)  NULL,
    [LOCATION_ELEMENT_3] VARCHAR (7)  NULL,
    [LOCATION_ELEMENT_4] VARCHAR (7)  NULL,
    [LOCATION_ELEMENT_5] VARCHAR (7)  NULL,
    [LOCATION_ELEMENT_6] VARCHAR (7)  NULL,
    [LOCATION_ELEMENT_7] VARCHAR (7)  NULL,
    [LOCATION_ELEMENT_8] VARCHAR (7)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

