CREATE TABLE [stage].[t_qbyte_accounts] (
    [CREATE_DATE]                    DATETIME         NULL,
    [CREATE_USER]                    VARCHAR (30)     NULL,
    [MAJOR_ACCT]                     VARCHAR (4)      NULL,
    [MINOR_ACCT]                     VARCHAR (4)      NULL,
    [ACCT_DESC]                      VARCHAR (40)     NULL,
    [AFE_REQD_FLAG]                  VARCHAR (1)      NULL,
    [CC_REQD_FLAG]                   VARCHAR (1)      NULL,
    [VOL_REQD_FLAG]                  VARCHAR (1)      NULL,
    [ACTVY_DATE_REQD_FLAG]           VARCHAR (1)      NULL,
    [CONTINUITY_REQD_FLAG]           VARCHAR (1)      NULL,
    [ENV_ALLOWED_FLAG]               VARCHAR (1)      NULL,
    [ALT_CLIENT_REQD_FLAG]           VARCHAR (1)      NULL,
    [ALT_GL_CODE_REQD_FLAG]          VARCHAR (1)      NULL,
    [CTRL_EQUIP_REQD_FLAG]           VARCHAR (1)      NULL,
    [BUDGET_IN_VOLUMES_FLAG]         VARCHAR (1)      NULL,
    [ORACLE_ASSETS_REQD_FLAG]        VARCHAR (1)      NULL,
    [GL_SUB_CODE_REQD_FLAG]          VARCHAR (1)      NULL,
    [JIB_FOOTNOTE_REQD_FLAG]         VARCHAR (1)      NULL,
    [ENERGY_CONTENT_REQD_FLAG]       VARCHAR (1)      NULL,
    [CONT_EQUIP_FOOTNOTE_REQD_FLAG]  VARCHAR (1)      NULL,
    [PROCESS_ONLY_ACCT_FLAG]         VARCHAR (1)      NULL,
    [USER_DEFINED_TAG_FLAG]          VARCHAR (1)      NULL,
    [EXCLUDE_AFE_COSTS_FROM_CC_OH]   VARCHAR (1)      NULL,
    [LAST_UPDT_DATE]                 DATETIME         NULL,
    [LAST_UPDT_USER]                 VARCHAR (32)     NULL,
    [CTRL_ACCT_TYPE_CODE]            VARCHAR (2)      NULL,
    [PROD_CODE]                      VARCHAR (6)      NULL,
    [GST_FACTOR]                     NUMERIC (14, 10) NULL,
    [PASC_ACCT]                      VARCHAR (10)     NULL,
    [DEFAULT_CURR_TYPE_CODE]         VARCHAR (1)      NULL,
    [CURR_CONVERSION_RULE_CODE]      VARCHAR (6)      NULL,
    [TERM_DATE]                      DATETIME         NULL,
    [TERM_USER]                      VARCHAR (32)     NULL,
    [TO_CAPITAL_MAJOR_ACCT]          VARCHAR (4)      NULL,
    [TO_CAPITAL_MINOR_ACCT]          VARCHAR (4)      NULL,
    [TO_EXPENSE_MAJOR_ACCT]          VARCHAR (4)      NULL,
    [TO_EXPENSE_MINOR_ACCT]          VARCHAR (4)      NULL,
    [CURR_CODE]                      VARCHAR (6)      NULL,
    [DDA_RULE_CODE]                  VARCHAR (6)      NULL,
    [ACCOUNT_COMPANY_CODE]           VARCHAR (1)      NULL,
    [ACCRUAL_MAJOR_ACCT]             VARCHAR (4)      NULL,
    [ACCRUAL_MINOR_ACCT]             VARCHAR (4)      NULL,
    [INVOICE_APPROVAL_COST_CATEGORY] VARCHAR (6)      NULL,
    [USER_DEFINED_TAG_PROMPT]        VARCHAR (20)     NULL,
    [ENV_CODE_PROMPT]                VARCHAR (20)     NULL,
    [RE_OCI_FLAG]                    VARCHAR (1)      NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

