CREATE TABLE [stage].[t_qbyte_clients] (
    [CLIENT_ID]                  NUMERIC (10)     NULL,
    [CLIENT_NAME1]               VARCHAR (40)     NULL,
    [PAYMENT_CODE]               VARCHAR (3)      NULL,
    [CLIENT_CODE]                VARCHAR (12)     NULL,
    [CLIENT_NAME2]               VARCHAR (40)     NULL,
    [CLIENT_ADDRESS1]            VARCHAR (40)     NULL,
    [CLIENT_ADDRESS2]            VARCHAR (40)     NULL,
    [CLIENT_ADDRESS3]            VARCHAR (40)     NULL,
    [CLIENT_ADDRESS4]            VARCHAR (40)     NULL,
    [CLIENT_CITY]                VARCHAR (40)     NULL,
    [CLIENT_PROVINCE]            VARCHAR (2)      NULL,
    [CLIENT_COUNTRY_CODE]        VARCHAR (2)      NULL,
    [CLIENT_POSTALCODE]          VARCHAR (10)     NULL,
    [PHONE_NUM]                  VARCHAR (17)     NULL,
    [FAX_NUM]                    VARCHAR (17)     NULL,
    [TELEX_NUM]                  VARCHAR (17)     NULL,
    [AP_CREDIT_DAYS]             NUMERIC (3)      NULL,
    [AR_CREDIT_DAYS]             NUMERIC (3)      NULL,
    [BILLING_CODE]               VARCHAR (1)      NULL,
    [ADX_NUM]                    VARCHAR (4)      NULL,
    [WORKERS_COMP_FLAG]          VARCHAR (1)      NULL,
    [WITHOLDING_TAX_FLAG]        VARCHAR (1)      NULL,
    [GST_REG_NUM]                VARCHAR (20)     NULL,
    [DUN_AND_BRADSTREET_REF]     VARCHAR (10)     NULL,
    [HOLD_DATE]                  DATETIME         NULL,
    [TRANSACTING_CLIENT_ID]      NUMERIC (10)     NULL,
    [CHANGED_TO_CLIENT_ID]       NUMERIC (10)     NULL,
    [PAY_TO_CLIENT_ID]           NUMERIC (10)     NULL,
    [CREATE_DATE]                DATETIME         NULL,
    [CREATE_USER]                VARCHAR (30)     NULL,
    [TERM_DATE]                  DATETIME         NULL,
    [TERM_USER]                  VARCHAR (30)     NULL,
    [LAST_UPDT_DATE]             DATETIME         NULL,
    [LAST_UPDT_USER]             VARCHAR (30)     NULL,
    [ORG_REF_ID]                 NUMERIC (4)      NULL,
    [AR_CREDIT_LIMIT_AMT]        NUMERIC (14, 2)  NULL,
    [CREDIT_REVISED_DATE]        DATETIME         NULL,
    [SIN_SSN]                    VARCHAR (9)      NULL,
    [REC_FORMAT_CODE]            VARCHAR (6)      NULL,
    [SEND_FORMAT_CODE]           VARCHAR (6)      NULL,
    [SEND_METHOD_CODE]           VARCHAR (6)      NULL,
    [USE_JIBE_DOI_EDITS_FLAG]    VARCHAR (1)      NULL,
    [CLIENT_LEGAL_NAME]          VARCHAR (300)    NULL,
    [CHANGED_TO_ALT_ADDRESS_ID]  NUMERIC (10)     NULL,
    [DISCOUNT_CREDIT_DAYS]       NUMERIC (3)      NULL,
    [DISCOUNT_PCT]               NUMERIC (14, 10) NULL,
    [SUBSYSTEM_COMPONENT_ID]     NUMERIC (10)     NULL,
    [EXTERNAL_LINK_REF]          VARCHAR (10)     NULL,
    [ALTERNATE_CLIENT_ID_REQD]   VARCHAR (1)      NULL,
    [CLIENT_TYPE_CODE]           VARCHAR (8)      NULL,
    [DEFAULT_ADDRESS_SHORT_NAME] VARCHAR (15)     NULL,
    [DEFAULT_BA_ADDRESS_ID]      NUMERIC (10)     NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

