CREATE TABLE [stage].[t_qbyte_voucher_types] (
    [VOUCHER_TYPE_CODE]           VARCHAR (6)  NOT NULL,
    [VOUCHER_TYPE_DESC]           VARCHAR (40) NOT NULL,
    [GL_REPORTING_LEVEL_CODE]     VARCHAR (1)  NOT NULL,
    [ON_LINE_POST_FLAG]           VARCHAR (1)  NULL,
    [ACCRUAL_FLAG]                VARCHAR (1)  NULL,
    [STANDARD_ENTRY_TYPE_FLAG]    VARCHAR (1)  NULL,
    [VOUCHER_TYPE_USE_CODE]       VARCHAR (1)  NULL,
    [AUTO_GEN_IN_BATCH_EDIT_FLAG] VARCHAR (1)  NULL,
    [POPULATE_COMPANY_CODE_FLAG]  VARCHAR (1)  NULL,
    [TRANSLATION_MODE]            VARCHAR (1)  NULL,
    [CURRENCY_ADJUSTMENT_FLAG]    VARCHAR (1)  NULL,
    [CREATE_DATE]                 DATETIME     NULL,
    [CREATE_USER]                 VARCHAR (30) NULL,
    [LAST_UPDATE_DATE]            DATETIME     NULL,
    [LAST_UPDATE_USER]            VARCHAR (30) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

