CREATE TABLE [stage].[t_qbyte_authorizations_for_expenditure] (
    [CREATE_DATE]                  DATETIME         NULL,
    [CREATE_USER]                  VARCHAR (30)     NULL,
    [AFE_NUM]                      VARCHAR (10)     NULL,
    [AFE_TYPE_CODE]                VARCHAR (6)      NULL,
    [AFE_NAME]                     VARCHAR (40)     NULL,
    [AFE_STAT_CODE]                VARCHAR (10)     NULL,
    [CURR_CODE]                    VARCHAR (6)      NULL,
    [OWNERSHIP_ORG_ID]             NUMERIC (4)      NULL,
    [JIB_FLAG]                     VARCHAR (1)      NULL,
    [CIP_TRANSFER_FLAG]            VARCHAR (1)      NULL,
    [USE_JIBE_EDITS_FLAG]          VARCHAR (1)      NULL,
    [ACCRUAL_FLAG]                 VARCHAR (1)      NULL,
    [LAST_UPDT_DATE]               DATETIME         NULL,
    [LAST_UPDT_USER]               VARCHAR (32)     NULL,
    [BUDGET_ACTIVITY_ID]           VARCHAR (10)     NULL,
    [BUDGET_ACTIVITY_YEAR]         DATETIME         NULL,
    [EFFECTIVE_DATE]               DATETIME         NULL,
    [PROPOSAL_DATE]                DATETIME         NULL,
    [APPROVAL_DATE]                DATETIME         NULL,
    [DUE_DATE]                     DATETIME         NULL,
    [COMMITMENT_DATE]              DATETIME         NULL,
    [ALLOC_AMT]                    NUMERIC (14, 2)  NULL,
    [TAX_CODE]                     VARCHAR (10)     NULL,
    [TERM_DATE]                    DATETIME         NULL,
    [TERM_USER]                    VARCHAR (32)     NULL,
    [AFE_START_DATE]               DATETIME         NULL,
    [AFE_FINISH_DATE]              DATETIME         NULL,
    [CAPITAL_ACCRUAL_METHOD_CODE]  VARCHAR (6)      NULL,
    [MANAGING_ORG_ID]              NUMERIC (4)      NULL,
    [NET_ESTIMATE_PCT]             NUMERIC (14, 10) NULL,
    [INTERNAL_APPROVER]            VARCHAR (40)     NULL,
    [PROVINCE]                     VARCHAR (2)      NULL,
    [MANAGER_NAME]                 VARCHAR (20)     NULL,
    [SUCCESS_EFFORT_TYPE_CODE]     VARCHAR (1)      NULL,
    [CAPITAL_ACCRUAL_CC_NUM]       VARCHAR (10)     NULL,
    [GEOLOGIST_ASSIGNED]           VARCHAR (40)     NULL,
    [GEOPHYSICIST_ASSIGNED]        VARCHAR (40)     NULL,
    [ENGINEER_ASSIGNED]            VARCHAR (40)     NULL,
    [EQUIP_COMPONENT_AMT]          NUMERIC (14, 2)  NULL,
    [WRHSE_COMPONENT_AMT]          NUMERIC (14, 2)  NULL,
    [TRANSLATION_RATE]             NUMERIC (14, 10) NULL,
    [ORIGINAL_ALLOC_AMT]           NUMERIC (14, 2)  NULL,
    [REPORTING_ALLOC_AMT]          NUMERIC (14, 2)  NULL,
    [ALLOW_OTHER_ORGS_CODE]        VARCHAR (1)      NULL,
    [SURVEY_SYSTEM_CODE]           VARCHAR (6)      NULL,
    [LOCATION_ELEMENT_1]           VARCHAR (7)      NULL,
    [LOCATION_ELEMENT_2]           VARCHAR (7)      NULL,
    [LOCATION_ELEMENT_3]           VARCHAR (7)      NULL,
    [LOCATION_ELEMENT_4]           VARCHAR (7)      NULL,
    [LOCATION_ELEMENT_5]           VARCHAR (7)      NULL,
    [LOCATION_ELEMENT_6]           VARCHAR (7)      NULL,
    [LOCATION_ELEMENT_7]           VARCHAR (7)      NULL,
    [LOCATION_ELEMENT_8]           VARCHAR (7)      NULL,
    [LAST_UPDT_STATUS_USER]        VARCHAR (32)     NULL,
    [LAST_UPDT_STATUS_DATE]        DATETIME         NULL,
    [DOI_TYPE_CODE]                VARCHAR (8)      NULL,
    [AFE_CLASS_CODE]               VARCHAR (6)      NULL,
    [DEFAULT_GL_SUB_CODE]          VARCHAR (6)      NULL,
    [OVERHEAD_START_DATE]          DATETIME         NULL,
    [OVERHEAD_END_DATE]            DATETIME         NULL,
    [CAPITAL_OR_DRY_HOLE_EXP_CODE] VARCHAR (1)      NULL,
    [AFE_UDF_1_CODE]               VARCHAR (30)     NULL,
    [AFE_UDF_2_CODE]               VARCHAR (30)     NULL,
    [AFE_UDF_3_CODE]               VARCHAR (30)     NULL,
    [AFE_UDF_4_CODE]               VARCHAR (30)     NULL,
    [AFE_UDF_5_CODE]               VARCHAR (30)     NULL,
    [AFE_UDF_6_CODE]               VARCHAR (30)     NULL,
    [AFE_UDF_7_CODE]               VARCHAR (30)     NULL,
    [AFE_UDF_8_CODE]               VARCHAR (30)     NULL,
    [AFE_UDF_9_CODE]               VARCHAR (30)     NULL,
    [AFE_UDF_10_CODE]              VARCHAR (30)     NULL,
    [AFE_UDF_11_CODE]              VARCHAR (30)     NULL,
    [AFE_UDF_12_CODE]              VARCHAR (30)     NULL,
    [AFE_UDF_13_CODE]              VARCHAR (30)     NULL,
    [AFE_UDF_14_CODE]              VARCHAR (30)     NULL,
    [AFE_UDF_15_CODE]              VARCHAR (30)     NULL,
    [AFE_UDF_16_CODE]              VARCHAR (30)     NULL,
    [AFE_UDF_17_CODE]              VARCHAR (30)     NULL,
    [AFE_UDF_18_CODE]              VARCHAR (30)     NULL,
    [AFE_UDF_19_CODE]              VARCHAR (30)     NULL,
    [AFE_UDF_20_CODE]              VARCHAR (30)     NULL,
    [AFE_REPORTING_UDF_1_CODE]     VARCHAR (30)     NULL,
    [AFE_REPORTING_UDF_2_CODE]     VARCHAR (30)     NULL,
    [AFE_REPORTING_UDF_3_CODE]     VARCHAR (30)     NULL,
    [LAST_ACCRUED_DATE]            DATETIME         NULL,
    [COUNTRY_CODE]                 VARCHAR (2)      NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

