CREATE TABLE [stage].[t_qbyte_fa_ba_properties] (
    [CREATE_DATE]                    DATETIME         NULL,
    [CREATE_USER]                    VARCHAR (32)     NULL,
    [LAST_UPDATE_DATE]               DATETIME         NULL,
    [LAST_UPDATE_USER]               VARCHAR (32)     NULL,
    [BA_ID]                          NUMERIC (10)     NULL,
    [EFFECTIVE_DATE]                 DATETIME         NULL,
    [ALTERNATE_BA_ID_REQD_FLAG]      VARCHAR (1)      NULL,
    [USE_JIBE_DOI_EDITS_FLAG]        VARCHAR (1)      NULL,
    [WITHOLDING_TAX_FLAG]            VARCHAR (1)      NULL,
    [WORKERS_COMP_FLAG]              VARCHAR (1)      NULL,
    [PAYMENT_CODE]                   VARCHAR (3)      NULL,
    [BILLING_CODE]                   VARCHAR (1)      NULL,
    [HOLD_DATE]                      DATETIME         NULL,
    [SUBSYSTEM_COMPONENT_ID]         NUMERIC (10)     NULL,
    [TRANSACTING_BA_ID]              NUMERIC (10)     NULL,
    [PAID_TO_BA_ID]                  NUMERIC (10)     NULL,
    [AP_CREDIT_DAYS]                 NUMERIC (3)      NULL,
    [AR_CREDIT_DAYS]                 NUMERIC (3)      NULL,
    [AR_CREDIT_LIMIT_AMT]            NUMERIC (14, 2)  NULL,
    [CREDIT_REVISED_DATE]            DATETIME         NULL,
    [DISCOUNT_CREDIT_DAYS]           NUMERIC (3)      NULL,
    [DISCOUNT_PCT]                   NUMERIC (14, 10) NULL,
    [REC_FORMAT_CODE]                VARCHAR (6)      NULL,
    [SEND_FORMAT_CODE]               VARCHAR (6)      NULL,
    [SEND_METHOD_CODE]               VARCHAR (6)      NULL,
    [ADX_NUM]                        VARCHAR (4)      NULL,
    [INACTIVE_DATE]                  DATETIME         NULL,
    [INACTIVATED_USER]               VARCHAR (30)     NULL,
    [DEFAULT_BA_ADDRESS_ID]          NUMERIC (10)     NULL,
    [INVC_DATE_IN_UNIQUE_CHECK_FLAG] VARCHAR (1)      NULL,
    [EXCLUDE_FROM_DUP_PAYMENT_FLAG]  VARCHAR (1)      NULL,
    [PRINT_JIB_STATEMENT_FLAG]       VARCHAR (1)      NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

