CREATE TABLE [stage].[t_qbyte_major_accounts] (
    [CREATE_DATE]                    DATETIME     NULL,
    [CREATE_USER]                    VARCHAR (32) NULL,
    [MAJOR_ACCT]                     VARCHAR (4)  NULL,
    [MAJOR_ACCT_DESC]                VARCHAR (40) NULL,
    [CLASS_CODE]                     VARCHAR (2)  NULL,
    [GROSS_OR_NET_CODE]              VARCHAR (1)  NULL,
    [AFE_REQD_DFLT_FLAG]             VARCHAR (1)  NULL,
    [CC_REQD_DFLT_FLAG]              VARCHAR (1)  NULL,
    [VOL_REQD_DFLT_FLAG]             VARCHAR (1)  NULL,
    [ACTVY_DATE_REQD_DFLT_FLAG]      VARCHAR (1)  NULL,
    [CONTINUITY_REQD_DFLT_FLAG]      VARCHAR (1)  NULL,
    [ENV_ALLOWED_DFLT_FLAG]          VARCHAR (1)  NULL,
    [ALT_CLIENT_REQD_DFLT_FLAG]      VARCHAR (1)  NULL,
    [ALT_GL_CODE_REQD_DFLT_FLAG]     VARCHAR (1)  NULL,
    [CTRL_EQUIP_REQD_DFLT_FLAG]      VARCHAR (1)  NULL,
    [LAST_UPDT_DATE]                 DATETIME     NULL,
    [LAST_UPDT_USER]                 VARCHAR (32) NULL,
    [NET_MAJOR_ACCT]                 VARCHAR (4)  NULL,
    [CTRL_ACCT_TYPE_DFLT_CODE]       VARCHAR (2)  NULL,
    [ACCRUAL_MAJOR_ACCT]             VARCHAR (4)  NULL,
    [ACCRUAL_MINOR_ACCT]             VARCHAR (4)  NULL,
    [DEFAULT_CURR_TYPE_DFLT_CODE]    VARCHAR (1)  NULL,
    [CURR_CONV_RULE_DFLT_CODE]       VARCHAR (6)  NULL,
    [TERM_DATE]                      DATETIME     NULL,
    [TERM_USER]                      VARCHAR (32) NULL,
    [TAX_CLASS_RULE_FLAG]            VARCHAR (1)  NULL,
    [GL_SUB_CODE_REQD_DFLT_FLAG]     VARCHAR (1)  NULL,
    [JIB_FOOTNOTE_REQD_DFLT_FLAG]    VARCHAR (1)  NULL,
    [CONT_EQUIP_FOOT_REQD_DFLT_FLAG] VARCHAR (1)  NULL,
    [RE_OCI_DFLT_FLAG]               VARCHAR (1)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

