CREATE TABLE [stage].[t_qbyte_cost_centres] (
    [CREATE_DATE]                    DATETIME         NULL,
    [CREATE_USER]                    VARCHAR (30)     NULL,
    [CC_NUM]                         VARCHAR (10)     NULL,
    [CC_TYPE_CODE]                   VARCHAR (3)      NULL,
    [CC_NAME]                        VARCHAR (40)     NULL,
    [OWNERSHIP_ORG_ID]               NUMERIC (4)      NULL,
    [JIB_FLAG]                       VARCHAR (1)      NULL,
    [ALT_GL_CODE_REQD_FLAG]          VARCHAR (1)      NULL,
    [USE_JIBE_EDITS_FLAG]            VARCHAR (1)      NULL,
    [MANAGING_ORG_ID]                NUMERIC (4)      NULL,
    [OC_COST_CENTRE_FLAG]            VARCHAR (1)      NULL,
    [LAST_UPDT_DATE]                 DATETIME         NULL,
    [LAST_UPDT_USER]                 VARCHAR (32)     NULL,
    [LAND_FILE_NUMBER]               VARCHAR (10)     NULL,
    [LEASE_SPLIT_NUMBER]             NUMERIC (4)      NULL,
    [OPERATOR_CC_NUM]                VARCHAR (10)     NULL,
    [UNIT_CODE]                      NUMERIC (5)      NULL,
    [UNIT_CC_NUM]                    VARCHAR (10)     NULL,
    [TAX_STREAM_CODE]                VARCHAR (6)      NULL,
    [TERM_DATE]                      DATETIME         NULL,
    [TERM_USER]                      VARCHAR (32)     NULL,
    [BATTERY_NUM]                    VARCHAR (10)     NULL,
    [OPERATOR_CLIENT_ID]             NUMERIC (6)      NULL,
    [ACTIVE_DATE]                    DATETIME         NULL,
    [WELL_STAT_CODE]                 VARCHAR (6)      NULL,
    [WELL_SPUD_DATE]                 DATETIME         NULL,
    [WELL_RIG_RELEASE_DATE]          DATETIME         NULL,
    [WELL_TOTAL_DEPTH]               NUMERIC (10, 2)  NULL,
    [WELL_SHUT_IN_DATE]              DATETIME         NULL,
    [PRIMARY_PROD_CODE]              VARCHAR (6)      NULL,
    [OVERHEAD_METHOD_CODE]           VARCHAR (10)     NULL,
    [LAST_OVERHEAD_ACCT_PER_DATE]    DATETIME         NULL,
    [PRODUCING_ZONE]                 VARCHAR (20)     NULL,
    [PROVINCE]                       VARCHAR (2)      NULL,
    [OVERHEAD_RECOVERY_CC_NUM]       VARCHAR (10)     NULL,
    [SURVEY_SYSTEM_CODE]             VARCHAR (6)      NULL,
    [LOCATION_ELEMENT_1]             VARCHAR (7)      NULL,
    [LOCATION_ELEMENT_2]             VARCHAR (7)      NULL,
    [LOCATION_ELEMENT_3]             VARCHAR (7)      NULL,
    [LOCATION_ELEMENT_4]             VARCHAR (7)      NULL,
    [LOCATION_ELEMENT_5]             VARCHAR (7)      NULL,
    [LOCATION_ELEMENT_6]             VARCHAR (7)      NULL,
    [LOCATION_ELEMENT_7]             VARCHAR (7)      NULL,
    [LOCATION_ELEMENT_8]             VARCHAR (7)      NULL,
    [MUNICIPALITY_CODE]              VARCHAR (8)      NULL,
    [CAPITAL_OR_DRY_HOLE_EXP_CODE]   VARCHAR (1)      NULL,
    [JIBE_CHECK_AMT]                 NUMERIC (14, 2)  NULL,
    [JIBE_CHECK_VARIANCE_PCT]        NUMERIC (14, 10) NULL,
    [ALLOW_OTHER_ORGS_CODE]          VARCHAR (1)      NULL,
    [CONTRACT_OPERATOR_CLIENT_ID]    NUMERIC (6)      NULL,
    [DEFAULT_GL_SUB_CODE]            VARCHAR (6)      NULL,
    [LAST_EMP_BENEFIT_ACCT_PER_DATE] DATETIME         NULL,
    [LAST_EMP_BENEFIT_ADJ_DATE]      DATETIME         NULL,
    [CC_GROUP_CODE]                  VARCHAR (6)      NULL,
    [BILLING_CODE]                   VARCHAR (1)      NULL,
    [OPERATING_CENTRE_CODE]          VARCHAR (10)     NULL,
    [CC_UDF_1_CODE]                  VARCHAR (30)     NULL,
    [CC_UDF_2_CODE]                  VARCHAR (30)     NULL,
    [CC_UDF_3_CODE]                  VARCHAR (30)     NULL,
    [CC_UDF_4_CODE]                  VARCHAR (30)     NULL,
    [CC_UDF_5_CODE]                  VARCHAR (30)     NULL,
    [CC_UDF_6_CODE]                  VARCHAR (30)     NULL,
    [CC_UDF_7_CODE]                  VARCHAR (30)     NULL,
    [CC_UDF_8_CODE]                  VARCHAR (30)     NULL,
    [CC_UDF_9_CODE]                  VARCHAR (30)     NULL,
    [CC_UDF_10_CODE]                 VARCHAR (30)     NULL,
    [CC_UDF_11_CODE]                 VARCHAR (30)     NULL,
    [CC_UDF_12_CODE]                 VARCHAR (30)     NULL,
    [CC_UDF_13_CODE]                 VARCHAR (30)     NULL,
    [CC_UDF_14_CODE]                 VARCHAR (30)     NULL,
    [CC_UDF_15_CODE]                 VARCHAR (30)     NULL,
    [CC_UDF_16_CODE]                 VARCHAR (30)     NULL,
    [CC_UDF_17_CODE]                 VARCHAR (30)     NULL,
    [CC_UDF_18_CODE]                 VARCHAR (30)     NULL,
    [CC_UDF_19_CODE]                 VARCHAR (30)     NULL,
    [CC_UDF_20_CODE]                 VARCHAR (30)     NULL,
    [WELL_STAT_LAST_UPDATE_DATE]     DATETIME         NULL,
    [WELL_STAT_LAST_UPDATE_USER]     VARCHAR (30)     NULL,
    [COUNTRY_CODE]                   VARCHAR (2)      NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

