CREATE TABLE [stage].[t_qbyte_account_groups] (
    [CREATE_DATE]            DATETIME      NULL,
    [CREATE_USER]            VARCHAR (30)  NULL,
    [LAST_UPDATE_DATE]       DATETIME      NULL,
    [LAST_UPDATE_USER]       VARCHAR (30)  NULL,
    [ACCT_GROUP_TYPE_CODE]   VARCHAR (6)   NULL,
    [ACCT_GROUP_CODE]        VARCHAR (6)   NULL,
    [DISPLAY_SEQ_NUM]        NUMERIC (4)   NULL,
    [ACCT_GROUP_DESC]        VARCHAR (240) NULL,
    [ROLLUP_ACCT_GROUP_FLAG] VARCHAR (1)   NULL,
    [ACCT_GROUP_DATE]        DATETIME      NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

