CREATE TABLE [stage].[t_siteview_svt_svjobafe] (
    [idsite]            VARCHAR (32)   NOT NULL,
    [idrecparent]       VARCHAR (32)   NULL,
    [idrec]             VARCHAR (32)   NOT NULL,
    [projectname]       VARCHAR (50)   NULL,
    [projectrefnumber]  VARCHAR (100)  NULL,
    [idrecloc]          VARCHAR (32)   NULL,
    [idrecloctk]        VARCHAR (26)   NULL,
    [refno]             VARCHAR (255)  NULL,
    [costcenternum]     VARCHAR (100)  NULL,
    [typ]               VARCHAR (50)   NULL,
    [wi]                FLOAT (53)     NULL,
    [dttmafe]           DATETIME       NULL,
    [idrecwelljob]      VARCHAR (32)   NULL,
    [idrecwelljobtk]    VARCHAR (26)   NULL,
    [approvedby]        VARCHAR (50)   NULL,
    [dttmapproved]      DATETIME       NULL,
    [status]            VARCHAR (50)   NULL,
    [dttmexpired]       DATETIME       NULL,
    [allocation]        FLOAT (53)     NULL,
    [afenumbersupp]     VARCHAR (255)  NULL,
    [com]               VARCHAR (2000) NULL,
    [usertxt1]          VARCHAR (50)   NULL,
    [usertxt2]          VARCHAR (50)   NULL,
    [userdttm1]         DATETIME       NULL,
    [syslockmeui]       SMALLINT       NULL,
    [syslockchildrenui] SMALLINT       NULL,
    [syslockme]         SMALLINT       NULL,
    [syslockchildren]   SMALLINT       NULL,
    [syslockdate]       DATETIME       NULL,
    [sysmoddate]        DATETIME       NULL,
    [sysmoduser]        VARCHAR (50)   NULL,
    [syscreatedate]     DATETIME       NULL,
    [syscreateuser]     VARCHAR (50)   NULL,
    [systag]            VARCHAR (255)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

