CREATE TABLE [stage].[t_siteview_svt_svjobreport] (
    [idsite]            VARCHAR (32)   NOT NULL,
    [idrecparent]       VARCHAR (32)   NULL,
    [idrec]             VARCHAR (32)   NOT NULL,
    [dttmstart]         DATETIME       NULL,
    [dttmend]           DATETIME       NULL,
    [condroad]          VARCHAR (50)   NULL,
    [condlease]         VARCHAR (50)   NULL,
    [condweather]       VARCHAR (50)   NULL,
    [condwind]          VARCHAR (50)   NULL,
    [condwave]          VARCHAR (50)   NULL,
    [temphigh]          FLOAT (53)     NULL,
    [templow]           FLOAT (53)     NULL,
    [groundcond]        VARCHAR (50)   NULL,
    [idreccontact]      VARCHAR (32)   NULL,
    [idreccontacttk]    VARCHAR (26)   NULL,
    [activitystatus]    VARCHAR (50)   NULL,
    [summary]           VARCHAR (2000) NULL,
    [plannxtactivity]   VARCHAR (2000) NULL,
    [usertxt1]          VARCHAR (50)   NULL,
    [usernum1]          FLOAT (53)     NULL,
    [userboolean1]      SMALLINT       NULL,
    [syslockmeui]       SMALLINT       NULL,
    [syslockchildrenui] SMALLINT       NULL,
    [syslockme]         SMALLINT       NULL,
    [syslockchildren]   SMALLINT       NULL,
    [syslockdate]       DATETIME       NULL,
    [sysmoddate]        DATETIME       NULL,
    [sysmoduser]        VARCHAR (50)   NULL,
    [syscreatedate]     DATETIME       NULL,
    [syscreateuser]     VARCHAR (50)   NULL,
    [systag]            VARCHAR (255)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

