CREATE TABLE [stage].[t_siteview_svt_svjob] (
    [idsite]               VARCHAR (32)   NULL,
    [idrec]                VARCHAR (32)   NULL,
    [typ1]                 VARCHAR (50)   NULL,
    [typ2]                 VARCHAR (50)   NULL,
    [status1]              VARCHAR (50)   NULL,
    [status2]              VARCHAR (50)   NULL,
    [dttmstart]            DATETIME       NULL,
    [dttmend]              DATETIME       NULL,
    [dttmplanend]          DATETIME       NULL,
    [dttmplanstart]        DATETIME       NULL,
    [jobrefno]             VARCHAR (50)   NULL,
    [objective]            VARCHAR (2000) NULL,
    [contact1]             VARCHAR (50)   NULL,
    [contact2]             VARCHAR (50)   NULL,
    [userdttm1]            DATETIME       NULL,
    [userdttm2]            DATETIME       NULL,
    [summary]              VARCHAR (2000) NULL,
    [svestactive]          INT            NULL,
    [desest1]              VARCHAR (50)   NULL,
    [daysest1]             FLOAT (53)     NULL,
    [desest2]              VARCHAR (50)   NULL,
    [daysest2]             FLOAT (53)     NULL,
    [desest3]              VARCHAR (50)   NULL,
    [daysest3]             FLOAT (53)     NULL,
    [desest4]              VARCHAR (50)   NULL,
    [daysest4]             FLOAT (53)     NULL,
    [usertxt1]             VARCHAR (50)   NULL,
    [usertxt3]             VARCHAR (50)   NULL,
    [usertxt2]             VARCHAR (50)   NULL,
    [usertxt4]             VARCHAR (50)   NULL,
    [usertxt5]             VARCHAR (50)   NULL,
    [usernum1]             FLOAT (53)     NULL,
    [usernum2]             FLOAT (53)     NULL,
    [userboolean1]         SMALLINT       NULL,
    [userboolean2]         SMALLINT       NULL,
    [currencycode]         VARCHAR (10)   NULL,
    [chartofaccounts]      VARCHAR (50)   NULL,
    [currencyexchangerate] FLOAT (53)     NULL,
    [mitigationplan]       VARCHAR (100)  NULL,
    [projectname]          VARCHAR (100)  NULL,
    [syslockmeui]          SMALLINT       NULL,
    [syslockchildrenui]    SMALLINT       NULL,
    [syslockme]            SMALLINT       NULL,
    [syslockchildren]      SMALLINT       NULL,
    [syslockdate]          DATETIME       NULL,
    [sysmoddate]           DATETIME       NULL,
    [sysmoduser]           VARCHAR (50)   NULL,
    [syscreatedate]        DATETIME       NULL,
    [syscreateuser]        VARCHAR (50)   NULL,
    [systag]               VARCHAR (255)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

