CREATE TABLE [stage].[t_stg_avocet_mv_fv_site] (
    [SITE_ID]                      VARCHAR (23)    NOT NULL,
    [DISTRICT_ID]                  VARCHAR (23)    NULL,
    [PROVINCE_ID]                  VARCHAR (23)    NULL,
    [COUNTRY_ID]                   VARCHAR (23)    NULL,
    [FIELD_ID]                     VARCHAR (23)    NULL,
    [CORPORATE_PARENT_ID]          NUMERIC (18, 8) NULL,
    [START_DATE]                   DATETIME        NULL,
    [END_DATE]                     DATETIME        NULL,
    [NAME]                         VARCHAR (120)   NULL,
    [SHORT_NAME]                   VARCHAR (60)    NULL,
    [NOTES]                        VARCHAR (765)   NULL,
    [LOCATION]                     VARCHAR (72)    NULL,
    [SECONDARY_LOCATION]           VARCHAR (72)    NULL,
    [PA_CODE]                      VARCHAR (72)    NULL,
    [SECONDARY_PA_CODE]            VARCHAR (72)    NULL,
    [STATUS]                       NUMERIC (18, 8) NULL,
    [LATITUDE]                     FLOAT (53)      NULL,
    [ELEVATION]                    FLOAT (53)      NULL,
    [TYPE]                         NUMERIC (18, 8) NULL,
    [NON_OPERATED]                 NUMERIC (18, 8) NULL,
    [LONGITUDE]                    FLOAT (53)      NULL,
    [GAS_STREAM_ID]                VARCHAR (23)    NULL,
    [SUBSECTION]                   VARCHAR (90)    NULL,
    [SECTION]                      VARCHAR (90)    NULL,
    [TOWNSHIP]                     VARCHAR (90)    NULL,
    [RANGE]                        VARCHAR (90)    NULL,
    [FORMATTED_SECONDARY_LOCATION] VARCHAR (72)    NULL,
    [FORMATTED_LOCATION]           VARCHAR (72)    NULL,
    [TAG_ID]                       VARCHAR (40)    NULL,
    [OWNER_GUID]                   VARCHAR (38)    NULL,
    [DATAPOINT_1]                  FLOAT (53)      NULL,
    [DATAPOINT_2]                  FLOAT (53)      NULL,
    [DATAPOINT_3]                  FLOAT (53)      NULL,
    [DATAPOINT_4]                  FLOAT (53)      NULL,
    [DATAPOINT_5]                  FLOAT (53)      NULL,
    [DATAPOINT_6]                  VARCHAR (768)   NULL,
    [DATAPOINT_7]                  VARCHAR (768)   NULL,
    [DATAPOINT_8]                  VARCHAR (768)   NULL,
    [DATAPOINT_9]                  VARCHAR (768)   NULL,
    [DATAPOINT_10]                 VARCHAR (768)   NULL,
    [CHANGE_COUNTER]               NUMERIC (18, 8) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

