CREATE TABLE [stage].[t_valnav_dim_hierarchy_history] (
    [ENTITY_GUID]               VARCHAR (50)    NULL,
    [UWI]                       VARCHAR (100)   NULL,
    [FORMATTED_UWI]             VARCHAR (100)   NULL,
    [CC_NUM]                    VARCHAR (50)    NULL,
    [CC_NAME]                   VARCHAR (2000)  NULL,
    [UNIT_CC_NUM]               VARCHAR (100)   NULL,
    [UNIT_CC_NAME]              VARCHAR (2000)  NULL,
    [FACILITY]                  VARCHAR (100)   NULL,
    [FACILITY_NAME]             VARCHAR (2000)  NULL,
    [AREA]                      VARCHAR (100)   NULL,
    [AREA_NAME]                 VARCHAR (2000)  NULL,
    [DISTRICT]                  VARCHAR (100)   NULL,
    [DISTRICT_NAME]             VARCHAR (2000)  NULL,
    [REGION]                    VARCHAR (100)   NULL,
    [REGION_NAME]               VARCHAR (2000)  NULL,
    [ZONE_PLAY]                 VARCHAR (100)   NULL,
    [WELL_DIRECTION]            VARCHAR (100)   NULL,
    [OP_NONOP]                  VARCHAR (100)   NULL,
    [CAPITAL_TYPE]              VARCHAR (100)   NULL,
    [BUDGET_YEAR]               VARCHAR (100)   NULL,
    [BUDGET_QUARTER]            VARCHAR (100)   NULL,
    [DE_RISK]                   VARCHAR (100)   NULL,
    [NRA]                       VARCHAR (100)   NULL,
    [RESERVE_REALIZED_DATE]     VARCHAR (20)    NULL,
    [DRILL_DAYS]                VARCHAR (100)   NULL,
    [CAPITAL_GROUP]             VARCHAR (100)   NULL,
    [DEPTH_GCI]                 NUMERIC (10, 5) NULL,
    [CHANCE_OF_SUCCESS]         NUMERIC (10, 5) NULL,
    [WORKING_INTEREST]          NUMERIC (10, 5) NULL,
    [ROYALTY_INCOME_INTEREST]   NUMERIC (10, 5) NULL,
    [PROVINCE]                  VARCHAR (100)   NULL,
    [PRIMARY_PRODUCT]           VARCHAR (50)    NULL,
    [AREA_DISPLAY]              VARCHAR (2000)  NULL,
    [FACILITY_DISPLAY]          VARCHAR (2000)  NULL,
    [DISTRICT_DISPLAY]          VARCHAR (2000)  NULL,
    [REGION_DISPLAY]            VARCHAR (2000)  NULL,
    [ON_PROD_DATE]              VARCHAR (10)    NULL,
    [CURRENT_RESERVE_PROPERTY]  VARCHAR (100)   NULL,
    [YEAR_END_RESERVE_PROPERTY] VARCHAR (100)   NULL,
    [CGU]                       VARCHAR (100)   NULL,
    [BUDGET_GROUP]              VARCHAR (100)   NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

