CREATE TABLE [stage].[t_valnav_dim_hierarchy_source] (
    [entity_key]                  NVARCHAR (50)    NOT NULL,
    [entity_name]                 NVARCHAR (100)   NOT NULL,
    [cost_centre]                 VARCHAR (50)     NULL,
    [cost_centre_name]            VARCHAR (1000)   NULL,
    [corp]                        VARCHAR (50)     NULL,
    [corp_name]                   VARCHAR (1000)   NULL,
    [region]                      VARCHAR (50)     NULL,
    [region_name]                 VARCHAR (1000)   NULL,
    [region_code]                 VARCHAR (100)    NULL,
    [district]                    VARCHAR (50)     NULL,
    [district_name]               VARCHAR (1000)   NULL,
    [district_code]               VARCHAR (100)    NULL,
    [area]                        VARCHAR (50)     NULL,
    [area_name]                   VARCHAR (1000)   NULL,
    [area_code]                   VARCHAR (100)    NULL,
    [facility]                    VARCHAR (50)     NULL,
    [facility_name]               VARCHAR (1000)   NULL,
    [facility_code]               VARCHAR (100)    NULL,
    [cc_type]                     VARCHAR (50)     NULL,
    [cc_type_code]                VARCHAR (50)     NULL,
    [budget_group]                VARCHAR (200)    NULL,
    [budget_year]                 VARCHAR (100)    NULL,
    [valnav_budget_year]          VARCHAR (100)    NULL,
    [op_nonop]                    VARCHAR (10)     NULL,
    [origin]                      VARCHAR (100)    NULL,
    [province]                    VARCHAR (50)     NULL,
    [create_date]                 VARCHAR (50)     NULL,
    [spud_date]                   VARCHAR (50)     NULL,
    [rig_release_date]            VARCHAR (50)     NULL,
    [on_production_date]          VARCHAR (50)     NULL,
    [acquired_from]               VARCHAR (100)    NULL,
    [current_reserves_property]   VARCHAR (200)    NULL,
    [disposition_package]         VARCHAR (200)    NULL,
    [disposition_type]            VARCHAR (200)    NULL,
    [disposition_area]            VARCHAR (200)    NULL,
    [disposition_facility]        VARCHAR (200)    NULL,
    [disposed_flag]               VARCHAR (20)     NULL,
    [focus_area_flag]             VARCHAR (10)     NULL,
    [primary_product]             NVARCHAR (50)    NULL,
    [cgu]                         VARCHAR (100)    NULL,
    [working_interest]            FLOAT (53)       NULL,
    [year_end_reserves_property]  VARCHAR (200)    NULL,
    [unit_cc_num]                 VARCHAR (50)     NULL,
    [unit_cc_name]                VARCHAR (1000)   NULL,
    [survey_system_code]          VARCHAR (50)     NULL,
    [uwi]                         NVARCHAR (100)   NOT NULL,
    [uwi_desc]                    VARCHAR (500)    NULL,
    [meridian]                    VARCHAR (50)     NULL,
    [range]                       VARCHAR (50)     NULL,
    [township]                    VARCHAR (50)     NULL,
    [section]                     VARCHAR (50)     NULL,
    [tax_pools]                   VARCHAR (100)    NULL,
    [strat_unit_id]               VARCHAR (50)     NULL,
    [crstatus_desc]               VARCHAR (100)    NULL,
    [license_no]                  VARCHAR (50)     NULL,
    [surf_location]               VARCHAR (50)     NULL,
    [tvd_depth]                   NUMERIC (10, 2)  NULL,
    [total_depth]                 NUMERIC (10, 2)  NULL,
    [zone_desc]                   VARCHAR (100)    NULL,
    [deviation_flag]              VARCHAR (100)    NULL,
    [formatted_uwi]               NVARCHAR (100)   NULL,
    [bottom_hole_latitude]        NUMERIC (12, 7)  NULL,
    [bottom_hole_longitude]       NUMERIC (12, 7)  NULL,
    [surface_latitude]            NUMERIC (12, 7)  NULL,
    [surface_longitude]           NUMERIC (12, 7)  NULL,
    [gas_shrinkage_factor]        NUMERIC (12, 2)  NULL,
    [ngl_yield_factor]            NUMERIC (12, 2)  NULL,
    [pvunit_completion_name]      VARCHAR (100)    NULL,
    [pvunit_name]                 VARCHAR (100)    NULL,
    [pvunit_short_name]           VARCHAR (100)    NULL,
    [entity_source]               VARCHAR (6)      NOT NULL,
    [is_cc_dim]                   INT              NOT NULL,
    [cc_term_date]                VARCHAR (50)     NULL,
    [chance_of_success]           FLOAT (53)       NULL,
    [budget_quarter]              VARCHAR (100)    NULL,
    [capital_group]               VARCHAR (100)    NULL,
    [capital_type]                VARCHAR (100)    NULL,
    [de_risk]                     VARCHAR (100)    NULL,
    [depth_gci]                   FLOAT (53)       NULL,
    [drill_days]                  VARCHAR (100)    NULL,
    [nra]                         VARCHAR (100)    NULL,
    [reserve_realized_date]       VARCHAR (50)     NULL,
    [royalty_income_interest]     FLOAT (53)       NULL,
    [well_direction]              VARCHAR (100)    NULL,
    [zone_play]                   VARCHAR (100)    NULL,
    [is_valnav]                   INT              NOT NULL,
    [source_db]                   VARCHAR (12)     NOT NULL,
    [source_db_sort_key]          INT              NOT NULL,
    [budget_year_group]           VARCHAR (50)     NULL,
    [origin_group]                VARCHAR (100)    NULL,
    [cc_num_working_interest_pct] NUMERIC (38, 11) NULL,
    [lateral_length]              FLOAT (53)       NULL,
    [segment_start_date]          VARCHAR (10)     NULL,
    [last_production_date]        VARCHAR (50)     NULL,
    [completion_type]             VARCHAR (50)     NULL,
    [total_proppant_placed]       FLOAT (53)       NULL,
    [c_star]                      FLOAT (53)       NULL,
    [Production_Category]         VARCHAR (100)    NULL,
    [Incentive_Type]              VARCHAR (100)    NULL,
    [Meter_Station]               VARCHAR (100)    NULL,
    [type_curve_kpi]              VARCHAR (100)    NULL,
    [royalty_type]                VARCHAR (100)    NULL,
    [first_prod_month]            VARCHAR (50)     NULL,
    [group1]                      VARCHAR (100)    NULL,
    [group2]                      VARCHAR (100)    NULL,
    [group3]                      VARCHAR (100)    NULL,
    [group4]                      VARCHAR (100)    NULL,
    [group5]                      VARCHAR (100)    NULL,
    [group6]                      VARCHAR (100)    NULL,
    [group7]                      VARCHAR (100)    NULL,
    [group8]                      VARCHAR (100)    NULL,
    [group9]                      VARCHAR (100)    NULL,
    [group10]                     VARCHAR (100)    NULL,
    [completion_month]            VARCHAR (50)     NULL,
    [plant]                       VARCHAR (100)    NULL,
    [keyera_inlet]                VARCHAR (100)    NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

