CREATE TABLE [stage].[t_wellview_wvt_wvjobreport] (
    [idwell]                VARCHAR (32)   NOT NULL,
    [idrecparent]           VARCHAR (32)   NULL,
    [idrec]                 VARCHAR (32)   NOT NULL,
    [condhole]              VARCHAR (50)   NULL,
    [condlease]             VARCHAR (50)   NULL,
    [condroad]              VARCHAR (50)   NULL,
    [condtemp]              FLOAT (53)     NULL,
    [condwave]              VARCHAR (50)   NULL,
    [condweather]           VARCHAR (50)   NULL,
    [condwind]              VARCHAR (50)   NULL,
    [depthtvdendprojmethod] VARCHAR (20)   NULL,
    [dttmend]               DATETIME       NULL,
    [dttmstart]             DATETIME       NULL,
    [durationsinceltinc]    FLOAT (53)     NULL,
    [durationsincerptinc]   FLOAT (53)     NULL,
    [gasbackgroundavg]      FLOAT (53)     NULL,
    [gasbackgroundmax]      FLOAT (53)     NULL,
    [gasconnectionavg]      FLOAT (53)     NULL,
    [gasconnectionmax]      FLOAT (53)     NULL,
    [gasdrillavg]           FLOAT (53)     NULL,
    [gasdrillmax]           FLOAT (53)     NULL,
    [gastripavg]            FLOAT (53)     NULL,
    [gastripmax]            FLOAT (53)     NULL,
    [h2smax]                FLOAT (53)     NULL,
    [idrecnextcas]          VARCHAR (32)   NULL,
    [idrecnextcastk]        VARCHAR (26)   NULL,
    [plannextrptops]        VARCHAR (2000) NULL,
    [remarks]               VARCHAR (2000) NULL,
    [rigtime]               FLOAT (53)     NULL,
    [rpttmactops]           VARCHAR (100)  NULL,
    [statusend]             VARCHAR (50)   NULL,
    [summaryops]            VARCHAR (2000) NULL,
    [userboolean1]          SMALLINT       NULL,
    [userboolean2]          SMALLINT       NULL,
    [usernum1]              FLOAT (53)     NULL,
    [usernum2]              FLOAT (53)     NULL,
    [usernum3]              FLOAT (53)     NULL,
    [usernum4]              FLOAT (53)     NULL,
    [usernum5]              FLOAT (53)     NULL,
    [usertxt1]              VARCHAR (50)   NULL,
    [usertxt2]              VARCHAR (50)   NULL,
    [usertxt3]              VARCHAR (50)   NULL,
    [usertxt4]              VARCHAR (50)   NULL,
    [usertxt5]              VARCHAR (50)   NULL,
    [syslockmeui]           SMALLINT       NULL,
    [syslockchildrenui]     SMALLINT       NULL,
    [syslockme]             SMALLINT       NULL,
    [syslockchildren]       SMALLINT       NULL,
    [syslockdate]           DATETIME       NULL,
    [sysmoddate]            DATETIME       NULL,
    [sysmoduser]            VARCHAR (50)   NULL,
    [syscreatedate]         DATETIME       NULL,
    [syscreateuser]         VARCHAR (50)   NULL,
    [systag]                VARCHAR (255)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

