CREATE TABLE [stage].[t_wellview_wvt_wvjobdrillstring] (
    [idwell]             VARCHAR (32)   NOT NULL,
    [idrecparent]        VARCHAR (32)   NULL,
    [idrec]              VARCHAR (32)   NOT NULL,
    [bitno]              VARCHAR (10)   NULL,
    [bittfa]             FLOAT (53)     NULL,
    [com]                VARCHAR (2000) NULL,
    [des]                VARCHAR (100)  NULL,
    [dircontrolmethod]   VARCHAR (50)   NULL,
    [dttmoutofhole]      DATETIME       NULL,
    [dttmpickup]         DATETIME       NULL,
    [idrecbit]           VARCHAR (32)   NULL,
    [idrecbittk]         VARCHAR (26)   NULL,
    [proposed]           SMALLINT       NULL,
    [stringno]           INT            NULL,
    [stringobjective]    VARCHAR (100)  NULL,
    [stringresult]       VARCHAR (100)  NULL,
    [stringresultdetail] VARCHAR (50)   NULL,
    [stringresultnote]   VARCHAR (255)  NULL,
    [travelequipwt]      FLOAT (53)     NULL,
    [triphookloadmax]    FLOAT (53)     NULL,
    [tripnote]           VARCHAR (255)  NULL,
    [tripoverpullmax]    FLOAT (53)     NULL,
    [triprateinavg]      FLOAT (53)     NULL,
    [triprateinmax]      FLOAT (53)     NULL,
    [triprateoutavg]     FLOAT (53)     NULL,
    [triprateoutmax]     FLOAT (53)     NULL,
    [wearbearing]        VARCHAR (10)   NULL,
    [weardull]           VARCHAR (10)   NULL,
    [weargauge]          VARCHAR (10)   NULL,
    [wearinner]          INT            NULL,
    [wearloc]            VARCHAR (10)   NULL,
    [wearother]          VARCHAR (10)   NULL,
    [wearouter]          INT            NULL,
    [wearpulled]         VARCHAR (10)   NULL,
    [syslockmeui]        SMALLINT       NULL,
    [syslockchildrenui]  SMALLINT       NULL,
    [syslockme]          SMALLINT       NULL,
    [syslockchildren]    SMALLINT       NULL,
    [syslockdate]        DATETIME       NULL,
    [sysmoddate]         DATETIME       NULL,
    [sysmoduser]         VARCHAR (50)   NULL,
    [syscreatedate]      DATETIME       NULL,
    [syscreateuser]      VARCHAR (50)   NULL,
    [systag]             VARCHAR (255)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

