CREATE TABLE [stage].[t_wellview_wvt_wvcas] (
    [idwell]                  VARCHAR (32)   NOT NULL,
    [idrec]                   VARCHAR (32)   NOT NULL,
    [centralizers]            VARCHAR (100)  NULL,
    [centralizersstandoffavg] FLOAT (53)     NULL,
    [centralizersstandoffmin] FLOAT (53)     NULL,
    [com]                     VARCHAR (2000) NULL,
    [contractor]              VARCHAR (50)   NULL,
    [depthbtm]                FLOAT (53)     NULL,
    [depthcutpull]            FLOAT (53)     NULL,
    [des]                     VARCHAR (100)  NULL,
    [dttmcutpull]             DATETIME       NULL,
    [dttmonbottom]            DATETIME       NULL,
    [dttmoutofhole]           DATETIME       NULL,
    [dttmpickup]              DATETIME       NULL,
    [dttmpull]                DATETIME       NULL,
    [dttmrun]                 DATETIME       NULL,
    [idrecjobpull]            VARCHAR (32)   NULL,
    [idrecjobpulltk]          VARCHAR (26)   NULL,
    [idrecjobrun]             VARCHAR (32)   NULL,
    [idrecjobruntk]           VARCHAR (26)   NULL,
    [idrecwellbore]           VARCHAR (32)   NULL,
    [idrecwellboretk]         VARCHAR (26)   NULL,
    [latposition]             VARCHAR (20)   NULL,
    [notecutpull]             VARCHAR (255)  NULL,
    [operatingpresslimit]     FLOAT (53)     NULL,
    [proposedcutpull]         SMALLINT       NULL,
    [proposedpull]            SMALLINT       NULL,
    [proposedrun]             SMALLINT       NULL,
    [pullreason]              VARCHAR (100)  NULL,
    [pullreasondetail]        VARCHAR (100)  NULL,
    [reasoncutpull]           VARCHAR (100)  NULL,
    [scratchers]              VARCHAR (100)  NULL,
    [stringwtdown]            FLOAT (53)     NULL,
    [stringwtup]              FLOAT (53)     NULL,
    [tension]                 FLOAT (53)     NULL,
    [travelequipwt]           FLOAT (53)     NULL,
    [usertxt1]                VARCHAR (50)   NULL,
    [usertxt2]                VARCHAR (50)   NULL,
    [usertxt3]                VARCHAR (50)   NULL,
    [volumeshoetrack]         FLOAT (53)     NULL,
    [syslockmeui]             SMALLINT       NULL,
    [syslockchildrenui]       SMALLINT       NULL,
    [syslockme]               SMALLINT       NULL,
    [syslockchildren]         SMALLINT       NULL,
    [syslockdate]             DATETIME       NULL,
    [sysmoddate]              DATETIME       NULL,
    [sysmoduser]              VARCHAR (50)   NULL,
    [syscreatedate]           DATETIME       NULL,
    [syscreateuser]           VARCHAR (50)   NULL,
    [systag]                  VARCHAR (255)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

