CREATE TABLE [stage].[t_wellview_wvt_wvwellheader] (
    [idwell]               VARCHAR (32)   NOT NULL,
    [agent]                VARCHAR (50)   NULL,
    [area]                 VARCHAR (50)   NULL,
    [basin]                VARCHAR (100)  NULL,
    [basincode]            VARCHAR (50)   NULL,
    [com]                  VARCHAR (2000) NULL,
    [country]              VARCHAR (50)   NULL,
    [county]               VARCHAR (50)   NULL,
    [currentwellstatus1]   VARCHAR (50)   NULL,
    [currentwellstatus2]   VARCHAR (50)   NULL,
    [directionstowell]     VARCHAR (2000) NULL,
    [district]             VARCHAR (100)  NULL,
    [division]             VARCHAR (100)  NULL,
    [divisioncode]         VARCHAR (100)  NULL,
    [dttmabandon]          DATETIME       NULL,
    [dttmfirstprod]        DATETIME       NULL,
    [dttmrr]               DATETIME       NULL,
    [dttmspud]             DATETIME       NULL,
    [dttmwellclass]        DATETIME       NULL,
    [dttmwelllic]          DATETIME       NULL,
    [elvcasflange]         FLOAT (53)     NULL,
    [elvground]            FLOAT (53)     NULL,
    [elvlat]               FLOAT (53)     NULL,
    [elvmudline]           FLOAT (53)     NULL,
    [elvorigkb]            FLOAT (53)     NULL,
    [elvtubhead]           FLOAT (53)     NULL,
    [environmentsensitive] SMALLINT       NULL,
    [ewdist]               FLOAT (53)     NULL,
    [ewflag]               VARCHAR (5)    NULL,
    [fieldcode]            VARCHAR (50)   NULL,
    [fieldname]            VARCHAR (50)   NULL,
    [fieldoffice]          VARCHAR (50)   NULL,
    [fieldofficecode]      VARCHAR (50)   NULL,
    [govauthority]         VARCHAR (50)   NULL,
    [hih2s]                SMALLINT       NULL,
    [hisitp]               SMALLINT       NULL,
    [idrecelvhistory]      VARCHAR (32)   NULL,
    [idrecelvhistorytk]    VARCHAR (26)   NULL,
    [latitude]             FLOAT (53)     NULL,
    [latlongdatum]         VARCHAR (50)   NULL,
    [latlongsource]        VARCHAR (50)   NULL,
    [lease]                VARCHAR (50)   NULL,
    [leasecode]            VARCHAR (50)   NULL,
    [legalsurveyloc]       VARCHAR (100)  NULL,
    [legalsurveysubtyp]    VARCHAR (100)  NULL,
    [legalsurveytyp]       VARCHAR (100)  NULL,
    [localtimezone]        FLOAT (53)     NULL,
    [locationnote]         VARCHAR (255)  NULL,
    [locationref]          VARCHAR (50)   NULL,
    [locationsensitive]    SMALLINT       NULL,
    [locationtyp]          VARCHAR (100)  NULL,
    [longitude]            FLOAT (53)     NULL,
    [nsdist]               FLOAT (53)     NULL,
    [nsflag]               VARCHAR (5)    NULL,
    [operated]             SMALLINT       NULL,
    [operator]             VARCHAR (50)   NULL,
    [operatorcode]         VARCHAR (50)   NULL,
    [padcode]              VARCHAR (50)   NULL,
    [padname]              VARCHAR (50)   NULL,
    [platform]             VARCHAR (50)   NULL,
    [primaryfluiddes]      VARCHAR (100)  NULL,
    [problemflag]          SMALLINT       NULL,
    [riskclass]            VARCHAR (50)   NULL,
    [slot]                 VARCHAR (50)   NULL,
    [stateprov]            VARCHAR (50)   NULL,
    [surfacerights]        VARCHAR (50)   NULL,
    [towndist]             FLOAT (53)     NULL,
    [townflag]             VARCHAR (5)    NULL,
    [townname]             VARCHAR (50)   NULL,
    [townstateprov]        VARCHAR (50)   NULL,
    [userboolean1]         SMALLINT       NULL,
    [userboolean2]         SMALLINT       NULL,
    [userboolean3]         SMALLINT       NULL,
    [userboolean4]         SMALLINT       NULL,
    [userboolean5]         SMALLINT       NULL,
    [userdttm1]            DATETIME       NULL,
    [userdttm2]            DATETIME       NULL,
    [userdttm3]            DATETIME       NULL,
    [userdttm4]            DATETIME       NULL,
    [userdttm5]            DATETIME       NULL,
    [usernum1]             FLOAT (53)     NULL,
    [usernum2]             FLOAT (53)     NULL,
    [usernum3]             FLOAT (53)     NULL,
    [usernum4]             FLOAT (53)     NULL,
    [usernum5]             FLOAT (53)     NULL,
    [usernum6]             FLOAT (53)     NULL,
    [usertxt1]             VARCHAR (100)  NULL,
    [usertxt10]            VARCHAR (100)  NULL,
    [usertxt2]             VARCHAR (100)  NULL,
    [usertxt3]             VARCHAR (100)  NULL,
    [usertxt4]             VARCHAR (100)  NULL,
    [usertxt5]             VARCHAR (100)  NULL,
    [usertxt6]             VARCHAR (100)  NULL,
    [usertxt7]             VARCHAR (100)  NULL,
    [usertxt8]             VARCHAR (100)  NULL,
    [usertxt9]             VARCHAR (100)  NULL,
    [utmgridzone]          INT            NULL,
    [utmsource]            VARCHAR (50)   NULL,
    [utmx]                 FLOAT (53)     NULL,
    [utmy]                 FLOAT (53)     NULL,
    [waterdepth]           FLOAT (53)     NULL,
    [waterdepthref]        VARCHAR (50)   NULL,
    [wellclass]            VARCHAR (50)   NULL,
    [wellconfig]           VARCHAR (50)   NULL,
    [wellida]              VARCHAR (50)   NULL,
    [wellidb]              VARCHAR (50)   NULL,
    [wellidc]              VARCHAR (50)   NULL,
    [wellidd]              VARCHAR (50)   NULL,
    [wellide]              VARCHAR (50)   NULL,
    [welllicensee]         VARCHAR (50)   NULL,
    [welllicenseno]        VARCHAR (50)   NULL,
    [wellname]             VARCHAR (100)  NULL,
    [welltyp1]             VARCHAR (100)  NULL,
    [welltyp2]             VARCHAR (100)  NULL,
    [syslockmeui]          SMALLINT       NULL,
    [syslockchildrenui]    SMALLINT       NULL,
    [syslockme]            SMALLINT       NULL,
    [syslockchildren]      SMALLINT       NULL,
    [syslockdate]          DATETIME       NULL,
    [sysmoddate]           DATETIME       NULL,
    [sysmoduser]           VARCHAR (50)   NULL,
    [syscreatedate]        DATETIME       NULL,
    [syscreateuser]        VARCHAR (50)   NULL,
    [systag]               VARCHAR (255)  NULL,
    [sysmoddatedb]         DATETIME       NULL,
    [sysmoduserdb]         VARCHAR (50)   NULL,
    [syssecuritytyp]       VARCHAR (50)   NULL,
    [syslockdatemaster]    DATETIME       NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

