CREATE TABLE [stage].[t_wellview_wvt_wvjobrig] (
    [idwell]                      VARCHAR (32)   NOT NULL,
    [idrecparent]                 VARCHAR (32)   NULL,
    [idrec]                       VARCHAR (32)   NOT NULL,
    [anchorlinetyp]               VARCHAR (100)  NULL,
    [anchormaxtension]            FLOAT (53)     NULL,
    [anchorno]                    INT            NULL,
    [anchortyp]                   VARCHAR (100)  NULL,
    [com]                         VARCHAR (2000) NULL,
    [contractor]                  VARCHAR (50)   NULL,
    [contractorparent]            VARCHAR (50)   NULL,
    [contracttyp]                 VARCHAR (100)  NULL,
    [depthmax]                    FLOAT (53)     NULL,
    [derricktyp]                  VARCHAR (100)  NULL,
    [drawworkmake]                VARCHAR (100)  NULL,
    [drawworkmodel]               VARCHAR (100)  NULL,
    [drawworktyp]                 VARCHAR (100)  NULL,
    [dttmend]                     DATETIME       NULL,
    [dttmstart]                   DATETIME       NULL,
    [heightmastclearance]         FLOAT (53)     NULL,
    [heightsubclear]              FLOAT (53)     NULL,
    [hookloadmax]                 FLOAT (53)     NULL,
    [idrecjobcontactcontractor]   VARCHAR (32)   NULL,
    [idrecjobcontactcontractortk] VARCHAR (26)   NULL,
    [inventoryno]                 VARCHAR (10)   NULL,
    [lengthchokeline]             FLOAT (53)     NULL,
    [lengthkillline]              FLOAT (53)     NULL,
    [maxvariableload]             FLOAT (53)     NULL,
    [postyp]                      VARCHAR (100)  NULL,
    [proposed]                    SMALLINT       NULL,
    [power]                       FLOAT (53)     NULL,
    [powertyp]                    VARCHAR (100)  NULL,
    [purpose]                     VARCHAR (100)  NULL,
    [refheight]                   FLOAT (53)     NULL,
    [rigno]                       VARCHAR (50)   NULL,
    [rigrateref]                  FLOAT (53)     NULL,
    [rotarysystem]                VARCHAR (50)   NULL,
    [slipjtextmax]                FLOAT (53)     NULL,
    [szidchokeline]               FLOAT (53)     NULL,
    [szidkillline]                FLOAT (53)     NULL,
    [setbackcapacity]             FLOAT (53)     NULL,
    [torquemax]                   FLOAT (53)     NULL,
    [transportloads]              INT            NULL,
    [typ1]                        VARCHAR (100)  NULL,
    [typ2]                        VARCHAR (100)  NULL,
    [volsurfline]                 FLOAT (53)     NULL,
    [waterdepthmax]               FLOAT (53)     NULL,
    [weightblock]                 FLOAT (53)     NULL,
    [syslockmeui]                 SMALLINT       NULL,
    [syslockchildrenui]           SMALLINT       NULL,
    [syslockme]                   SMALLINT       NULL,
    [syslockchildren]             SMALLINT       NULL,
    [syslockdate]                 DATETIME       NULL,
    [sysmoddate]                  DATETIME       NULL,
    [sysmoduser]                  VARCHAR (50)   NULL,
    [syscreatedate]               DATETIME       NULL,
    [syscreateuser]               VARCHAR (50)   NULL,
    [systag]                      VARCHAR (255)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

