CREATE TABLE [stage].[t_wellview_wvt_wvjobdrillstringdrillparam] (
    [idwell]             VARCHAR (32)  NOT NULL,
    [idrecparent]        VARCHAR (32)  NULL,
    [idrec]              VARCHAR (32)  NOT NULL,
    [bhaanpres]          FLOAT (53)    NULL,
    [bhtemp]             FLOAT (53)    NULL,
    [depthend]           FLOAT (53)    NULL,
    [depthstart]         FLOAT (53)    NULL,
    [dttmend]            DATETIME      NULL,
    [dttmstart]          DATETIME      NULL,
    [ecdendoverride]     FLOAT (53)    NULL,
    [excludefromnewhole] SMALLINT      NULL,
    [gasinjrate]         FLOAT (53)    NULL,
    [gasreturnrate]      FLOAT (53)    NULL,
    [hookloadoffbottom]  FLOAT (53)    NULL,
    [hookloadpickup]     FLOAT (53)    NULL,
    [hookloadrotating]   FLOAT (53)    NULL,
    [hookloadslackoff]   FLOAT (53)    NULL,
    [idrecwellbore]      VARCHAR (32)  NULL,
    [idrecwellboretk]    VARCHAR (26)  NULL,
    [injtemp]            FLOAT (53)    NULL,
    [liquidinjrate]      FLOAT (53)    NULL,
    [liquidinjrateriser] FLOAT (53)    NULL,
    [liquidreturnrate]   FLOAT (53)    NULL,
    [note]               VARCHAR (255) NULL,
    [refnostand]         VARCHAR (10)  NULL,
    [ropinst]            FLOAT (53)    NULL,
    [rpmmotor]           FLOAT (53)    NULL,
    [rpmstring]          FLOAT (53)    NULL,
    [sppdiff]            FLOAT (53)    NULL,
    [sppdrill]           FLOAT (53)    NULL,
    [surfannpres]        FLOAT (53)    NULL,
    [surfanntemp]        FLOAT (53)    NULL,
    [szodvgstab]         FLOAT (53)    NULL,
    [tfo]                FLOAT (53)    NULL,
    [tforef]             VARCHAR (10)  NULL,
    [tmcirc]             FLOAT (53)    NULL,
    [tmdrill]            FLOAT (53)    NULL,
    [tmother]            FLOAT (53)    NULL,
    [tmtrip]             FLOAT (53)    NULL,
    [torquedrill]        FLOAT (53)    NULL,
    [torqueoffbtm]       FLOAT (53)    NULL,
    [torqueunits]        VARCHAR (10)  NULL,
    [typ1]               VARCHAR (100) NULL,
    [typ2]               VARCHAR (100) NULL,
    [wob]                FLOAT (53)    NULL,
    [syslockmeui]        SMALLINT      NULL,
    [syslockchildrenui]  SMALLINT      NULL,
    [syslockme]          SMALLINT      NULL,
    [syslockchildren]    SMALLINT      NULL,
    [syslockdate]        DATETIME      NULL,
    [sysmoddate]         DATETIME      NULL,
    [sysmoduser]         VARCHAR (50)  NULL,
    [syscreatedate]      DATETIME      NULL,
    [syscreateuser]      VARCHAR (50)  NULL,
    [systag]             VARCHAR (255) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

