CREATE PROC [data_mart].[build_dim_authorization_for_expenditure] @complete_rebuild_flag [varchar](1) AS
BEGIN
  -- SET NOCOUNT ON added to prevent extra result sets from
  -- interfering with SELECT statements.
  SET NOCOUNT ON;

  IF @complete_rebuild_flag IS NULL OR @complete_rebuild_flag = ''
    SET @complete_rebuild_flag = 'N'

  BEGIN TRY

    IF @complete_rebuild_flag = 'Y'
        
      BEGIN

       -- BEGIN TRANSACTION

          TRUNCATE TABLE [data_mart].[t_dim_authorization_for_expenditure];

		  SET IDENTITY_INSERT [data_mart].[t_dim_authorization_for_expenditure] ON;

          INSERT INTO [data_mart].[t_dim_authorization_for_expenditure]
            (
             afe_key,
             afe_num,
             afe_name,
             client_id,
             client_name,
             op_nonop,
             ref_org_id,
             afe_type_code,
             afe_type_description,
             afe_status_code,
             afe_status_description,
             cost_centre,
             cost_centre_name,
             corp_code,
             corp_name,
             region_code,
             region_name,
             district_code,
             district_name,
             area_code,
             area_name,
             facility_code,
             facility_name,
             curr_code,
             ownership_org_id,
             jib_flag,
             cip_transfer_flag,
             use_jibe_edits_flag,
             accrual_flag,
             create_date,
             create_user,
             last_updt_date,
             last_updt_user,
             term_date,
             term_user,
             effective_date,
             proposal_date,
             due_date,
             commitment_date,
             afe_approval_date,
             afe_start_date,
             budget_activity_year,
             extrapolated_budget_year,
             project_approval_status,
             project_execution_status,
             afe_date,
             acct_yr,
             alloc_amt,
             tax_code,
             capital_accrual_method_code,
             managing_org_id,
             net_estimate_pct,
             internal_approver,
             manager_name,
             success_effort_type_code,
             capital_accrual_cc_num,
             equip_component_amt,
             wrhse_component_amt,
             translation_rate,
             original_alloc_amt,
             reporting_alloc_amt,
             allow_other_orgs_code,
             province,
             engineer_assigned,
             geologist_assigned,
             geophysicist_assigned,
             last_updt_status_user,
             last_updt_status_date,
             doi_type_code,
             afe_class_code,
             default_gl_sub_code,
             overhead_start_date,
             overhead_end_date,
             capital_or_dry_hole_exp_code,
             last_accrued_date,
             country_code,
             survey_system_code,
             primary_uwi,
             uwi_alias,
             primary_location,
             sorted_uwi,
             uwi_sort_element_1,
             uwi_sort_element_2,
             uwi_sort_element_3,
             uwi_sort_element_4,
             uwi_sort_element_5,
             uwi_sort_element_6,
             uwi_sort_element_7,
             uwi_sort_element_8,
             uwi_sort_element_9,
             afe_udf_1_code,
             afe_udf_5_code,
             afe_udf_7_code,
             afe_udf_20_code,
             project_justification_comments,
			 budget_activity_year_desc,
			 afe_type_group,
			 afe_type_group_desc,
			 job_start_date,
			 rig_number,
			 rig_name,
			 zone_play,
			 wellview_spud_date, 
			 wellview_rig_release_date, 
			 wellview_total_depth, 
			 wellview_intermediate_casing_depth,
			 wellview_horizontal_depth,
			 AFE_GCA_FCC,
			 cc_list, Number_of_CCs,
			 job_end_date
            )
          SELECT
              '-1',
              '-1',
              'Unspecified AFE Number',
              NULL,
              NULL,
              NULL,
              1,
              'AFE Type Not Applicable',
              'Unspecified AFE Type',
              'AFE Status Not Applicable',
              'Unspecified AFE Status',
              '-1',
              'Unspecified Cost Centre',
              'CORP',
              'Corporate',
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              1,
              'N',
              'N',
              'N',
              'N',
              GETDATE (),
              'ATigley',
              GETDATE (),
              'ATigley',
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              'PRIOR_PERIOD',
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              1,
              100.00,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              'AB',
              NULL,
              NULL,
              NULL,
              'ATigley',
              GETDATE (),
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              'CA',
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
              NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL, null,null, null, null
			             
          INSERT INTO [data_mart].[t_dim_authorization_for_expenditure]
            (
               afe_key,
               afe_num,
               afe_name,
               client_id,
               client_name,
               op_nonop,
               ref_org_id,
               afe_type_code,
               afe_type_description,
               afe_status_code,
               afe_status_description,
               cost_centre,
               cost_centre_name,
               corp_code,
               corp_name,
               region_code,
               region_name,
               district_code,
               district_name,
               area_code,
               area_name,
               facility_code,
               facility_name,
               curr_code,
               ownership_org_id,
               jib_flag,
               cip_transfer_flag,
               use_jibe_edits_flag,
               accrual_flag,
               create_date,
               create_user,
               last_updt_date,
               last_updt_user,
               term_date,
               term_user,
               effective_date,
               proposal_date,
               due_date,
               commitment_date,
               afe_approval_date,
               afe_start_date,
               budget_activity_year,
               extrapolated_budget_year,
               project_approval_status,
               project_execution_status,
               afe_date,
               acct_yr,
               alloc_amt,
               tax_code,
               capital_accrual_method_code,
               managing_org_id,
               net_estimate_pct,
               internal_approver,
               manager_name,
               success_effort_type_code,
               capital_accrual_cc_num,
               equip_component_amt,
               wrhse_component_amt,
               translation_rate,
               original_alloc_amt,
               reporting_alloc_amt,
               allow_other_orgs_code,
               province,
               engineer_assigned,
               geologist_assigned,
               geophysicist_assigned,
               last_updt_status_user,
               last_updt_status_date,
               doi_type_code,
               afe_class_code,
               default_gl_sub_code,
               overhead_start_date,
               overhead_end_date,
               capital_or_dry_hole_exp_code,
               last_accrued_date,
               country_code,
               survey_system_code,
               primary_uwi,
               uwi_alias,
               primary_location,
               sorted_uwi,
               uwi_sort_element_1,
               uwi_sort_element_2,
               uwi_sort_element_3,
               uwi_sort_element_4,
               uwi_sort_element_5,
               uwi_sort_element_6,
               uwi_sort_element_7,
               uwi_sort_element_8,
               uwi_sort_element_9,
               afe_udf_1_code,
               afe_udf_5_code,
               afe_udf_7_code,
               afe_udf_20_code,
               project_justification_comments,
			   budget_activity_year_desc,
			   afe_type_group,
			   afe_type_group_desc,
			   job_start_date,
			   rig_number,
			   rig_name,
			   zone_play,
			   wellview_spud_date, 
			   wellview_rig_release_date, 
			   wellview_total_depth, 
			   wellview_intermediate_casing_depth,
			   wellview_horizontal_depth,
			   AFE_GCA_FCC,
			   cc_list, Number_of_CCs
			   , job_end_date
            )
          SELECT
               '-2',
               '-2',
               'Unrecognized or Unmatched AFE Number',
               NULL,
               NULL,
               NULL,
               1,
               'AFE Type Not Applicable',
               'Unspecified AFE Type',
               'AFE Status Not Applicable',
               'Unspecified AFE Status',
               '-1',
               'Unspecified Cost Centre',
               'CORP',
               'Corporate',
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               1,
               'N',
               'N',
               'N',
               'N',
               GETDATE (),
               'ATigley',
               GETDATE (),
               'ATigley',
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               'PRIOR_PERIOD',
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               1,
               100.00,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               'AB',
               NULL,
               NULL,
               NULL,
               'ATigley',
               GETDATE (),
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               'CA',
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
               NULL,
			   NULL,
			   NULL,
			   NULL,
			   NULL,
			   NULL,
			   NULL,
			   NULL,
			   NULL,
			   NULL,
			   NULL,
			   NULL,
			   NULL,null,null, null, null
			
 	      SET IDENTITY_INSERT [data_mart].[t_dim_authorization_for_expenditure] OFF;
      --  COMMIT TRANSACTION

      END

      --BEGIN TRANSACTION               
     
      -- Merge AFEs from [stage].[dbo].[v_qbyte_authorization_for_expenditure_attributes]
      IF OBJECT_ID('tempdb..#t_dim_entity_MERGE') IS NOT NULL
        DROP TABLE #t_dim_entity_MERGE	 

      CREATE TABLE #t_dim_entity_MERGE WITH (DISTRIBUTION = ROUND_ROBIN)
        AS
          SELECT
		    'NEW' Flag,
            src.[afe_num],
            src.[afe_name],
            src.[client_id],
            src.[client_name],
            src.[op_nonop],
            src.[ref_org_id],
            src.[afe_type_code],
            src.[afe_type_description],
            src.[afe_status_code],
            src.[afe_status_description],
            src.[cost_centre],
            src.[cost_centre_name],
            src.[corp_code],
            src.[corp_name],
            src.[region],
            src.[region_code],
            src.[region_name],
            src.[district],
            src.[district_code],
            src.[district_name],
            src.[area],
            src.[area_code],
            src.[area_name],
            src.[facility],
            src.[facility_code],
            src.[facility_name],
            src.[curr_code],
            src.[ownership_org_id],
            src.[jib_flag],
            src.[cip_transfer_flag],
            src.[use_jibe_edits_flag],
            src.[accrual_flag],
            src.[create_date],
            src.[create_user],
            src.[last_updt_date],
            src.[last_updt_user],
            src.[term_date],
            src.[term_user],
            src.[effective_date],
            src.[proposal_date],
            src.[due_date],
            src.[commitment_date],
            src.[afe_approval_date],
            src.[afe_start_date],
            src.[budget_activity_year],
            src.[extrapolated_budget_year],
            src.[project_approval_status],
            src.[project_execution_status],
            src.[afe_date],
            src.[acct_yr],
            src.[alloc_amt],
            src.[tax_code],
            src.[capital_accrual_method_code],
            src.[managing_org_id],
            src.[net_estimate_pct],
            src.[internal_approver],
            src.[manager_name],
            src.[success_effort_type_code],
            src.[capital_accrual_cc_num],
            src.[equip_component_amt],
            src.[wrhse_component_amt],
            src.[translation_rate],
            src.[original_alloc_amt],
            src.[reporting_alloc_amt],
            src.[allow_other_orgs_code],
            src.[province],
            src.[engineer_assigned],
            src.[geologist_assigned],
            src.[geophysicist_assigned],
            src.[last_updt_status_user],
            src.[last_updt_status_date],
            src.[doi_type_code],
            src.[afe_class_code],
            src.[default_gl_sub_code],
            src.[overhead_start_date],
            src.[overhead_end_date],
            src.[capital_or_dry_hole_exp_code],
            src.[last_accrued_date],
            src.[country_code],
            src.[survey_system_code],
            src.[primary_uwi],
            src.[uwi_alias],
            src.[primary_location],
            src.[sorted_uwi],
            src.[uwi_sort_element_1],
            src.[uwi_sort_element_2],
            src.[uwi_sort_element_3],
            src.[uwi_sort_element_4],
            src.[uwi_sort_element_5],
            src.[uwi_sort_element_6],
            src.[uwi_sort_element_7],
            src.[uwi_sort_element_8],
            src.[uwi_sort_element_9],
            src.[afe_udf_1_code],
            src.[afe_udf_5_code],
            src.[afe_udf_7_code],
            src.[afe_udf_20_code],
            src.[project_justification_comments],
			src.[budget_activity_year_desc],
			src.[afe_type_group],
			src.[afe_type_group_desc],
			src.[job_start_date],
			src.[rig_number],
			src.[rig_name],
			src.[zone_play],
			src.[wellview_spud_date],
			src.[wellview_rig_release_date], 
			src.[wellview_total_depth], 
			src.[wellview_intermediate_casing_depth],
			src.[wellview_horizontal_depth],
			src.AFE_GCA_FCC,
			src.cc_list,
			src.Number_of_CCs,
			src.job_end_date
          FROM
            [stage].[v_qbyte_authorization_for_expenditure_attributes] as src
          LEFT JOIN [data_mart].[t_dim_authorization_for_expenditure] as trg
            ON trg.afe_num = src.afe_num
          WHERE
		    trg.afe_num  IS NULL

          UNION ALL

          SELECT
		    'UPDATE' Flag,
            src.[afe_num],
            src.[afe_name],
            src.[client_id],
            src.[client_name],
            src.[op_nonop],
            src.[ref_org_id],
            src.[afe_type_code],
            src.[afe_type_description],
            src.[afe_status_code],
            src.[afe_status_description],
            src.[cost_centre],
            src.[cost_centre_name],
            src.[corp_code],
            src.[corp_name],
            src.[region],
            src.[region_code],
            src.[region_name],
            src.[district],
            src.[district_code],
            src.[district_name],
            src.[area],
            src.[area_code],
            src.[area_name],
            src.[facility],
            src.[facility_code],
            src.[facility_name],
            src.[curr_code],
            src.[ownership_org_id],
            src.[jib_flag],
            src.[cip_transfer_flag],
            src.[use_jibe_edits_flag],
            src.[accrual_flag],
            src.[create_date],
            src.[create_user],
            src.[last_updt_date],
            src.[last_updt_user],
            src.[term_date],
            src.[term_user],
            src.[effective_date],
            src.[proposal_date],
            src.[due_date],
            src.[commitment_date],
            src.[afe_approval_date],
            src.[afe_start_date],
            src.[budget_activity_year],
            src.[extrapolated_budget_year],
            src.[project_approval_status],
            src.[project_execution_status],
            src.[afe_date],
            src.[acct_yr],
            src.[alloc_amt],
            src.[tax_code],
            src.[capital_accrual_method_code],
            src.[managing_org_id],
            src.[net_estimate_pct],
            src.[internal_approver],
            src.[manager_name],
            src.[success_effort_type_code],
            src.[capital_accrual_cc_num],
            src.[equip_component_amt],
            src.[wrhse_component_amt],
            src.[translation_rate],
            src.[original_alloc_amt],
            src.[reporting_alloc_amt],
            src.[allow_other_orgs_code],
            src.[province],
            src.[engineer_assigned],
            src.[geologist_assigned],
            src.[geophysicist_assigned],
            src.[last_updt_status_user],
            src.[last_updt_status_date],
            src.[doi_type_code],
            src.[afe_class_code],
            src.[default_gl_sub_code],
            src.[overhead_start_date],
            src.[overhead_end_date],
            src.[capital_or_dry_hole_exp_code],
            src.[last_accrued_date],
            src.[country_code],
            src.[survey_system_code],
            src.[primary_uwi],
            src.[uwi_alias],
            src.[primary_location],
            src.[sorted_uwi],
            src.[uwi_sort_element_1],
            src.[uwi_sort_element_2],
            src.[uwi_sort_element_3],
            src.[uwi_sort_element_4],
            src.[uwi_sort_element_5],
            src.[uwi_sort_element_6],
            src.[uwi_sort_element_7],
            src.[uwi_sort_element_8],
            src.[uwi_sort_element_9],
            src.[afe_udf_1_code],
            src.[afe_udf_5_code],
            src.[afe_udf_7_code],
            src.[afe_udf_20_code],
            src.[project_justification_comments],
			src.[budget_activity_year_desc],
			src.[afe_type_group],
			src.[afe_type_group_desc],
			src.[job_start_date],
			src.[rig_number],
			src.[rig_name],
			src.[zone_play],
			src.[wellview_spud_date],
			src.[wellview_rig_release_date], 
			src.[wellview_total_depth], 
			src.[wellview_intermediate_casing_depth],
			src.[wellview_horizontal_depth],
			src.AFE_GCA_FCC,
			src.cc_list,
			src.Number_of_CCs,
			src.job_end_date
	      FROM
		    (
               SELECT
                 src.[afe_num],
                 src.[afe_name],
                 src.[client_id],
                 src.[client_name],
                 src.[op_nonop],
                 src.[ref_org_id],
                 src.[afe_type_code],
                 src.[afe_type_description],
                 src.[afe_status_code],
                 src.[afe_status_description],
                 src.[cost_centre],
                 src.[cost_centre_name],
                 src.[corp_code],
                 src.[corp_name],
                 src.[region],
                 src.[region_code],
                 src.[region_name],
                 src.[district],
                 src.[district_code],
                 src.[district_name],
                 src.[area],
                 src.[area_code],
                 src.[area_name],
                 src.[facility],
                 src.[facility_code],
                 src.[facility_name],
                 src.[curr_code],
                 src.[ownership_org_id],
                 src.[jib_flag],
                 src.[cip_transfer_flag],
                 src.[use_jibe_edits_flag],
                 src.[accrual_flag],
                 src.[create_date],
                 src.[create_user],
                 src.[last_updt_date],
                 src.[last_updt_user],
                 src.[term_date],
                 src.[term_user],
                 src.[effective_date],
                 src.[proposal_date],
                 src.[due_date],
                 src.[commitment_date],
                 src.[afe_approval_date],
                 src.[afe_start_date],
                 src.[budget_activity_year],
                 src.[extrapolated_budget_year],
                 src.[project_approval_status],
                 src.[project_execution_status],
                 src.[afe_date],
                 src.[acct_yr],
                 src.[alloc_amt],
                 src.[tax_code],
                 src.[capital_accrual_method_code],
                 src.[managing_org_id],
                 src.[net_estimate_pct],
                 src.[internal_approver],
                 src.[manager_name],
                 src.[success_effort_type_code],
                 src.[capital_accrual_cc_num],
                 src.[equip_component_amt],
                 src.[wrhse_component_amt],
                 src.[translation_rate],
                 src.[original_alloc_amt],
                 src.[reporting_alloc_amt],
                 src.[allow_other_orgs_code],
                 src.[province],
                 src.[engineer_assigned],
                 src.[geologist_assigned],
                 src.[geophysicist_assigned],
                 src.[last_updt_status_user],
                 src.[last_updt_status_date],
                 src.[doi_type_code],
                 src.[afe_class_code],
                 src.[default_gl_sub_code],
                 src.[overhead_start_date],
                 src.[overhead_end_date],
                 src.[capital_or_dry_hole_exp_code],
                 src.[last_accrued_date],
                 src.[country_code],
                 src.[survey_system_code],
                 src.[primary_uwi],
                 src.[uwi_alias],
                 src.[primary_location],
                 src.[sorted_uwi],
                 src.[uwi_sort_element_1],
                 src.[uwi_sort_element_2],
                 src.[uwi_sort_element_3],
                 src.[uwi_sort_element_4],
                 src.[uwi_sort_element_5],
                 src.[uwi_sort_element_6],
                 src.[uwi_sort_element_7],
                 src.[uwi_sort_element_8],
                 src.[uwi_sort_element_9],
                 src.[afe_udf_1_code],
                 src.[afe_udf_5_code],
                 src.[afe_udf_7_code],
                 src.[afe_udf_20_code],
                 src.[project_justification_comments],
			     src.[budget_activity_year_desc],
			     src.[afe_type_group],
			     src.[afe_type_group_desc],
			     src.[job_start_date],
			     src.[rig_number],
			     src.[rig_name],
			     src.[zone_play],
			     src.[wellview_spud_date],
			     src.[wellview_rig_release_date], 
			     src.[wellview_total_depth], 
			     src.[wellview_intermediate_casing_depth],
			     src.[wellview_horizontal_depth],
			     src.AFE_GCA_FCC,
			     src.cc_list,
			     src.Number_of_CCs,
			     src.job_end_date
               FROM
                 [stage].[v_qbyte_authorization_for_expenditure_attributes] as src
               INNER JOIN [data_mart].[t_dim_authorization_for_expenditure] as trg
                 ON trg.afe_num = src.afe_num

               EXCEPT

               SELECT
                 trg.[afe_num],
                 trg.[afe_name],
                 trg.[client_id],
                 trg.[client_name],
                 trg.[op_nonop],
                 trg.[ref_org_id],
                 trg.[afe_type_code],
                 trg.[afe_type_description],
                 trg.[afe_status_code],
                 trg.[afe_status_description],
                 trg.[cost_centre],
                 trg.[cost_centre_name],
                 trg.[corp_code],
                 trg.[corp_name],
                 trg.[region],
                 trg.[region_code],
                 trg.[region_name],
                 trg.[district],
                 trg.[district_code],
                 trg.[district_name],
                 trg.[area],
                 trg.[area_code],
                 trg.[area_name],
                 trg.[facility],
                 trg.[facility_code],
                 trg.[facility_name],
                 trg.[curr_code],
                 trg.[ownership_org_id],
                 trg.[jib_flag],
                 trg.[cip_transfer_flag],
                 trg.[use_jibe_edits_flag],
                 trg.[accrual_flag],
                 trg.[create_date],
                 trg.[create_user],
                 trg.[last_updt_date],
                 trg.[last_updt_user],
                 trg.[term_date],
                 trg.[term_user],
                 trg.[effective_date],
                 trg.[proposal_date],
                 trg.[due_date],
                 trg.[commitment_date],
                 trg.[afe_approval_date],
                 trg.[afe_start_date],
                 trg.[budget_activity_year],
                 trg.[extrapolated_budget_year],
                 trg.[project_approval_status],
                 trg.[project_execution_status],
                 trg.[afe_date],
                 trg.[acct_yr],
                 trg.[alloc_amt],
                 trg.[tax_code],
                 trg.[capital_accrual_method_code],
                 trg.[managing_org_id],
                 trg.[net_estimate_pct],
                 trg.[internal_approver],
                 trg.[manager_name],
                 trg.[success_effort_type_code],
                 trg.[capital_accrual_cc_num],
                 trg.[equip_component_amt],
                 trg.[wrhse_component_amt],
                 trg.[translation_rate],
                 trg.[original_alloc_amt],
                 trg.[reporting_alloc_amt],
                 trg.[allow_other_orgs_code],
                 trg.[province],
                 trg.[engineer_assigned],
                 trg.[geologist_assigned],
                 trg.[geophysicist_assigned],
                 trg.[last_updt_status_user],
                 trg.[last_updt_status_date],
                 trg.[doi_type_code],
                 trg.[afe_class_code],
                 trg.[default_gl_sub_code],
                 trg.[overhead_start_date],
                 trg.[overhead_end_date],
                 trg.[capital_or_dry_hole_exp_code],
                 trg.[last_accrued_date],
                 trg.[country_code],
                 trg.[survey_system_code],
                 trg.[primary_uwi],
                 trg.[uwi_alias],
                 trg.[primary_location],
                 trg.[sorted_uwi],
                 trg.[uwi_sort_element_1],
                 trg.[uwi_sort_element_2],
                 trg.[uwi_sort_element_3],
                 trg.[uwi_sort_element_4],
                 trg.[uwi_sort_element_5],
                 trg.[uwi_sort_element_6],
                 trg.[uwi_sort_element_7],
                 trg.[uwi_sort_element_8],
                 trg.[uwi_sort_element_9],
                 trg.[afe_udf_1_code],
                 trg.[afe_udf_5_code],
                 trg.[afe_udf_7_code],
                 trg.[afe_udf_20_code],
                 trg.[project_justification_comments],
			     trg.[budget_activity_year_desc],
			     trg.[afe_type_group],
			     trg.[afe_type_group_desc],
			     trg.[job_start_date],
			     trg.[rig_number],
			     trg.[rig_name],
			     trg.[zone_play],
			     trg.[wellview_spud_date],
			     trg.[wellview_rig_release_date], 
			     trg.[wellview_total_depth], 
			     trg.[wellview_intermediate_casing_depth],
			     trg.[wellview_horizontal_depth],
			     trg.AFE_GCA_FCC,
			     trg.cc_list,
			     trg.Number_of_CCs,
			     trg.job_end_date
               FROM
                 [data_mart].[t_dim_authorization_for_expenditure] as trg                 
			) src


      INSERT INTO [data_mart].[t_dim_authorization_for_expenditure]
	    (
           [afe_num],
           [afe_name],
           [client_id],
           [client_name],
           [op_nonop],
           [ref_org_id],
           [afe_type_code],
           [afe_type_description],
           [afe_status_code],
           [afe_status_description],
           [cost_centre],
           [cost_centre_name],
           [corp_code],
           [corp_name],
           [region],
           [region_code],
           [region_name],
           [district],
           [district_code],
           [district_name],
           [area],
           [area_code],
           [area_name],
           [facility],
           [facility_code],
           [facility_name],
           [curr_code],
           [ownership_org_id],
           [jib_flag],
           [cip_transfer_flag],
           [use_jibe_edits_flag],
           [accrual_flag],
           [create_date],
           [create_user],
           [last_updt_date],
           [last_updt_user],
           [term_date],
           [term_user],
           [effective_date],
           [proposal_date],
           [due_date],
           [commitment_date],
           [afe_approval_date],
           [afe_start_date],
           [budget_activity_year],
           [extrapolated_budget_year],
           [project_approval_status],
           [project_execution_status],
           [afe_date],
           [acct_yr],
           [alloc_amt],
           [tax_code],
           [capital_accrual_method_code],
           [managing_org_id],
           [net_estimate_pct],
           [internal_approver],
           [manager_name],
           [success_effort_type_code],
           [capital_accrual_cc_num],
           [equip_component_amt],
           [wrhse_component_amt],
           [translation_rate],
           [original_alloc_amt],
           [reporting_alloc_amt],
           [allow_other_orgs_code],
           [province],
           [engineer_assigned],
           [geologist_assigned],
           [geophysicist_assigned],
           [last_updt_status_user],
           [last_updt_status_date],
           [doi_type_code],
           [afe_class_code],
           [default_gl_sub_code],
           [overhead_start_date],
           [overhead_end_date],
           [capital_or_dry_hole_exp_code],
           [last_accrued_date],
           [country_code],
           [survey_system_code],
           [primary_uwi],
           [uwi_alias],
           [primary_location],
           [sorted_uwi],
           [uwi_sort_element_1],
           [uwi_sort_element_2],
           [uwi_sort_element_3],
           [uwi_sort_element_4],
           [uwi_sort_element_5],
           [uwi_sort_element_6],
           [uwi_sort_element_7],
           [uwi_sort_element_8],
           [uwi_sort_element_9],
           [afe_udf_1_code],
           [afe_udf_5_code],
           [afe_udf_7_code],
           [afe_udf_20_code],
           [project_justification_comments],
		   [budget_activity_year_desc],
		   [afe_type_group],
		   [afe_type_group_desc],
		   [job_start_date],
		   [rig_number],
		   [rig_name],
		   [zone_play],
		   [wellview_spud_date],
		   [wellview_rig_release_date], 
		   [wellview_total_depth], 
		   [wellview_intermediate_casing_depth],
		   [wellview_horizontal_depth],
		   AFE_GCA_FCC,
		   cc_list,
		   Number_of_CCs,
		   job_end_date
		)
        SELECT
          src.[afe_num],
          src.[afe_name],
          src.[client_id],
          src.[client_name],
          src.[op_nonop],
          src.[ref_org_id],
          src.[afe_type_code],
          src.[afe_type_description],
          src.[afe_status_code],
          src.[afe_status_description],
          src.[cost_centre],
          src.[cost_centre_name],
          src.[corp_code],
          src.[corp_name],
          src.[region],
          src.[region_code],
          src.[region_name],
          src.[district],
          src.[district_code],
          src.[district_name],
          src.[area],
          src.[area_code],
          src.[area_name],
          src.[facility],
          src.[facility_code],
          src.[facility_name],
          src.[curr_code],
          src.[ownership_org_id],
          src.[jib_flag],
          src.[cip_transfer_flag],
          src.[use_jibe_edits_flag],
          src.[accrual_flag],
          src.[create_date],
          src.[create_user],
          src.[last_updt_date],
          src.[last_updt_user],
          src.[term_date],
          src.[term_user],
          src.[effective_date],
          src.[proposal_date],
          src.[due_date],
          src.[commitment_date],
          src.[afe_approval_date],
          src.[afe_start_date],
          src.[budget_activity_year],
          src.[extrapolated_budget_year],
          src.[project_approval_status],
          src.[project_execution_status],
          src.[afe_date],
          src.[acct_yr],
          src.[alloc_amt],
          src.[tax_code],
          src.[capital_accrual_method_code],
          src.[managing_org_id],
          src.[net_estimate_pct],
          src.[internal_approver],
          src.[manager_name],
          src.[success_effort_type_code],
          src.[capital_accrual_cc_num],
          src.[equip_component_amt],
          src.[wrhse_component_amt],
          src.[translation_rate],
          src.[original_alloc_amt],
          src.[reporting_alloc_amt],
          src.[allow_other_orgs_code],
          src.[province],
          src.[engineer_assigned],
          src.[geologist_assigned],
          src.[geophysicist_assigned],
          src.[last_updt_status_user],
          src.[last_updt_status_date],
          src.[doi_type_code],
          src.[afe_class_code],
          src.[default_gl_sub_code],
          src.[overhead_start_date],
          src.[overhead_end_date],
          src.[capital_or_dry_hole_exp_code],
          src.[last_accrued_date],
          src.[country_code],
          src.[survey_system_code],
          src.[primary_uwi],
          src.[uwi_alias],
          src.[primary_location],
          src.[sorted_uwi],
          src.[uwi_sort_element_1],
          src.[uwi_sort_element_2],
          src.[uwi_sort_element_3],
          src.[uwi_sort_element_4],
          src.[uwi_sort_element_5],
          src.[uwi_sort_element_6],
          src.[uwi_sort_element_7],
          src.[uwi_sort_element_8],
          src.[uwi_sort_element_9],
          src.[afe_udf_1_code],
          src.[afe_udf_5_code],
          src.[afe_udf_7_code],
          src.[afe_udf_20_code],
          src.[project_justification_comments],
		  src.[budget_activity_year_desc],
		  src.[afe_type_group],
		  src.[afe_type_group_desc],
		  src.[job_start_date],
		  src.[rig_number],
		  src.[rig_name],
		  src.[zone_play],
		  src.[wellview_spud_date],
		  src.[wellview_rig_release_date], 
		  src.[wellview_total_depth], 
		  src.[wellview_intermediate_casing_depth],
		  src.[wellview_horizontal_depth],
		  src.AFE_GCA_FCC,
		  src.cc_list,
		  src.Number_of_CCs,
		  src.job_end_date
        FROM
		  #t_dim_entity_MERGE src
        WHERE 
		  Flag = 'NEW'

	  -------- ROW_COUNT
	  --DECLARE  @rowcnt INT
	  --EXEC [dbo].[LastRowCount] @rowcnt OUTPUT	

	  UPDATE [data_mart].[t_dim_authorization_for_expenditure]
      SET
        [data_mart].[t_dim_authorization_for_expenditure].[afe_name]                       = UPD.[afe_name],
        [data_mart].[t_dim_authorization_for_expenditure].[client_id]                      = UPD.[client_id],
        [data_mart].[t_dim_authorization_for_expenditure].[client_name]                    = UPD.[client_name],
        [data_mart].[t_dim_authorization_for_expenditure].[op_nonop]                       = UPD.[op_nonop],
        [data_mart].[t_dim_authorization_for_expenditure].[ref_org_id]                     = UPD.[ref_org_id],
        [data_mart].[t_dim_authorization_for_expenditure].[afe_type_code]                  = UPD.[afe_type_code],
        [data_mart].[t_dim_authorization_for_expenditure].[afe_type_description]           = UPD.[afe_type_description],
        [data_mart].[t_dim_authorization_for_expenditure].[afe_status_code]                = UPD.[afe_status_code],
        [data_mart].[t_dim_authorization_for_expenditure].[afe_status_description]         = UPD.[afe_status_description],
        [data_mart].[t_dim_authorization_for_expenditure].[cost_centre]                    = UPD.[cost_centre],
        [data_mart].[t_dim_authorization_for_expenditure].[cost_centre_name]               = UPD.[cost_centre_name],
        [data_mart].[t_dim_authorization_for_expenditure].[corp_code]                      = UPD.[corp_code],
        [data_mart].[t_dim_authorization_for_expenditure].[corp_name]                      = UPD.[corp_name],
        [data_mart].[t_dim_authorization_for_expenditure].[region]                         = UPD.[region],
        [data_mart].[t_dim_authorization_for_expenditure].[region_code]                    = UPD.[region_code],
        [data_mart].[t_dim_authorization_for_expenditure].[region_name]                    = UPD.[region_name],
        [data_mart].[t_dim_authorization_for_expenditure].[district]                       = UPD.[district],
        [data_mart].[t_dim_authorization_for_expenditure].[district_code]                  = UPD.[district_code],
        [data_mart].[t_dim_authorization_for_expenditure].[district_name]                  = UPD.[district_name],
        [data_mart].[t_dim_authorization_for_expenditure].[area]                           = UPD.[area],
        [data_mart].[t_dim_authorization_for_expenditure].[area_code]                      = UPD.[area_code],
        [data_mart].[t_dim_authorization_for_expenditure].[area_name]                      = UPD.[area_name],
        [data_mart].[t_dim_authorization_for_expenditure].[facility]                       = UPD.[facility],
        [data_mart].[t_dim_authorization_for_expenditure].[facility_code]                  = UPD.[facility_code],
        [data_mart].[t_dim_authorization_for_expenditure].[facility_name]                  = UPD.[facility_name],
        [data_mart].[t_dim_authorization_for_expenditure].[curr_code]                      = UPD.[curr_code],
        [data_mart].[t_dim_authorization_for_expenditure].[ownership_org_id]               = UPD.[ownership_org_id],
        [data_mart].[t_dim_authorization_for_expenditure].[jib_flag]                       = UPD.[jib_flag],
        [data_mart].[t_dim_authorization_for_expenditure].[cip_transfer_flag]              = UPD.[cip_transfer_flag],
        [data_mart].[t_dim_authorization_for_expenditure].[use_jibe_edits_flag]            = UPD.[use_jibe_edits_flag],
        [data_mart].[t_dim_authorization_for_expenditure].[accrual_flag]                   = UPD.[accrual_flag],
        [data_mart].[t_dim_authorization_for_expenditure].[create_date]                    = UPD.[create_date],
        [data_mart].[t_dim_authorization_for_expenditure].[create_user]                    = UPD.[create_user],
        [data_mart].[t_dim_authorization_for_expenditure].[last_updt_date]                 = UPD.[last_updt_date],
        [data_mart].[t_dim_authorization_for_expenditure].[last_updt_user]                 = UPD.[last_updt_user],
        [data_mart].[t_dim_authorization_for_expenditure].[term_date]                      = UPD.[term_date],
        [data_mart].[t_dim_authorization_for_expenditure].[term_user]                      = UPD.[term_user],
        [data_mart].[t_dim_authorization_for_expenditure].[effective_date]                 = UPD.[effective_date],
        [data_mart].[t_dim_authorization_for_expenditure].[proposal_date]                  = UPD.[proposal_date],
        [data_mart].[t_dim_authorization_for_expenditure].[due_date]                       = UPD.[due_date],
        [data_mart].[t_dim_authorization_for_expenditure].[commitment_date]                = UPD.[commitment_date],
        [data_mart].[t_dim_authorization_for_expenditure].[afe_approval_date]              = UPD.[afe_approval_date],
        [data_mart].[t_dim_authorization_for_expenditure].[afe_start_date]                 = UPD.[afe_start_date],
        [data_mart].[t_dim_authorization_for_expenditure].[budget_activity_year]           = UPD.[budget_activity_year],
        [data_mart].[t_dim_authorization_for_expenditure].[extrapolated_budget_year]       = UPD.[extrapolated_budget_year],
        [data_mart].[t_dim_authorization_for_expenditure].[project_approval_status]        = UPD.[project_approval_status],
        [data_mart].[t_dim_authorization_for_expenditure].[project_execution_status]       = UPD.[project_execution_status],
        [data_mart].[t_dim_authorization_for_expenditure].[afe_date]                       = UPD.[afe_date],
        [data_mart].[t_dim_authorization_for_expenditure].[acct_yr]                        = UPD.[acct_yr],
        [data_mart].[t_dim_authorization_for_expenditure].[alloc_amt]                      = UPD.[alloc_amt],
        [data_mart].[t_dim_authorization_for_expenditure].[tax_code]                       = UPD.[tax_code],
        [data_mart].[t_dim_authorization_for_expenditure].[capital_accrual_method_code]    = UPD.[capital_accrual_method_code],
        [data_mart].[t_dim_authorization_for_expenditure].[managing_org_id]                = UPD.[managing_org_id],
        [data_mart].[t_dim_authorization_for_expenditure].[net_estimate_pct]               = UPD.[net_estimate_pct],
        [data_mart].[t_dim_authorization_for_expenditure].[internal_approver]              = UPD.[internal_approver],
        [data_mart].[t_dim_authorization_for_expenditure].[manager_name]                   = UPD.[manager_name],
        [data_mart].[t_dim_authorization_for_expenditure].[success_effort_type_code]       = UPD.[success_effort_type_code],
        [data_mart].[t_dim_authorization_for_expenditure].[capital_accrual_cc_num]         = UPD.[capital_accrual_cc_num],
        [data_mart].[t_dim_authorization_for_expenditure].[equip_component_amt]            = UPD.[equip_component_amt],
        [data_mart].[t_dim_authorization_for_expenditure].[wrhse_component_amt]            = UPD.[wrhse_component_amt],
        [data_mart].[t_dim_authorization_for_expenditure].[translation_rate]               = UPD.[translation_rate],
        [data_mart].[t_dim_authorization_for_expenditure].[original_alloc_amt]             = UPD.[original_alloc_amt],
        [data_mart].[t_dim_authorization_for_expenditure].[reporting_alloc_amt]            = UPD.[reporting_alloc_amt],
        [data_mart].[t_dim_authorization_for_expenditure].[allow_other_orgs_code]          = UPD.[allow_other_orgs_code],
        [data_mart].[t_dim_authorization_for_expenditure].[province]                       = UPD.[province],
        [data_mart].[t_dim_authorization_for_expenditure].[engineer_assigned]              = UPD.[engineer_assigned],
        [data_mart].[t_dim_authorization_for_expenditure].[geologist_assigned]             = UPD.[geologist_assigned],
        [data_mart].[t_dim_authorization_for_expenditure].[geophysicist_assigned]          = UPD.[geophysicist_assigned],
        [data_mart].[t_dim_authorization_for_expenditure].[last_updt_status_user]          = UPD.[last_updt_status_user],
        [data_mart].[t_dim_authorization_for_expenditure].[last_updt_status_date]          = UPD.[last_updt_status_date],
        [data_mart].[t_dim_authorization_for_expenditure].[doi_type_code]                  = UPD.[doi_type_code],
        [data_mart].[t_dim_authorization_for_expenditure].[afe_class_code]                 = UPD.[afe_class_code],
        [data_mart].[t_dim_authorization_for_expenditure].[default_gl_sub_code]            = UPD.[default_gl_sub_code],
        [data_mart].[t_dim_authorization_for_expenditure].[overhead_start_date]            = UPD.[overhead_start_date],
        [data_mart].[t_dim_authorization_for_expenditure].[overhead_end_date]              = UPD.[overhead_end_date],
        [data_mart].[t_dim_authorization_for_expenditure].[capital_or_dry_hole_exp_code]   = UPD.[capital_or_dry_hole_exp_code],
        [data_mart].[t_dim_authorization_for_expenditure].[last_accrued_date]              = UPD.[last_accrued_date],
        [data_mart].[t_dim_authorization_for_expenditure].[country_code]                   = UPD.[country_code],
        [data_mart].[t_dim_authorization_for_expenditure].[survey_system_code]             = UPD.[survey_system_code],
        [data_mart].[t_dim_authorization_for_expenditure].[primary_uwi]                    = UPD.[primary_uwi],
        [data_mart].[t_dim_authorization_for_expenditure].[uwi_alias]                      = UPD.[uwi_alias],
        [data_mart].[t_dim_authorization_for_expenditure].[primary_location]               = UPD.[primary_location],
        [data_mart].[t_dim_authorization_for_expenditure].[sorted_uwi]                     = UPD.[sorted_uwi],
        [data_mart].[t_dim_authorization_for_expenditure].[uwi_sort_element_1]             = UPD.[uwi_sort_element_1],
        [data_mart].[t_dim_authorization_for_expenditure].[uwi_sort_element_2]             = UPD.[uwi_sort_element_2],
        [data_mart].[t_dim_authorization_for_expenditure].[uwi_sort_element_3]             = UPD.[uwi_sort_element_3],
        [data_mart].[t_dim_authorization_for_expenditure].[uwi_sort_element_4]             = UPD.[uwi_sort_element_4],
        [data_mart].[t_dim_authorization_for_expenditure].[uwi_sort_element_5]             = UPD.[uwi_sort_element_5],
        [data_mart].[t_dim_authorization_for_expenditure].[uwi_sort_element_6]             = UPD.[uwi_sort_element_6],
        [data_mart].[t_dim_authorization_for_expenditure].[uwi_sort_element_7]             = UPD.[uwi_sort_element_7],
        [data_mart].[t_dim_authorization_for_expenditure].[uwi_sort_element_8]             = UPD.[uwi_sort_element_8],
        [data_mart].[t_dim_authorization_for_expenditure].[uwi_sort_element_9]             = UPD.[uwi_sort_element_9],
        [data_mart].[t_dim_authorization_for_expenditure].[afe_udf_1_code]                 = UPD.[afe_udf_1_code],
        [data_mart].[t_dim_authorization_for_expenditure].[afe_udf_5_code]                 = UPD.[afe_udf_5_code],
        [data_mart].[t_dim_authorization_for_expenditure].[afe_udf_7_code]                 = UPD.[afe_udf_7_code],
        [data_mart].[t_dim_authorization_for_expenditure].[afe_udf_20_code]                = UPD.[afe_udf_20_code],
        [data_mart].[t_dim_authorization_for_expenditure].[project_justification_comments] = UPD.[project_justification_comments],
		[data_mart].[t_dim_authorization_for_expenditure].[budget_activity_year_desc]      = UPD.[budget_activity_year_desc],
		[data_mart].[t_dim_authorization_for_expenditure].[afe_type_group]				   = UPD.[afe_type_group],
		[data_mart].[t_dim_authorization_for_expenditure].[afe_type_group_desc]			   = UPD.[afe_type_group_desc],
		[data_mart].[t_dim_authorization_for_expenditure].[job_start_date]				   = UPD.[job_start_date],
		[data_mart].[t_dim_authorization_for_expenditure].[rig_number]				       = UPD.[rig_number],
		[data_mart].[t_dim_authorization_for_expenditure].[rig_name]					   = UPD.[rig_name],
		[data_mart].[t_dim_authorization_for_expenditure].[zone_play]					   = UPD.[zone_play],
		[data_mart].[t_dim_authorization_for_expenditure].[wellview_spud_date]			   = UPD.[wellview_spud_date],
		[data_mart].[t_dim_authorization_for_expenditure].[wellview_rig_release_date]      = UPD.[wellview_rig_release_date], 
		[data_mart].[t_dim_authorization_for_expenditure].[wellview_total_depth]		   = UPD.[wellview_total_depth], 
		[data_mart].[t_dim_authorization_for_expenditure].[wellview_intermediate_casing_depth] = UPD.[wellview_intermediate_casing_depth],
		[data_mart].[t_dim_authorization_for_expenditure].[wellview_horizontal_depth]		   = UPD.[wellview_horizontal_depth],
		[data_mart].[t_dim_authorization_for_expenditure].AFE_GCA_FCC						   = UPD.AFE_GCA_FCC,
		[data_mart].[t_dim_authorization_for_expenditure].cc_list							   = UPD.cc_list,
		[data_mart].[t_dim_authorization_for_expenditure].Number_of_CCs					       = UPD.Number_of_CCs,
		[data_mart].[t_dim_authorization_for_expenditure].job_end_date					       = UPD.job_end_date
      FROM #t_dim_entity_MERGE UPD
      WHERE 
        [data_mart].[t_dim_authorization_for_expenditure].afe_num = UPD.afe_num AND
	    UPD.Flag = 'UPDATE'	

     --     
     -- End of Merge AFEs from [stage].[dbo].[v_qbyte_authorization_for_expenditure_attributes]
     
    -- COMMIT TRANSACTION

     IF @complete_rebuild_flag = 'Y'
         BEGIN

          --   BEGIN TRANSACTION
		     SET IDENTITY_INSERT [data_mart].[t_dim_authorization_for_expenditure] ON;
             INSERT INTO [data_mart].[t_dim_authorization_for_expenditure]
                ([afe_key],
                 [afe_num]
                )
             VALUES
                ('-2',
                 'Missing'
                );

             INSERT INTO [data_mart].[t_dim_authorization_for_expenditure]
                ([afe_key],
                 [afe_num]
                )
             VALUES
                ('-1',
                 'Unknown'
                );

            -- COMMIT TRANSACTION
			SET IDENTITY_INSERT [data_mart].[t_dim_authorization_for_expenditure] OFF;
         END

 END TRY
 
 BEGIN CATCH
        
       -- Grab error information from SQL functions
          DECLARE @ErrorSeverity INT           = ERROR_SEVERITY(),
                  @ErrorNumber INT             = ERROR_NUMBER(),
                  @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE(),
                  @ErrorState INT              = ERROR_STATE(),
                --  @ErrorLine INT               = ERROR_LINE(),
                  @ErrorProc nvarchar(200)     = ERROR_PROCEDURE()
                    
          -- If the error renders the transaction as uncommittable or we have open transactions, rollback
          --IF @@TRANCOUNT > 0
          --BEGIN
          --   ROLLBACK TRANSACTION
          --END

          RAISERROR (@ErrorMessage , @ErrorSeverity, @ErrorState, @ErrorNumber)

  END CATCH
 -- RETURN @@ERROR
END