CREATE PROC [data_mart].[build_dim_entity] @complete_rebuild_flag [varchar](1) AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
  SET NOCOUNT ON;

  IF @complete_rebuild_flag IS NULL OR @complete_rebuild_flag = ''
    SET @complete_rebuild_flag = 'N'

  BEGIN TRY	

	IF @complete_rebuild_flag = 'Y'
	   
	  BEGIN

	   -- BEGIN TRANSACTION

	  	  TRUNCATE TABLE [data_mart].[t_dim_entity];

		--COMMIT TRANSACTION

	  END

	--BEGIN TRANSACTION			
	
	  -- Merge Cost Centres from [stage].[dbo].[v_dim_source_entity_cost_centre_hierarchy]
      IF OBJECT_ID('tempdb..#t_dim_entity_MERGE') IS NOT NULL
        DROP TABLE #t_dim_entity_MERGE	 

      CREATE TABLE #t_dim_entity_MERGE WITH (DISTRIBUTION = ROUND_ROBIN)
        AS
		  SELECT
		    'NEW' Flag,
            src.cost_centre_id [entity_key],
	        src.[cost_centre_name] [entity_name],
	        src.[cost_centre_id] [cost_centre],
	        src.[cost_centre_name],
	        src.[corp],
	        src.[corp_name],
	        src.[region],
	        src.[region_name],
	        src.[region_code],
	        src.[district],
	        src.[district_name],
            src.[district_code],
	        src.[area],
	        src.[area_name],
	        src.[area_code],
	        src.[facility],
	        src.[facility_name],
            src.[facility_code],
	        src.[cc_type],
	        src.[cc_type_code],
	        src.[budget_group],
	        src.[budget_year],
	        src.[op_nonop],
	        src.[origin],
	        src.[province],
	        src.[create_date],
	        src.[spud_date],
	        src.[rig_release_date],
	        src.[on_production_date],
	        src.[acquired_from],
	        src.[current_reserves_property],
	        src.[disposition_package],
	        src.[disposition_type],
	        src.[disposition_area],
	        src.[disposition_facility],
	        src.[disposed_flag],
	        src.[focus_area_flag],
	        src.[primary_product],
	        src.[cgu],
	        src.[working_interest_pct],
	        src.[year_end_reserves_property],
	        src.[unit_cc_num],
	        src.[unit_cc_name],
	        src.[survey_system_code],
	        src.[uwi],
	        src.[uwi_desc],
	        src.[meridian],
	        src.[range],
	        src.[township],
	        src.[section],
	        src.[tax_pools],
	        src.[entity_source],
	        1 [is_cc_dim],
	        src.[cc_term_date],
	        src.[budget_year_group],
	        src.[origin_group],
	        src.[zone_play],
	        src.[gca_fcc],
	        src.[metrix_control_group],
	        src.[valnav_budget_year],
	        src.[valnav_budget_quarter],
	        src.[sales_disposition_point],
	        src.[last_production_date],
	        src.license_no,
	        src.on_prod_date_accumap,
	        src.on_prod_data_source,
	        src.qbyte_license,
	        src.surface_location,
	        src.Sask_Resource_Surcharge,
	        src.meter_station,
	        src.group1,
	        src.group2,
	        src.group3,
	        src.group4,
	        src.group5,
	        src.group6,
	        src.group7,
	        src.group8,
	        src.group9,
	        src.group10,
	        src.plant,
	        src.keyera_inlet
          FROM
            [stage].[v_dim_source_entity_cost_centre_hierarchy] as src
          LEFT JOIN [data_mart].[t_dim_entity] as trg
            ON trg.entity_key = src.cost_centre_id		    
          WHERE
		    trg.entity_key IS NULL

          UNION ALL

		  SELECT
		    'UPDATE' Flag,
            src.cost_centre_id [entity_key],
	        src.[cost_centre_name] [entity_name],
	        src.[cost_centre_id] [cost_centre],
	        src.[cost_centre_name],
	        src.[corp],
	        src.[corp_name],
	        src.[region],
	        src.[region_name],
	        src.[region_code],
	        src.[district],
	        src.[district_name],
            src.[district_code],
	        src.[area],
	        src.[area_name],
	        src.[area_code],
	        src.[facility],
	        src.[facility_name],
            src.[facility_code],
	        src.[cc_type],
	        src.[cc_type_code],
	        src.[budget_group],
	        src.[budget_year],
	        src.[op_nonop],
	        src.[origin],
	        src.[province],
	        src.[create_date],
	        src.[spud_date],
	        src.[rig_release_date],
	        src.[on_production_date],
	        src.[acquired_from],
	        src.[current_reserves_property],
	        src.[disposition_package],
	        src.[disposition_type],
	        src.[disposition_area],
	        src.[disposition_facility],
	        src.[disposed_flag],
	        src.[focus_area_flag],
	        src.[primary_product],
	        src.[cgu],
	        src.[working_interest_pct],
	        src.[year_end_reserves_property],
	        src.[unit_cc_num],
	        src.[unit_cc_name],
	        src.[survey_system_code],
	        src.[uwi],
	        src.[uwi_desc],
	        src.[meridian],
	        src.[range],
	        src.[township],
	        src.[section],
	        src.[tax_pools],
	        src.[entity_source],
	        1 [is_cc_dim],
	        src.[cc_term_date],
	        src.[budget_year_group],
	        src.[origin_group],
	        src.[zone_play],
	        src.[gca_fcc],
	        src.[metrix_control_group],
	        src.[valnav_budget_year],
	        src.[valnav_budget_quarter],
	        src.[sales_disposition_point],
	        src.[last_production_date],
	        src.license_no,
	        src.on_prod_date_accumap,
	        src.on_prod_data_source,
	        src.qbyte_license,
	        src.surface_location,
	        src.Sask_Resource_Surcharge,
	        src.meter_station,
	        src.group1,
	        src.group2,
	        src.group3,
	        src.group4,
	        src.group5,
	        src.group6,
	        src.group7,
	        src.group8,
	        src.group9,
	        src.group10,
	        src.plant,
	        src.keyera_inlet
          FROM
		    (
		       SELECT
                 src.cost_centre_id,
	             src.[cost_centre_name],
	             src.[corp],
	             src.[corp_name],
	             src.[region],
	             src.[region_name],
	             src.[region_code],
	             src.[district],
	             src.[district_name],
                 src.[district_code],
	             src.[area],
	             src.[area_name],
	             src.[area_code],
	             src.[facility],
	             src.[facility_name],
                 src.[facility_code],
	             src.[cc_type],
	             src.[cc_type_code],
	             src.[budget_group],
	             src.[budget_year],
	             src.[op_nonop],
	             src.[origin],
	             src.[province],
	             src.[create_date],
	             src.[spud_date],
	             src.[rig_release_date],
	             src.[on_production_date],
	             src.[acquired_from],
	             src.[current_reserves_property],
	             src.[disposition_package],
	             src.[disposition_type],
	             src.[disposition_area],
	             src.[disposition_facility],
	             src.[disposed_flag],
	             src.[focus_area_flag],
	             src.[primary_product],
	             src.[cgu],
	             src.[working_interest_pct],
	             src.[year_end_reserves_property],
	             src.[unit_cc_num],
	             src.[unit_cc_name],
	             src.[survey_system_code],
	             src.[uwi],
	             src.[uwi_desc],
	             src.[meridian],
	             src.[range],
	             src.[township],
	             src.[section],
	             src.[tax_pools],
	             src.[entity_source],
	             src.[cc_term_date],
	             src.[budget_year_group],
	             src.[origin_group],
	             src.[zone_play],
	             src.[gca_fcc],
	             src.[metrix_control_group],
	             src.[valnav_budget_year],
	             src.[valnav_budget_quarter],
	             src.[sales_disposition_point],
	             src.[last_production_date],
	             src.license_no,
	             src.on_prod_date_accumap,
	             src.on_prod_data_source,
	             src.qbyte_license,
	             src.surface_location,
	             src.Sask_Resource_Surcharge,
	             src.meter_station,
	             src.group1,
	             src.group2,
	             src.group3,
	             src.group4,
	             src.group5,
	             src.group6,
	             src.group7,
	             src.group8,
	             src.group9,
	             src.group10,
	             src.plant,
	             src.keyera_inlet
               FROM
                 [stage].[v_dim_source_entity_cost_centre_hierarchy] as src
               INNER JOIN [data_mart].[t_dim_entity] as trg
                 ON trg.entity_key = src.cost_centre_id	
				 
               EXCEPT

		       SELECT
                 trg.[entity_key] cost_centre_id,
	             trg.[cost_centre_name],
	             trg.[corp],
	             trg.[corp_name],
	             trg.[region],
	             trg.[region_name],
	             trg.[region_code],
	             trg.[district],
	             trg.[district_name],
                 trg.[district_code],
	             trg.[area],
	             trg.[area_name],
	             trg.[area_code],
	             trg.[facility],
	             trg.[facility_name],
                 trg.[facility_code],
	             trg.[cc_type],
	             trg.[cc_type_code],
	             trg.[budget_group],
	             trg.[budget_year],
	             trg.[op_nonop],
	             trg.[origin],
	             trg.[province],
	             trg.[create_date],
	             trg.[spud_date],
	             trg.[rig_release_date],
	             trg.[on_production_date],
	             trg.[acquired_from],
	             trg.[current_reserves_property],
	             trg.[disposition_package],
	             trg.[disposition_type],
	             trg.[disposition_area],
	             trg.[disposition_facility],
	             trg.[disposed_flag],
	             trg.[focus_area_flag],
	             trg.[primary_product],
	             trg.[cgu],
	             trg.[working_interest_pct],
	             trg.[year_end_reserves_property],
	             trg.[unit_cc_num],
	             trg.[unit_cc_name],
	             trg.[survey_system_code],
	             trg.[uwi],
	             trg.[uwi_desc],
	             trg.[meridian],
	             trg.[range],
	             trg.[township],
	             trg.[section],
	             trg.[tax_pools],
	             trg.[entity_source],
	             trg.[cc_term_date],
	             trg.[budget_year_group],
	             trg.[origin_group],
	             trg.[zone_play],
	             trg.[gca_fcc],
	             trg.[metrix_control_group],
	             trg.[valnav_budget_year],
	             trg.[valnav_budget_quarter],
	             trg.[sales_disposition_point],
	             trg.[last_production_date],
	             trg.license_no,
	             trg.on_prod_date_accumap,
	             trg.on_prod_data_source,
	             trg.qbyte_license,
	             trg.surface_location,
	             trg.Sask_Resource_Surcharge,
	             trg.meter_station,
	             trg.group1,
	             trg.group2,
	             trg.group3,
	             trg.group4,
	             trg.group5,
	             trg.group6,
	             trg.group7,
	             trg.group8,
	             trg.group9,
	             trg.group10,
	             trg.plant,
	             trg.keyera_inlet
               FROM
                 [data_mart].[t_dim_entity] as trg
			) src
		    
      INSERT INTO [data_mart].[t_dim_entity]
	    (
           [entity_key],
	       [entity_name],
	       [cost_centre],
	       [cost_centre_name],
	       [corp],
	       [corp_name],
	       [region],
	       [region_name],
	       [region_code],
	       [district],
	       [district_name],
           [district_code],
	       [area],
	       [area_name],
	       [area_code],
	       [facility],
	       [facility_name],
           [facility_code],
	       [cc_type],
	       [cc_type_code],
	       [budget_group],
	       [budget_year],
	       [op_nonop],
	       [origin],
	       [province],
	       [create_date],
	       [spud_date],
	       [rig_release_date],
	       [on_production_date],
	       [acquired_from],
	       [current_reserves_property],
	       [disposition_package],
	       [disposition_type],
	       [disposition_area],
	       [disposition_facility],
	       [disposed_flag],
	       [focus_area_flag],
	       [primary_product],
	       [cgu],
	       [working_interest_pct],
	       [year_end_reserves_property],
	       [unit_cc_num],
	       [unit_cc_name],
	       [survey_system_code],
	       [uwi],
	       [uwi_desc],
	       [meridian],
	       [range],
	       [township],
	       [section],
	       [tax_pools],
	       [entity_source],
	       [is_cc_dim],
	       [cc_term_date],
	       [budget_year_group],
	       [origin_group],
	       [zone_play],
	       [gca_fcc],
	       [metrix_control_group],
	       [valnav_budget_year],
	       [valnav_budget_quarter],
	       [sales_disposition_point],
	       [last_production_date],
	       license_no,
	       on_prod_date_accumap,
	       on_prod_data_source,
	       qbyte_license,
	       surface_location,
	       Sask_Resource_Surcharge,
	       meter_station,
	       group1,
	       group2,
	       group3,
	       group4,
	       group5,
	       group6,
	       group7,
	       group8,
	       group9,
	       group10,
	       plant,
	       keyera_inlet           
		)
	    SELECT
          src.[entity_key],
	      src.[entity_name],
	      src.[cost_centre],
	      src.[cost_centre_name],
	      src.[corp],
	      src.[corp_name],
	      src.[region],
	      src.[region_name],
	      src.[region_code],
	      src.[district],
	      src.[district_name],
          src.[district_code],
	      src.[area],
	      src.[area_name],
	      src.[area_code],
	      src.[facility],
	      src.[facility_name],
          src.[facility_code],
	      src.[cc_type],
	      src.[cc_type_code],
	      src.[budget_group],
	      src.[budget_year],
	      src.[op_nonop],
	      src.[origin],
	      src.[province],
	      src.[create_date],
	      src.[spud_date],
	      src.[rig_release_date],
	      src.[on_production_date],
	      src.[acquired_from],
	      src.[current_reserves_property],
	      src.[disposition_package],
	      src.[disposition_type],
	      src.[disposition_area],
	      src.[disposition_facility],
	      src.[disposed_flag],
	      src.[focus_area_flag],
	      src.[primary_product],
	      src.[cgu],
	      src.[working_interest_pct],
	      src.[year_end_reserves_property],
	      src.[unit_cc_num],
	      src.[unit_cc_name],
	      src.[survey_system_code],
	      src.[uwi],
	      src.[uwi_desc],
	      src.[meridian],
	      src.[range],
	      src.[township],
	      src.[section],
	      src.[tax_pools],
	      src.[entity_source],
	      src.[is_cc_dim],
	      src.[cc_term_date],
	      src.[budget_year_group],
	      src.[origin_group],
	      src.[zone_play],
	      src.[gca_fcc],
	      src.[metrix_control_group],
	      src.[valnav_budget_year],
	      src.[valnav_budget_quarter],
	      src.[sales_disposition_point],
	      src.[last_production_date],
	      src.license_no,
	      src.on_prod_date_accumap,
	      src.on_prod_data_source,
	      src.qbyte_license,
	      src.surface_location,
	      src.Sask_Resource_Surcharge,
	      src.meter_station,
	      src.group1,
	      src.group2,
	      src.group3,
	      src.group4,
	      src.group5,
	      src.group6,
	      src.group7,
	      src.group8,
	      src.group9,
	      src.group10,
	      src.plant,
	      src.keyera_inlet
        FROM
		  #t_dim_entity_MERGE src
        WHERE
		  Flag = 'NEW'

	  -------- ROW_COUNT
	  --DECLARE  @rowcnt INT
	  --EXEC [dbo].[LastRowCount] @rowcnt OUTPUT	

	  UPDATE [data_mart].[t_dim_entity]
      SET
		[data_mart].[t_dim_entity].[entity_name]				   =  UPD.[entity_name],
		[data_mart].[t_dim_entity].[cost_centre]				   =  UPD.[cost_centre],
		[data_mart].[t_dim_entity].[cost_centre_name]			   =  UPD.[cost_centre_name],
		[data_mart].[t_dim_entity].[corp]                          =  UPD.[corp],
		[data_mart].[t_dim_entity].[corp_name]                     =  UPD.[corp_name],
		[data_mart].[t_dim_entity].[region]                        =  UPD.[region],
		[data_mart].[t_dim_entity].[region_name]                   =  UPD.[region_name],
		[data_mart].[t_dim_entity].[region_code]                   =  UPD.[region_code],
		[data_mart].[t_dim_entity].[district]                      =  UPD.[district],
		[data_mart].[t_dim_entity].[district_name]                 =  UPD.[district_name],
		[data_mart].[t_dim_entity].[district_code]                 =  UPD.[district_code],
		[data_mart].[t_dim_entity].[area]                          =  UPD.[area],
		[data_mart].[t_dim_entity].[area_name]                     =  UPD.[area_name],
		[data_mart].[t_dim_entity].[area_code]                     =  UPD.[area_code],
		[data_mart].[t_dim_entity].[facility]                      =  UPD.[facility],
		[data_mart].[t_dim_entity].[facility_name]                 =  UPD.[facility_name],
		[data_mart].[t_dim_entity].[facility_code]                 =  UPD.[facility_code],
		[data_mart].[t_dim_entity].[cc_type]                       =  UPD.[cc_type],
		[data_mart].[t_dim_entity].[cc_type_code]                  =  UPD.[cc_type_code],
		[data_mart].[t_dim_entity].[budget_group]                  =  UPD.[budget_group],
		[data_mart].[t_dim_entity].[budget_year]                   =  UPD.[budget_year],
		[data_mart].[t_dim_entity].[op_nonop]                      =  UPD.[op_nonop],
		[data_mart].[t_dim_entity].[origin]                        =  UPD.[origin],
		[data_mart].[t_dim_entity].[province]                      =  UPD.[province],
		[data_mart].[t_dim_entity].[create_date]                   =  UPD.[create_date],
		[data_mart].[t_dim_entity].[spud_date]                     =  UPD.[spud_date],
		[data_mart].[t_dim_entity].[rig_release_date]              =  UPD.[rig_release_date],
		[data_mart].[t_dim_entity].[on_production_date]            =  UPD.[on_production_date],
		[data_mart].[t_dim_entity].[acquired_from]                 =  UPD.[acquired_from],
		[data_mart].[t_dim_entity].[current_reserves_property]     =  UPD.[current_reserves_property],
		[data_mart].[t_dim_entity].[disposition_package]           =  UPD.[disposition_package],
		[data_mart].[t_dim_entity].[disposition_type]              =  UPD.[disposition_type],
		[data_mart].[t_dim_entity].[disposition_area]              =  UPD.[disposition_area],
		[data_mart].[t_dim_entity].[disposition_facility]          =  UPD.[disposition_facility],
		[data_mart].[t_dim_entity].[disposed_flag]                 =  UPD.[disposed_flag],
		[data_mart].[t_dim_entity].[focus_area_flag]               =  UPD.[focus_area_flag],
		[data_mart].[t_dim_entity].[primary_product]               =  UPD.[primary_product],
		[data_mart].[t_dim_entity].[cgu]						   =  UPD.[cgu],
		[data_mart].[t_dim_entity].[working_interest_pct]          =  UPD.[working_interest_pct],
		[data_mart].[t_dim_entity].[year_end_reserves_property]    =  UPD.[year_end_reserves_property],
		[data_mart].[t_dim_entity].[unit_cc_num]                   =  UPD.[unit_cc_num],
		[data_mart].[t_dim_entity].[unit_cc_name]                  =  UPD.[unit_cc_name],
		[data_mart].[t_dim_entity].[survey_system_code]            =  UPD.[survey_system_code],
		[data_mart].[t_dim_entity].[uwi]						   =  UPD.[uwi],
		[data_mart].[t_dim_entity].[uwi_desc]					   =  UPD.[uwi_desc],
		[data_mart].[t_dim_entity].[meridian]                      =  UPD.[meridian],
		[data_mart].[t_dim_entity].[range]                         =  UPD.[range],
		[data_mart].[t_dim_entity].[township]                      =  UPD.[township],
		[data_mart].[t_dim_entity].[section]                       =  UPD.[section],
		[data_mart].[t_dim_entity].[tax_pools]					   =  UPD.[tax_pools],
		[data_mart].[t_dim_entity].[entity_source]				   =  UPD.[entity_source],
		[data_mart].[t_dim_entity].[is_cc_dim]					   =  UPD.[is_cc_dim],
		[data_mart].[t_dim_entity].[cc_term_date]				   =  UPD.[cc_term_date],
		[data_mart].[t_dim_entity].[budget_year_group]			   =  UPD.[budget_year_group],
		[data_mart].[t_dim_entity].[origin_group]				   =  UPD.[origin_group],
		[data_mart].[t_dim_entity].[zone_play]					   =  UPD.[zone_play],
		[data_mart].[t_dim_entity].[gca_fcc]					   =  UPD.[gca_fcc],
		[data_mart].[t_dim_entity].[metrix_control_group]		   =  UPD.[metrix_control_group],
		[data_mart].[t_dim_entity].[valnav_budget_year]			   =  UPD.[valnav_budget_year],
		[data_mart].[t_dim_entity].[valnav_budget_quarter]		   =  UPD.[valnav_budget_quarter],
		[data_mart].[t_dim_entity].[sales_disposition_point]	   =  UPD.[sales_disposition_point],
		[data_mart].[t_dim_entity].[last_production_date]          =  UPD.[last_production_date],
		[data_mart].[t_dim_entity].license_no					   =  UPD.license_no,
		[data_mart].[t_dim_entity].on_prod_date_accumap			   =  UPD.on_prod_date_accumap,
		[data_mart].[t_dim_entity].on_prod_data_source			   =  UPD.on_prod_data_source,
		[data_mart].[t_dim_entity].qbyte_license				   =  UPD.qbyte_license,
		[data_mart].[t_dim_entity].surface_location				   =  UPD.surface_location,
		[data_mart].[t_dim_entity].Sask_Resource_Surcharge		   =  UPD.Sask_Resource_Surcharge,
		[data_mart].[t_dim_entity].meter_station				   =  UPD.meter_station,
		[data_mart].[t_dim_entity].group1						   =  UPD.group1,
		[data_mart].[t_dim_entity].group2						   =  UPD.group2,
		[data_mart].[t_dim_entity].group3						   =  UPD.group3,
		[data_mart].[t_dim_entity].group4						   =  UPD.group4,
		[data_mart].[t_dim_entity].group5						   =  UPD.group5,
		[data_mart].[t_dim_entity].group6						   =  UPD.group6,
		[data_mart].[t_dim_entity].group7						   =  UPD.group7,
		[data_mart].[t_dim_entity].group8						   =  UPD.group8,
		[data_mart].[t_dim_entity].group9						   =  UPD.group9,
		[data_mart].[t_dim_entity].group10						   =  UPD.group10,
		[data_mart].[t_dim_entity].plant						   =  UPD.plant,
		[data_mart].[t_dim_entity].keyera_inlet				       =  UPD.keyera_inlet	
      FROM #t_dim_entity_MERGE UPD
      WHERE 
        [data_mart].[t_dim_entity].entity_key = UPD.entity_key AND
	    UPD.Flag = 'UPDATE'	

      -- End of Merge Cost Centres from [stage].[dbo].[v_qbyte_cc_hieararchy] 
	
  --  COMMIT TRANSACTION


	--BEGIN TRANSACTION

	-- Merge UWIs  from [stage].[dbo].[v_uwi_hierarchy_attributes]
      IF OBJECT_ID('tempdb..#t_dim_entity_MERGE') IS NOT NULL
        DROP TABLE #t_dim_entity_MERGE	 

      CREATE TABLE #t_dim_entity_MERGE WITH (DISTRIBUTION = ROUND_ROBIN)
        AS
		  SELECT
		    'NEW' Flag,
            src.uwi [entity_key],
	        src.[well_name] [entity_name],
	        src.[cost_centre],
	        src.[cost_centre_name],
	        src.[corp],
	        src.[corp_name],
	        src.[region],
	        src.[region_name],
	        src.[region_code],
	        src.[district],
	        src.[district_name],
	        src.[district_code],
	        src.[area],
	        src.[area_name],
	        src.[area_code],
	        src.[facility],
	        src.[facility_name],
	        src.[facility_code],
	        src.[cc_type],
	        src.[cc_type_code],
	        src.[budget_group],
	        src.[budget_year],
	        src.[op_nonop],
	        src.[origin],
	        src.[province],
	        src.[create_date],
	        src.[spud_date],
	        src.[rig_release_date],
	        src.[on_production_date],
	        src.[acquired_from],
	        src.[current_reserves_property],
	        src.[disposition_package],
	        src.[disposition_type],
	        src.[disposition_area],
	        src.[disposition_facility],
	        src.[disposed_flag],
	        src.[focus_area_flag],
	        src.[primary_product],
	        src.[cgu],
	        src.[working_interest_pct],
	        src.[year_end_reserves_property],
	        src.[unit_cc_num],
	        src.[unit_cc_name],
	        src.[survey_system_code],
	        src.[uwi],
	        src.[well_name] [uwi_desc],
	        src.[meridian],
	        src.[range],
	        src.[township],
	        src.[section],
	        src.[tax_pools],
	        src.[strat_unit_id],
	        src.[crstatus_desc],
	        src.[license_no],
	        src.[surf_location],
	        src.[tvd_depth],
	        src.[total_depth],
	        src.[zone_desc],
	        src.[deviation_flag],
	        src.[formatted_uwi],
	        src.[bottom_hole_latitude],
	        src.[bottom_hole_longitude],
	        src.[surface_latitude],
	        src.[surface_longitude],
	        src.[gas_shrinkage_factor],
	        src.[ngl_yield_factor],
	        src.[pvunit_completion_name],
	        src.[pvunit_name],
	        src.[pvunit_short_name],
	        src.[entity_source],
	        0 [is_cc_dim],
	        src.[cc_term_date],
	        1 [is_uwi],
	        src.[budget_year_group],
	        src.[origin_group],
	        src.[zone_play],
	        src.[routename],
	        src.[flownet_name],
	        src.[valnav_budget_year],
	        src.[valnav_budget_quarter],
	        src.[sales_disposition_point],
	        src.[last_production_date],
	        src.on_prod_date_accumap,
	        src.on_prod_data_source,	
	        src.inline_test_date,
	        src.qbyte_license,
	        src.surface_location,
	        src.Sask_Resource_Surcharge,
	        src.meter_station,
	        src.de_risk,
	        src.current_licensee,
	        src.original_licensee,
	        src.operator,
	        src.mode,
	        src.schematic_typical,
	        src.plant,
	        src.keyera_inlet
          FROM
		    [stage].[v_dim_source_entity_uwi_hierarchy_attributes] as src
          LEFT JOIN [data_mart].[t_dim_entity] as trg
            ON trg.entity_key = src.uwi
          WHERE
		    trg.entity_key IS NULL
		  
          UNION ALL

 		  SELECT
		    'UPDATE' Flag,
            src.uwi [entity_key],
	        src.[well_name] [entity_name],
	        src.[cost_centre],
	        src.[cost_centre_name],
	        src.[corp],
	        src.[corp_name],
	        src.[region],
	        src.[region_name],
	        src.[region_code],
	        src.[district],
	        src.[district_name],
	        src.[district_code],
	        src.[area],
	        src.[area_name],
	        src.[area_code],
	        src.[facility],
	        src.[facility_name],
	        src.[facility_code],
	        src.[cc_type],
	        src.[cc_type_code],
	        src.[budget_group],
	        src.[budget_year],
	        src.[op_nonop],
	        src.[origin],
	        src.[province],
	        src.[create_date],
	        src.[spud_date],
	        src.[rig_release_date],
	        src.[on_production_date],
	        src.[acquired_from],
	        src.[current_reserves_property],
	        src.[disposition_package],
	        src.[disposition_type],
	        src.[disposition_area],
	        src.[disposition_facility],
	        src.[disposed_flag],
	        src.[focus_area_flag],
	        src.[primary_product],
	        src.[cgu],
	        src.[working_interest_pct],
	        src.[year_end_reserves_property],
	        src.[unit_cc_num],
	        src.[unit_cc_name],
	        src.[survey_system_code],
	        src.[uwi],
	        src.[well_name] [uwi_desc],
	        src.[meridian],
	        src.[range],
	        src.[township],
	        src.[section],
	        src.[tax_pools],
	        src.[strat_unit_id],
	        src.[crstatus_desc],
	        src.[license_no],
	        src.[surf_location],
	        src.[tvd_depth],
	        src.[total_depth],
	        src.[zone_desc],
	        src.[deviation_flag],
	        src.[formatted_uwi],
	        src.[bottom_hole_latitude],
	        src.[bottom_hole_longitude],
	        src.[surface_latitude],
	        src.[surface_longitude],
	        src.[gas_shrinkage_factor],
	        src.[ngl_yield_factor],
	        src.[pvunit_completion_name],
	        src.[pvunit_name],
	        src.[pvunit_short_name],
	        src.[entity_source],
	        0 [is_cc_dim],
	        src.[cc_term_date],
	        1 [is_uwi],
	        src.[budget_year_group],
	        src.[origin_group],
	        src.[zone_play],
	        src.[routename],
	        src.[flownet_name],
	        src.[valnav_budget_year],
	        src.[valnav_budget_quarter],
	        src.[sales_disposition_point],
	        src.[last_production_date],
	        src.on_prod_date_accumap,
	        src.on_prod_data_source,	
	        src.inline_test_date,
	        src.qbyte_license,
	        src.surface_location,
	        src.Sask_Resource_Surcharge,
	        src.meter_station,
	        src.de_risk,
	        src.current_licensee,
	        src.original_licensee,
	        src.operator,
	        src.mode,
	        src.schematic_typical,
	        src.plant,
	        src.keyera_inlet    
         FROM
		   (
 		      SELECT
                src.uwi,
	            src.[well_name],
	            src.[cost_centre],
	            src.[cost_centre_name],
	            src.[corp],
	            src.[corp_name],
	            src.[region],
	            src.[region_name],
	            src.[region_code],
	            src.[district],
	            src.[district_name],
	            src.[district_code],
	            src.[area],
	            src.[area_name],
	            src.[area_code],
	            src.[facility],
	            src.[facility_name],
	            src.[facility_code],
	            src.[cc_type],
	            src.[cc_type_code],
	            src.[budget_group],
	            src.[budget_year],
	            src.[op_nonop],
	            src.[origin],
	            src.[province],
	            src.[create_date],
	            src.[spud_date],
	            src.[rig_release_date],
	            src.[on_production_date],
	            src.[acquired_from],
	            src.[current_reserves_property],
	            src.[disposition_package],
	            src.[disposition_type],
	            src.[disposition_area],
	            src.[disposition_facility],
	            src.[disposed_flag],
	            src.[focus_area_flag],
	            src.[primary_product],
	            src.[cgu],
	            src.[working_interest_pct],
	            src.[year_end_reserves_property],
	            src.[unit_cc_num],
	            src.[unit_cc_name],
	            src.[survey_system_code],
	            src.[meridian],
	            src.[range],
	            src.[township],
	            src.[section],
	            src.[tax_pools],
	            src.[strat_unit_id],
	            src.[crstatus_desc],
	            src.[license_no],
	            src.[surf_location],
	            src.[tvd_depth],
	            src.[total_depth],
	            src.[zone_desc],
	            src.[deviation_flag],
	            src.[formatted_uwi],
	            src.[bottom_hole_latitude],
	            src.[bottom_hole_longitude],
	            src.[surface_latitude],
	            src.[surface_longitude],
	            src.[gas_shrinkage_factor],
	            src.[ngl_yield_factor],
	            src.[pvunit_completion_name],
	            src.[pvunit_name],
	            src.[pvunit_short_name],
	            src.[entity_source],
	            src.[cc_term_date],
	            src.[budget_year_group],
	            src.[origin_group],
	            src.[zone_play],
	            src.[routename],
	            src.[flownet_name],
	            src.[valnav_budget_year],
	            src.[valnav_budget_quarter],
	            src.[sales_disposition_point],
	            src.[last_production_date],
	            src.on_prod_date_accumap,
	            src.on_prod_data_source,	
	            src.inline_test_date,
	            src.qbyte_license,
	            src.surface_location,
	            src.Sask_Resource_Surcharge,
	            src.meter_station,
	            src.de_risk,
	            src.current_licensee,
	            src.original_licensee,
	            src.operator,
	            src.mode,
	            src.schematic_typical,
	            src.plant,
	            src.keyera_inlet 
              FROM
		        [stage].[v_dim_source_entity_uwi_hierarchy_attributes] as src
              INNER JOIN [data_mart].[t_dim_entity] as trg
                ON trg.entity_key = src.uwi

              EXCEPT

 		      SELECT
                trg.[entity_key] uwi,
	            trg.[entity_name] [well_name],
	            trg.[cost_centre],
	            trg.[cost_centre_name],
	            trg.[corp],
	            trg.[corp_name],
	            trg.[region],
	            trg.[region_name],
	            trg.[region_code],
	            trg.[district],
	            trg.[district_name],
	            trg.[district_code],
	            trg.[area],
	            trg.[area_name],
	            trg.[area_code],
	            trg.[facility],
	            trg.[facility_name],
	            trg.[facility_code],
	            trg.[cc_type],
	            trg.[cc_type_code],
	            trg.[budget_group],
	            trg.[budget_year],
	            trg.[op_nonop],
	            trg.[origin],
	            trg.[province],
	            trg.[create_date],
	            trg.[spud_date],
	            trg.[rig_release_date],
	            trg.[on_production_date],
	            trg.[acquired_from],
	            trg.[current_reserves_property],
	            trg.[disposition_package],
	            trg.[disposition_type],
	            trg.[disposition_area],
	            trg.[disposition_facility],
	            trg.[disposed_flag],
	            trg.[focus_area_flag],
	            trg.[primary_product],
	            trg.[cgu],
	            trg.[working_interest_pct],
	            trg.[year_end_reserves_property],
	            trg.[unit_cc_num],
	            trg.[unit_cc_name],
	            trg.[survey_system_code],
	            trg.[meridian],
	            trg.[range],
	            trg.[township],
	            trg.[section],
	            trg.[tax_pools],
	            trg.[strat_unit_id],
	            trg.[crstatus_desc],
	            trg.[license_no],
	            trg.[surf_location],
	            trg.[tvd_depth],
	            trg.[total_depth],
	            trg.[zone_desc],
	            trg.[deviation_flag],
	            trg.[formatted_uwi],
	            trg.[bottom_hole_latitude],
	            trg.[bottom_hole_longitude],
	            trg.[surface_latitude],
	            trg.[surface_longitude],
	            trg.[gas_shrinkage_factor],
	            trg.[ngl_yield_factor],
	            trg.[pvunit_completion_name],
	            trg.[pvunit_name],
	            trg.[pvunit_short_name],
	            trg.[entity_source],
	            trg.[cc_term_date],
	            trg.[budget_year_group],
	            trg.[origin_group],
	            trg.[zone_play],
	            trg.[routename],
	            trg.[flownet_name],
	            trg.[valnav_budget_year],
	            trg.[valnav_budget_quarter],
	            trg.[sales_disposition_point],
	            trg.[last_production_date],
	            trg.on_prod_date_accumap,
	            trg.on_prod_data_source,	
	            trg.inline_test_date,
	            trg.qbyte_license,
	            trg.surface_location,
	            trg.Sask_Resource_Surcharge,
	            trg.meter_station,
	            trg.de_risk,
	            trg.current_licensee,
	            trg.original_licensee,
	            trg.operator,
	            trg.mode,
	            trg.schematic_typical,
	            trg.plant,
	            trg.keyera_inlet 
              FROM
		        [data_mart].[t_dim_entity] as trg
		   ) src

      INSERT INTO [data_mart].[t_dim_entity] 
	    (
           [entity_key],
	       [entity_name],
	       [cost_centre],
	       [cost_centre_name],
	       [corp],
	       [corp_name],
	       [region],
	       [region_name],
	       [region_code],
	       [district],
	       [district_name],
	       [district_code],
	       [area],
	       [area_name],
	       [area_code],
	       [facility],
	       [facility_name],
	       [facility_code],
	       [cc_type],
	       [cc_type_code],
	       [budget_group],
	       [budget_year],
	       [op_nonop],
	       [origin],
	       [province],
	       [create_date],
	       [spud_date],
	       [rig_release_date],
	       [on_production_date],
	       [acquired_from],
	       [current_reserves_property],
	       [disposition_package],
	       [disposition_type],
	       [disposition_area],
	       [disposition_facility],
	       [disposed_flag],
	       [focus_area_flag],
	       [primary_product],
	       [cgu],
	       [working_interest_pct],
	       [year_end_reserves_property],
	       [unit_cc_num],
	       [unit_cc_name],
	       [survey_system_code],
	       [uwi],
	       [uwi_desc],
	       [meridian],
	       [range],
	       [township],
	       [section],
	       [tax_pools],
	       [strat_unit_id],
	       [crstatus_desc],
	       [license_no],
	       [surf_location],
	       [tvd_depth],
	       [total_depth],
	       [zone_desc],
	       [deviation_flag],
	       [formatted_uwi],
	       [bottom_hole_latitude],
	       [bottom_hole_longitude],
	       [surface_latitude],
	       [surface_longitude],
	       [gas_shrinkage_factor],
	       [ngl_yield_factor],
	       [pvunit_completion_name],
	       [pvunit_name],
	       [pvunit_short_name],
	       [entity_source],
	       [is_cc_dim],
	       [cc_term_date],
	       [is_uwi],
	       [budget_year_group],
	       [origin_group],
	       [zone_play],
	       [routename],
	       [flownet_name],
	       [valnav_budget_year],
	       [valnav_budget_quarter],
	       [sales_disposition_point],
	       [last_production_date],
	       on_prod_date_accumap,
	       on_prod_data_source,	
	       inline_test_date,
	       qbyte_license,
	       surface_location,
	       Sask_Resource_Surcharge,
	       meter_station,
	       de_risk,
	       current_licensee,
	       original_licensee,
	       operator,
	       mode,
	       schematic_typical,
	       plant,
	       keyera_inlet		  
		)
        SELECT
          src.[entity_key],
	      src.[entity_name],
	      src.[cost_centre],
	      src.[cost_centre_name],
	      src.[corp],
	      src.[corp_name],
	      src.[region],
	      src.[region_name],
	      src.[region_code],
	      src.[district],
	      src.[district_name],
	      src.[district_code],
	      src.[area],
	      src.[area_name],
	      src.[area_code],
	      src.[facility],
	      src.[facility_name],
	      src.[facility_code],
	      src.[cc_type],
	      src.[cc_type_code],
	      src.[budget_group],
	      src.[budget_year],
	      src.[op_nonop],
	      src.[origin],
	      src.[province],
	      src.[create_date],
	      src.[spud_date],
	      src.[rig_release_date],
	      src.[on_production_date],
	      src.[acquired_from],
	      src.[current_reserves_property],
	      src.[disposition_package],
	      src.[disposition_type],
	      src.[disposition_area],
	      src.[disposition_facility],
	      src.[disposed_flag],
	      src.[focus_area_flag],
	      src.[primary_product],
	      src.[cgu],
	      src.[working_interest_pct],
	      src.[year_end_reserves_property],
	      src.[unit_cc_num],
	      src.[unit_cc_name],
	      src.[survey_system_code],
	      src.[uwi],
	      src.[uwi_desc],
	      src.[meridian],
	      src.[range],
	      src.[township],
	      src.[section],
	      src.[tax_pools],
	      src.[strat_unit_id],
	      src.[crstatus_desc],
	      src.[license_no],
	      src.[surf_location],
	      src.[tvd_depth],
	      src.[total_depth],
	      src.[zone_desc],
	      src.[deviation_flag],
	      src.[formatted_uwi],
	      src.[bottom_hole_latitude],
	      src.[bottom_hole_longitude],
	      src.[surface_latitude],
	      src.[surface_longitude],
	      src.[gas_shrinkage_factor],
	      src.[ngl_yield_factor],
	      src.[pvunit_completion_name],
	      src.[pvunit_name],
	      src.[pvunit_short_name],
	      src.[entity_source],
	      src.[is_cc_dim],
	      src.[cc_term_date],
	      src.[is_uwi],
	      src.[budget_year_group],
	      src.[origin_group],
	      src.[zone_play],
	      src.[routename],
	      src.[flownet_name],
	      src.[valnav_budget_year],
	      src.[valnav_budget_quarter],
	      src.[sales_disposition_point],
	      src.[last_production_date],
	      src.on_prod_date_accumap,
	      src.on_prod_data_source,	
	      src.inline_test_date,
	      src.qbyte_license,
	      src.surface_location,
	      src.Sask_Resource_Surcharge,
	      src.meter_station,
	      src.de_risk,
	      src.current_licensee,
	      src.original_licensee,
	      src.operator,
	      src.mode,
	      src.schematic_typical,
	      src.plant,
	      src.keyera_inlet
        FROM
		  #t_dim_entity_MERGE src
        WHERE 
		  Flag = 'NEW'

	  -------- ROW_COUNT
	  --DECLARE  @rowcnt INT
	  --EXEC [dbo].[LastRowCount] @rowcnt OUTPUT	

	  UPDATE [data_mart].[t_dim_entity]
      SET
		[data_mart].[t_dim_entity].[entity_name]				   =  UPD.[entity_name],
		[data_mart].[t_dim_entity].[cost_centre]				   =  UPD.[cost_centre],
		[data_mart].[t_dim_entity].[cost_centre_name]			   =  UPD.[cost_centre_name],
		[data_mart].[t_dim_entity].[corp]                          =  UPD.[corp],
		[data_mart].[t_dim_entity].[corp_name]                     =  UPD.[corp_name],
		[data_mart].[t_dim_entity].[region]                        =  UPD.[region],
		[data_mart].[t_dim_entity].[region_name]                   =  UPD.[region_name],
		[data_mart].[t_dim_entity].[region_code]                   =  UPD.[region_code],
		[data_mart].[t_dim_entity].[district]                      =  UPD.[district],
		[data_mart].[t_dim_entity].[district_name]                 =  UPD.[district_name],
		[data_mart].[t_dim_entity].[district_code]                 =  UPD.[district_code],
		[data_mart].[t_dim_entity].[area]                          =  UPD.[area],
		[data_mart].[t_dim_entity].[area_name]                     =  UPD.[area_name],
		[data_mart].[t_dim_entity].[area_code]                     =  UPD.[area_code],
		[data_mart].[t_dim_entity].[facility]                      =  UPD.[facility],
		[data_mart].[t_dim_entity].[facility_name]                 =  UPD.[facility_name],
		[data_mart].[t_dim_entity].[facility_code]                 =  UPD.[facility_code],
		[data_mart].[t_dim_entity].[cc_type]                       =  UPD.[cc_type],
		[data_mart].[t_dim_entity].[cc_type_code]                  =  UPD.[cc_type_code],
		[data_mart].[t_dim_entity].[budget_group]                  =  UPD.[budget_group],
		[data_mart].[t_dim_entity].[budget_year]                   =  UPD.[budget_year],
		[data_mart].[t_dim_entity].[op_nonop]                      =  UPD.[op_nonop],
		[data_mart].[t_dim_entity].[origin]                        =  UPD.[origin],
		[data_mart].[t_dim_entity].[province]                      =  UPD.[province],
		[data_mart].[t_dim_entity].[create_date]                   =  UPD.[create_date],
		[data_mart].[t_dim_entity].[spud_date]                     =  UPD.[spud_date],
		[data_mart].[t_dim_entity].[rig_release_date]              =  UPD.[rig_release_date],
		[data_mart].[t_dim_entity].[on_production_date]            =  UPD.[on_production_date],
		[data_mart].[t_dim_entity].[acquired_from]                 =  UPD.[acquired_from],
		[data_mart].[t_dim_entity].[current_reserves_property]     =  UPD.[current_reserves_property],
		[data_mart].[t_dim_entity].[disposition_package]           =  UPD.[disposition_package],
		[data_mart].[t_dim_entity].[disposition_type]              =  UPD.[disposition_type],
		[data_mart].[t_dim_entity].[disposition_area]              =  UPD.[disposition_area],
		[data_mart].[t_dim_entity].[disposition_facility]          =  UPD.[disposition_facility],
		[data_mart].[t_dim_entity].[disposed_flag]                 =  UPD.[disposed_flag],
		[data_mart].[t_dim_entity].[focus_area_flag]               =  UPD.[focus_area_flag],
		[data_mart].[t_dim_entity].[primary_product]               =  UPD.[primary_product],
		[data_mart].[t_dim_entity].[cgu]						   =  UPD.[cgu],
		[data_mart].[t_dim_entity].[working_interest_pct]          =  UPD.[working_interest_pct],
		[data_mart].[t_dim_entity].[year_end_reserves_property]    =  UPD.[year_end_reserves_property],
		[data_mart].[t_dim_entity].[unit_cc_num]                   =  UPD.[unit_cc_num],
		[data_mart].[t_dim_entity].[unit_cc_name]                  =  UPD.[unit_cc_name],
		[data_mart].[t_dim_entity].[survey_system_code]            =  UPD.[survey_system_code],
		[data_mart].[t_dim_entity].[uwi]						   =  UPD.[uwi],
		[data_mart].[t_dim_entity].[uwi_desc]					   =  UPD.[uwi_desc],
		[data_mart].[t_dim_entity].[meridian]                      =  UPD.[meridian],
		[data_mart].[t_dim_entity].[range]                         =  UPD.[range],
		[data_mart].[t_dim_entity].[township]                      =  UPD.[township],
		[data_mart].[t_dim_entity].[section]                       =  UPD.[section],
		[data_mart].[t_dim_entity].[tax_pools]					   =  UPD.[tax_pools],
		[data_mart].[t_dim_entity].[strat_unit_id]                 =  UPD.[strat_unit_id],
		[data_mart].[t_dim_entity].[crstatus_desc]                 =  UPD.[crstatus_desc],
		[data_mart].[t_dim_entity].[license_no]                    =  UPD.[license_no],
		[data_mart].[t_dim_entity].[surf_location]                 =  UPD.[surf_location],
		[data_mart].[t_dim_entity].[tvd_depth]                     =  UPD.[tvd_depth],
		[data_mart].[t_dim_entity].[total_depth]                   =  UPD.[total_depth],
		[data_mart].[t_dim_entity].[zone_desc]                     =  UPD.[zone_desc],
		[data_mart].[t_dim_entity].[deviation_flag]                =  UPD.[deviation_flag],
		[data_mart].[t_dim_entity].[formatted_uwi]                 =  UPD.[formatted_uwi],
		[data_mart].[t_dim_entity].[bottom_hole_latitude]          =  UPD.[bottom_hole_latitude],
		[data_mart].[t_dim_entity].[bottom_hole_longitude]         =  UPD.[bottom_hole_longitude],
		[data_mart].[t_dim_entity].[surface_latitude]			   =  UPD.[surface_latitude],
		[data_mart].[t_dim_entity].[surface_longitude]			   =  UPD.[surface_longitude],
		[data_mart].[t_dim_entity].[gas_shrinkage_factor]          =  UPD.[gas_shrinkage_factor],
		[data_mart].[t_dim_entity].[ngl_yield_factor]              =  UPD.[ngl_yield_factor],
		[data_mart].[t_dim_entity].[pvunit_completion_name]        =  UPD.[pvunit_completion_name],
		[data_mart].[t_dim_entity].[pvunit_name]                   =  UPD.[pvunit_name],
		[data_mart].[t_dim_entity].[pvunit_short_name]             =  UPD.[pvunit_short_name],
		[data_mart].[t_dim_entity].[entity_source]				   =  UPD.[entity_source],
		[data_mart].[t_dim_entity].[is_cc_dim]					   =  UPD.[is_cc_dim],
		[data_mart].[t_dim_entity].[cc_term_date]				   =  UPD.[cc_term_date],
		[data_mart].[t_dim_entity].[is_uwi]					  	   =  UPD.[is_uwi],
		[data_mart].[t_dim_entity].[budget_year_group]			   =  UPD.[budget_year_group],
		[data_mart].[t_dim_entity].[origin_group]				   =  UPD.[origin_group],
		[data_mart].[t_dim_entity].[zone_play]					   =  UPD.[zone_play],
		[data_mart].[t_dim_entity].[routename]					   =  UPD.[routename],
		[data_mart].[t_dim_entity].[flownet_name]				   =  UPD.[flownet_name],
		[data_mart].[t_dim_entity].[valnav_budget_year]			   =  UPD.[valnav_budget_year],
		[data_mart].[t_dim_entity].[valnav_budget_quarter]		   =  UPD.[valnav_budget_quarter],
		[data_mart].[t_dim_entity].[sales_disposition_point]	   =  UPD.[sales_disposition_point],
		[data_mart].[t_dim_entity].[last_production_date]		   =  UPD.[last_production_date],
		[data_mart].[t_dim_entity].on_prod_date_accumap			   =  UPD.on_prod_date_accumap,
		[data_mart].[t_dim_entity].on_prod_data_source			   =  UPD.on_prod_data_source,
		[data_mart].[t_dim_entity].inline_test_date				   =  UPD.inline_test_date,
		[data_mart].[t_dim_entity].qbyte_license				   =  UPD.qbyte_license,
		[data_mart].[t_dim_entity].surface_location				   =  UPD.surface_location,
		[data_mart].[t_dim_entity].Sask_Resource_Surcharge		   =  UPD.Sask_Resource_Surcharge,
		[data_mart].[t_dim_entity].meter_station				   =  UPD.meter_station,
		[data_mart].[t_dim_entity].de_risk						   =  UPD.de_risk,
		[data_mart].[t_dim_entity].current_licensee				   =  UPD.current_licensee,
		[data_mart].[t_dim_entity].original_licensee		       =  UPD.original_licensee,
		[data_mart].[t_dim_entity].operator					       =  UPD.operator,
		[data_mart].[t_dim_entity].mode							   =  UPD.mode,
		[data_mart].[t_dim_entity].schematic_typical			   =  UPD.schematic_typical,
		[data_mart].[t_dim_entity].plant						   =  UPD.plant,
		[data_mart].[t_dim_entity].keyera_inlet					   =  UPD.keyera_inlet
      FROM #t_dim_entity_MERGE UPD
      WHERE 
        [data_mart].[t_dim_entity].entity_key = UPD.entity_key AND
	    UPD.Flag = 'UPDATE'	
	 --	

	--COMMIT TRANSACTION
	--    
	--BEGIN TRANSACTION

	-- Align UWI/CC as Per Valnav UWI/CC 
      IF OBJECT_ID('tempdb..#UPDATE_MERGE') IS NOT NULL
        DROP TABLE #UPDATE_MERGE	 

      CREATE TABLE #UPDATE_MERGE WITH (DISTRIBUTION = ROUND_ROBIN)
        AS
	      SELECT 
		    ex.entity_key, 
			vdim.*
	      FROM
  	        [stage].v_exception_volumes_vs_valnav_uwi_cost_centre ex
	      LEFT OUTER JOIN
	        (
			   SELECT DISTINCT	
			     entity_name,
	             -- using first_value function as same uwi name can be attached to 2 different GUIDs...so a safeguard..DESC ensures null are not picked
				 FIRST_VALUE(cost_centre) OVER (PARTITION BY entity_name ORDER BY cost_centre DESC) cost_centre,					         
				 FIRST_VALUE(cost_centre_name) OVER (PARTITION BY entity_name ORDER BY cost_centre_name2 DESC) cost_centre_name,
				 FIRST_VALUE(corp) OVER (PARTITION BY entity_name ORDER BY corp DESC) corp,
				 FIRST_VALUE(corp_name) OVER (PARTITION BY entity_name ORDER BY corp_name2 DESC) corp_name,
				 FIRST_VALUE(region) OVER (PARTITION BY entity_name ORDER BY region DESC) region,
				 FIRST_VALUE(region_name) OVER (PARTITION BY entity_name ORDER BY region_name2 DESC) region_name,
				 FIRST_VALUE(district) OVER (PARTITION BY entity_name ORDER BY district DESC) district,
				 FIRST_VALUE(district_name) OVER (PARTITION BY entity_name ORDER BY district_name2 DESC) district_name,
				 FIRST_VALUE(area) OVER (PARTITION BY entity_name ORDER BY area DESC) area,
				 FIRST_VALUE(area_name) OVER (PARTITION BY entity_name ORDER BY area_name2 DESC) area_name,
				 FIRST_VALUE(facility) OVER (PARTITION BY entity_name ORDER BY facility DESC) facility,
				 FIRST_VALUE(facility_name) OVER (PARTITION BY entity_name ORDER BY facility_name2 DESC) facility_name,
				 FIRST_VALUE(cc_type) OVER (PARTITION BY entity_name ORDER BY cc_type DESC) cc_type,
				 FIRST_VALUE(budget_group) OVER (PARTITION BY entity_name ORDER BY budget_group DESC) budget_group,
				 FIRST_VALUE(op_nonop) OVER (PARTITION BY entity_name ORDER BY op_nonop DESC) op_nonop,
				 FIRST_VALUE(origin) OVER (PARTITION BY entity_name ORDER BY origin DESC) origin,
				 FIRST_VALUE(province) OVER (PARTITION BY entity_name ORDER BY province DESC) province,
				 FIRST_VALUE(create_date) OVER (PARTITION BY entity_name ORDER BY create_date DESC) create_date,
				 FIRST_VALUE(unit_cc_num) OVER (PARTITION BY entity_name ORDER BY unit_cc_num DESC) unit_cc_num,
				 FIRST_VALUE(unit_cc_name) OVER (PARTITION BY entity_name ORDER BY unit_cc_name2 DESC) unit_cc_name,
				 FIRST_VALUE(facility_code) OVER (PARTITION BY entity_name ORDER BY facility_code DESC) facility_code,
				 FIRST_VALUE(area_code) OVER (PARTITION BY entity_name ORDER BY area_code DESC) area_code,
				 FIRST_VALUE(district_code) OVER (PARTITION BY entity_name ORDER BY district_code DESC) district_code,
				 FIRST_VALUE(region_code) OVER (PARTITION BY entity_name ORDER BY region_code DESC) region_code,
				 FIRST_VALUE(cc_type_code) OVER (PARTITION BY entity_name ORDER BY cc_type_code DESC) cc_type_code,
				 FIRST_VALUE(valnav_budget_year) OVER (PARTITION BY entity_name ORDER BY valnav_budget_year DESC) valnav_budget_year,
				 FIRST_VALUE(cc_num_working_interest_pct) OVER (PARTITION BY entity_name ORDER BY cc_num_working_interest_pct DESC) cc_num_working_interest_pct,
				 FIRST_VALUE(entity_source) OVER (PARTITION BY entity_name ORDER BY entity_source DESC) entity_source,
				 FIRST_VALUE(cc_term_date) OVER (PARTITION BY entity_name ORDER BY cc_term_date DESC) cc_term_date,
				 FIRST_VALUE(budget_quarter) OVER (PARTITION BY entity_name ORDER BY budget_quarter DESC) budget_quarter,
				 FIRST_VALUE(budget_year) OVER (PARTITION BY entity_name ORDER BY budget_year DESC) budget_year,
				 FIRST_VALUE(budget_year_group) OVER (PARTITION BY entity_name ORDER BY budget_year_group DESC) budget_year_group,
				 FIRST_VALUE(nra) OVER (PARTITION BY entity_name ORDER BY nra DESC) nra
               FROM 
		         (
				    SELECT ve.*, 
		              --had use substring due to this error:
		              -- ORDER BY list of RANGE window frame has total size of 1000 bytes. Largest size supported is 900 bytes.
		              --
			          SUBSTRING(cost_centre_name, 1, 900) cost_centre_name2,
			          SUBSTRING(corp_name, 1, 900) corp_name2,
			          SUBSTRING(region_name, 1, 900) region_name2,
			          SUBSTRING(district_name, 1, 900) district_name2,
			          SUBSTRING(area_name, 1, 900) area_name2,
			          SUBSTRING(facility_name, 1, 900) facility_name2,
			          SUBSTRING(unit_cc_name, 1, 900) unit_cc_name2
		            FROM 
					  [stage].[v_dim_source_entity_valnav_entities] ve
		         ) ve					
	        ) vdim
	        ON vdim.entity_name = ex.entity_key
	      WHERE vdim.area_code is not null
	    
	  UPDATE [data_mart].t_dim_entity
	  SET 
	    cost_centre					    = x.cost_centre,
        cost_centre_name				= x.cost_centre_name,
	    corp							= x.corp,
	    corp_name						= x.corp_name,
	    region							= x.region,
	    region_name					    = x.region_name,
	    district						= x.district,
	    district_name					= x.district_name,
	    area							= x.area,
	    area_name						= x.area_name,
	    facility						= x.facility,
	    facility_name					= x.facility_name,
	    cc_type						    = x.cc_type,
	    budget_group					= x.budget_group,
	    op_nonop						= x.op_nonop,
	    origin							= x.origin,
	    province						= x.province,
	    create_date					    = x.create_date,
	    unit_cc_num					    = x.unit_cc_num,
	    unit_cc_name					= x.unit_cc_name,
	    facility_code					= x.facility_code,
	    area_code						= x.area_code,
	    district_code					= x.district_code,
	    region_code					    = x.region_code,
	    cc_type_code					= x.cc_type_code,
	    valnav_budget_year				= x.valnav_budget_year,
	    cc_num_working_interest_pct	    = x.cc_num_working_interest_pct,
	    entity_source					= x.entity_source,
	    cc_term_date					= x.cc_term_date,
	    budget_quarter					= x.budget_quarter,
	    budget_year					    = x.budget_year,
	    budget_year_group				= x.budget_year_group,
	    nra							    = x.nra,
	    valnav_budget_quarter			= x.budget_quarter
	  FROM
	    #UPDATE_MERGE x
	  WHERE 
	    x.entity_key = [data_mart].[t_dim_entity].entity_key AND
	    is_uwi = '1';

   -- COMMIT TRANSACTION
   
    -- update / re-align 'acquired from' attribute after cc change from valnav exceptions
   UPDATE [data_mart].t_dim_entity 
   SET acquired_from = cc.acquired_from
   FROM [stage].[t_cost_centre_hierarchy] cc 
   JOIN [stage].v_exception_volumes_vs_valnav_uwi_cost_centre ex
   ON cc.cost_centre_id = ex.volumes_cost_centre
   WHERE [data_mart].t_dim_entity.cost_centre = cc.cost_centre_id
   AND is_uwi = '1'
   AND cc.acquired_from is not null
   ;

	IF @complete_rebuild_flag = 'Y'
	  BEGIN

	  --  BEGIN TRANSACTION

		  INSERT INTO [data_mart].[t_dim_entity]
            (
			  [entity_key]
              ,[entity_name]
		      ,[is_cc_dim]
		      ,[is_uwi]
		      ,[is_valnav]
            )
		  VALUES
            (
			  '-2'
              ,'Missing'
		      ,1
		      ,1
		      ,1
			);

		  INSERT INTO [data_mart].[t_dim_entity]
		   ([entity_key]
           ,[entity_name]
		   ,[is_cc_dim]
		   ,[is_uwi]
		   ,[is_valnav]
				 )
			VALUES
           ('-1'
           ,'Unknown'
		   ,1
		   ,1
		   ,1);

		 --  COMMIT TRANSACTION

		  END         
    SELECT 1
  END TRY
  
  BEGIN CATCH
        
       -- Grab error information from SQL functions
		DECLARE @ErrorSeverity INT	= ERROR_SEVERITY()
				,@ErrorNumber INT	= ERROR_NUMBER()
				,@ErrorMessage nvarchar(4000)	= ERROR_MESSAGE()
				,@ErrorState INT = ERROR_STATE()
				--,@ErrorLine  INT = ERROR_LINE()
				,@ErrorProc nvarchar(200) = ERROR_PROCEDURE()
				
		-- If the error renders the transaction as uncommittable or we have open transactions, rollback
		--IF @@TRANCOUNT > 0
		--BEGIN
		--	ROLLBACK TRANSACTION
		--END
		RAISERROR (@ErrorMessage , @ErrorSeverity, @ErrorState, @ErrorNumber)      

  END CATCH
 -- RETURN @@ERROR
END