CREATE PROC [data_mart].[build_dim_entity_valnav] @complete_rebuild_flag [varchar](1) AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
  SET NOCOUNT ON;

  IF @complete_rebuild_flag IS NULL OR @complete_rebuild_flag = ''
    SET @complete_rebuild_flag = 'N'

  BEGIN TRY	

    IF @complete_rebuild_flag = 'Y'
	   
	BEGIN
		  
	 -- BEGIN TRANSACTION
	  
	  DELETE
	  FROM [data_mart].[t_dim_entity]
	  WHERE is_valnav=1 and entity_key not in ('-1','-2');
	  
	 -- COMMIT TRANSACTION
	  
	 -- BEGIN TRANSACTION


			 INSERT INTO [data_mart].[t_dim_entity]
			    (entity_key,
					entity_name,
					cost_centre,
					cost_centre_name,
					corp,
					corp_name,
					region,
					region_name,
					region_code,
					area,
					area_name,
					area_code,
					facility,
					facility_name,
					facility_code,
					cc_type,
					budget_group,
					budget_year,
					op_nonop,
					origin,
					province,
					create_date,
					spud_date,
					rig_release_date,
					on_production_date,
					acquired_from,
					current_reserves_property,
					disposition_package,
					disposition_type,
					disposition_area,
					disposition_facility,
					disposed_flag,
					focus_area_flag,
					primary_product,
					cgu,
					working_interest_pct,
					year_end_reserves_property,
					unit_cc_num,
					unit_cc_name,
					survey_system_code,
					uwi,
					uwi_desc,
					meridian,
					range,
					township,
					section,
					tax_pools,
					strat_unit_id,
					crstatus_desc,
					license_no,
					surf_location,
					tvd_depth,
					total_depth,
					zone_desc,
					deviation_flag,
					formatted_uwi,
					bottom_hole_latitude,
					bottom_hole_longitude,
					surface_latitude,
					surface_longitude,
					gas_shrinkage_factor,
					ngl_yield_factor,
					pvunit_completion_name,
					pvunit_name,
					pvunit_short_name,
					entity_source,
					is_cc_dim,
					cc_term_date,
					chance_of_success,
					budget_quarter,
					capital_group,
					capital_type,
					de_risk,
					depth_gci,
					drill_days,
					nra,
					reserve_realized_date,
					royalty_income_interest,
					well_direction,
					zone_play,
					is_valnav,
					is_uwi,
					budget_year_group,
					origin_group,
					cc_type_code,
					valnav_budget_year,
					cc_num_working_interest_pct,
					lateral_length,
					segment_start_date,
					valnav_budget_quarter,
					last_production_date,
					completion_type,
					total_proppant_placed,
					c_star,
					production_category,
					incentive_type,
					Meter_Station,
					type_curve_kpi,
					royalty_type,
					first_prod_month,
					group1,
					group2,
					group3,
					group4,
					group5,
					group6,
					group7,
					group8,
					group9,
					group10,
					completion_month,
					plant,
					keyera_inlet
			 )
			 SELECT entity_key,
					entity_name,
					cost_centre,
					cost_centre_name,
					corp,
					corp_name,
					region,
					region_name,
					region_code,
					area,
					area_name,
					area_code,
					facility,
					facility_name,
					facility_code,
					cc_type,
					budget_group,
					budget_year,
					op_nonop,
					origin,
					province,
					create_date,
					spud_date,
					NULL rig_release_date,
					on_production_date,
					acquired_from,
					current_reserve_property,
					disposition_package,
					disposition_type,
					disposition_area,
					disposition_facility,
					disposed_flag,
					focus_area_flag,
					primary_product,
					cgu,
					working_interest,
					year_end_reserve_property,
					unit_cc_num,
					unit_cc_name,
					survey_system_code,
					uwi,
					uwi_desc,
					meridian,
					range,
					township,
					section,
					tax_pools,
					strat_unit_id,
					crstatus_desc,
					license_no,
					surf_location,
					tvd_depth,
					total_depth,
					zone_desc,
					deviation_flag,
					formatted_uwi,
					bottom_hole_latitude,
					bottom_hole_longitude,
					surface_latitude,
					surface_longitude,
					gas_shrinkage_factor,
					ngl_yield_factor,
					pvunit_completion_name,
					pvunit_name,
					pvunit_short_name,
					entity_source,
					is_cc_dim,
					cc_term_date,
					chance_of_success,
					budget_quarter,
					capital_group,
					capital_type,
					de_risk,
					depth_gci,
					drill_days,
					nra,
					reserve_realized_date,
					royalty_income_interest,
					well_direction,
					zone_play,
					is_valnav,
					0 is_uwi,
					budget_year_group,
					origin_group,
					cc_type_code,
					valnav_budget_year,
					cc_num_working_interest_pct,
					null lateral_length,
					null segment_start_date,
					budget_quarter valnav_budget_quarter,
					last_production_date,
					null completion_type,
					null total_proppant_placed,
					null c_star,
					null production_category,
					null incentive_type,
					null Meter_Station,
					null type_curve_kpi,
					null royalty_type,
					null first_prod_month,
					null group1,
					null group2,
					null group3,
					null group4,
					null group5,
					null group6,
					null group7,
					null group8,
					null group9,
					null group10,
					null completion_month,
					null plant,
					null keyera_inlet
		    FROM [stage].[v_dim_source_entity_valnav_history_entities];

	 -- COMMIT TRANSACTION 

	END

	--BEGIN TRANSACTION
      IF OBJECT_ID('tempdb..#t_dim_entity_MERGE') IS NULL
	    CREATE TABLE #t_dim_entity_MERGE   --DROP TABLE #t_dim_entity_MERGE
		  (
		    [Flag] [varchar](10),
			[entity_key] [varchar](500) NULL,
			[entity_name] [varchar](1000) NULL,
			[cost_centre] [varchar](50) NULL,
			[cost_centre_name] [varchar](1000) NULL,
			[corp] [varchar](50) NULL,
			[corp_name] [varchar](1000) NULL,
			[region] [varchar](50) NULL,
			[region_name] [varchar](1000) NULL,
			[district] [varchar](50) NULL,
			[district_name] [varchar](1000) NULL,
			[area] [varchar](50) NULL,
			[area_name] [varchar](1000) NULL,
			[facility] [varchar](50) NULL,
			[facility_name] [varchar](1000) NULL,
			[cc_type] [varchar](50) NULL,
			[budget_group] [varchar](200) NULL,
			[budget_year] [varchar](100) NULL,
			[op_nonop] [varchar](10) NULL,
			[origin] [varchar](100) NULL,
			[province] [varchar](50) NULL,
			[create_date] [varchar](50) NULL,
			[spud_date] [varchar](50) NULL,
			[rig_release_date] [varchar](50) NULL,
			[on_production_date] [varchar](50) NULL,
			[acquired_from] [varchar](100) NULL,
			[current_reserves_property] [varchar](200) NULL,
			[disposition_package] [varchar](200) NULL,
			[disposition_type] [varchar](200) NULL,
			[disposition_area] [varchar](200) NULL,
			[disposition_facility] [varchar](200) NULL,
			[disposed_flag] [varchar](20) NULL,
			[focus_area_flag] [varchar](10) NULL,
			[primary_product] [varchar](50) NULL,
			[cgu] [varchar](100) NULL,
			[working_interest_pct] [numeric](38, 11) NULL,
			--[year_end_reserves_property] [varchar](200) NULL,
			[unit_cc_num] [varchar](50) NULL,
			[unit_cc_name] [varchar](1000) NULL,
			[survey_system_code] [varchar](50) NULL,
			[uwi] [varchar](200) NULL,
			[uwi_desc] [varchar](500) NULL,
			[meridian] [varchar](50) NULL,
			[range] [varchar](50) NULL,
			[township] [varchar](50) NULL,
			[section] [varchar](50) NULL,
			[tax_pools] [varchar](100) NULL,
			[strat_unit_id] [varchar](50) NULL,
			[crstatus_desc] [varchar](100) NULL,
			[license_no] [varchar](50) NULL,
			[surf_location] [varchar](50) NULL,
			[tvd_depth] [numeric](10, 2) NULL,
			[total_depth] [numeric](10, 2) NULL,
			[zone_desc] [varchar](100) NULL,
			[deviation_flag] [varchar](100) NULL,
			[formatted_uwi] [varchar](100) NULL,
			[bottom_hole_latitude] [numeric](12, 7) NULL,
			[bottom_hole_longitude] [numeric](12, 7) NULL,
			[surface_latitude] [numeric](12, 7) NULL,
			[surface_longitude] [numeric](12, 7) NULL,
			[gas_shrinkage_factor] [numeric](12, 2) NULL,
			[ngl_yield_factor] [numeric](12, 2) NULL,
			[pvunit_completion_name] [varchar](100) NULL,
			[pvunit_name] [varchar](100) NULL,
			[pvunit_short_name] [varchar](100) NULL,
			[entity_source] [varchar](50) NULL,
			[is_cc_dim] [int] NULL,
			[cc_term_date] [varchar](50) NULL,
			[chance_of_success] [numeric](18, 11) NULL,
			[budget_quarter] [varchar](100) NULL,
			[capital_group] [varchar](100) NULL,
			[capital_type] [varchar](100) NULL,
			[de_risk] [varchar](100) NULL,
			[depth_gci] [numeric](38, 11) NULL,
			[drill_days] [varchar](100) NULL,
			[nra] [varchar](100) NULL,
			[reserve_realized_date] [varchar](50) NULL,
			[royalty_income_interest] [numeric](38, 11) NULL,
			[well_direction] [varchar](100) NULL,
			[zone_play] [varchar](100) NULL,
			[is_valnav] [int] NULL,
		--	[is_uwi] [int] NULL,
		--	[region_code] [varchar](100) NULL,
		--	[district_code] [varchar](100) NULL,
		--	[area_code] [varchar](100) NULL,
		--	[facility_code] [varchar](100) NULL,
			[budget_year_group] [varchar](50) NULL,
			[origin_group] [varchar](100) NULL,
			[cc_type_code] [varchar](50) NULL,
			[valnav_budget_year] [varchar](100) NULL,
			[cc_num_working_interest_pct] [numeric](38, 11) NULL,
		--	[routename] [varchar](100) NULL,
		--	[flownet_name] [varchar](100) NULL,
			[lateral_length] [numeric](18, 11) NULL,
			[segment_start_date] [varchar](50) NULL,
			[valnav_budget_quarter] [varchar](100) NULL,
			--[gca_fcc] [varchar](100) NULL,
			--[metrix_control_group] [varchar](50) NULL,
			--[sales_disposition_point] [varchar](100) NULL,
			[last_production_date] [varchar](50) NULL,
			[completion_type] [varchar](50) NULL,
			[total_proppant_placed] [float] NULL,
			[c_star] [float] NULL,
			[production_category] [varchar](100) NULL,
			[incentive_type] [varchar](100) NULL,
			[Meter_Station] [varchar](100) NULL,
			--[on_prod_date_accumap] [varchar](50) NULL,
			--[on_prod_data_source] [varchar](50) NULL,
			--[inline_test_date] [varchar](50) NULL,
			[type_curve_kpi] [varchar](100) NULL,
			[royalty_type] [varchar](100) NULL,
			[first_prod_month] [varchar](50) NULL,
			--[qbyte_license] [varchar](50) NULL,
			--[surface_location] [varchar](50) NULL,
			--[Sask_Resource_Surcharge] [varchar](50) NULL,
			--[current_licensee] [varchar](100) NULL,
			--[original_licensee] [varchar](500) NULL,
			--[operator] [varchar](100) NULL,
			--[mode] [varchar](50) NULL,
			[group1] [varchar](100) NULL,
			[group2] [varchar](100) NULL,
			[group3] [varchar](100) NULL,
			[group4] [varchar](100) NULL,
			[group5] [varchar](100) NULL,
			[group6] [varchar](100) NULL,
			[group7] [varchar](100) NULL,
			[group8] [varchar](100) NULL,
			[group9] [varchar](100) NULL,
			[group10] [varchar](100) NULL,
			[completion_month] [varchar](50) NULL,
		--	[schematic_typical] [varchar](50) NULL,
			[plant] [varchar](100) NULL,
			[keyera_inlet] [varchar](100) NULL
		  )
        WITH
          (
        	DISTRIBUTION = ROUND_ROBIN,
        	CLUSTERED COLUMNSTORE INDEX
          )
      ELSE
	    TRUNCATE TABLE #t_dim_entity_MERGE

      -- NEW records		   
      INSERT INTO #t_dim_entity_MERGE
      SELECT 
  	    --CASE
  	    --  WHEN Target.entity_key IS NULL THEN 'NEW'
  	    --  WHEN Target.entity_key IS NOT NULL THEN 'UPDATE'
  	    --ELSE
  	    --  'EXISTING'
  	    --END Flag,
		'NEW' Flag,
		Source.[entity_key],
		Source.[entity_name],
		Source.[cost_centre],
		Source.[cost_centre_name],
		Source.[corp],
		Source.[corp_name],
		Source.[region],
		Source.[region_name],
	--	Source.[region_code],
		Source.[district],
		Source.[district_name],
	--	Source.[district_code],
		Source.[area],
		Source.[area_name],
		--Source.[area_code],
		Source.[facility],
		Source.[facility_name],
		--Source.[facility_code],
		Source.[cc_type],
		Source.[budget_group],
		Source.[budget_year],
		Source.[op_nonop],
		Source.[origin],
		Source.[province],
		Source.[create_date],
		Source.[spud_date],
		Source.[rig_release_date],
		Source.[on_production_date],
		Source.[acquired_from],
		Source.[current_reserves_property],
		Source.[disposition_package],
		Source.[disposition_type],
		Source.[disposition_area],
		Source.[disposition_facility],
		Source.[disposed_flag],
		Source.[focus_area_flag],
		Source.[primary_product],
		Source.[cgu],
		Source.[working_interest],
		--Source.[year_end_reserves_property],
		Source.[unit_cc_num],
		Source.[unit_cc_name],
		Source.[survey_system_code],
		Source.[uwi],
		Source.[uwi_desc],
		Source.[meridian],
		Source.[range],
		Source.[township],
		Source.[section],
		Source.[tax_pools],
		Source.[strat_unit_id],
		Source.[crstatus_desc],
		Source.[license_no],
		Source.[surf_location],
		Source.[tvd_depth],
		Source.[total_depth],
		Source.[zone_desc],
		Source.[deviation_flag],
		Source.[formatted_uwi],
		Source.[bottom_hole_latitude],
		Source.[bottom_hole_longitude],
		Source.[surface_latitude],
		Source.[surface_longitude],
		Source.[gas_shrinkage_factor],
		Source.[ngl_yield_factor],
		Source.[pvunit_completion_name],
		Source.[pvunit_name],
		Source.[pvunit_short_name],
		Source.[entity_source],
		0 [is_cc_dim],
		Source.[cc_term_date],
		Source.[chance_of_success],
		Source.[budget_quarter],
		Source.[capital_group],
		Source.[capital_type],
		Source.[de_risk],
		Source.[depth_gci],
		Source.[drill_days],
		Source.[nra],
		Source.[reserve_realized_date],
		Source.[royalty_income_interest],
		Source.[well_direction],
		Source.[zone_play],
		Source.[is_valnav],
		Source.[budget_year_group],
		Source.[origin_group],
		Source.[cc_type_code],
		Source.[valnav_budget_year],
		Source.[cc_num_working_interest_pct],
		Source.[lateral_length],
		Source.[segment_start_date],
		Source.[budget_quarter], --valnav_budget_quarter
		Source.[last_production_date],
		Source.completion_type,
		Source.total_proppant_placed,
		Source.c_star,
		Source.production_category,
		Source.incentive_type,
		Source.Meter_Station,
		Source.type_curve_kpi,
		Source.royalty_type,
		Source.first_prod_month,
		Source.group1,
		Source.group2,
		Source.group3,
		Source.group4,
		Source.group5,
		Source.group6,
		Source.group7,
		Source.group8,
		Source.group9,
		Source.group10,
		Source.completion_month,
		Source.plant,
		Source.keyera_inlet
      FROM [stage].[v_dim_source_entity_valnav_entities] Source
      LEFT JOIN [data_mart].[t_dim_entity] Target
  	    ON Source.entity_key = Target.entity_key
      WHERE 
	    Target.entity_key IS NULL


      -- UPDATED RECORDS
      INSERT INTO #t_dim_entity_MERGE
      SELECT 
		'UPDATE' Flag,
		Source.[entity_key],
		Source.[entity_name],
		Source.[cost_centre],
		Source.[cost_centre_name],
		Source.[corp],
		Source.[corp_name],
		Source.[region],
		Source.[region_name],
	--	Source.[region_code],
		Source.[district],
		Source.[district_name],
	--	Source.[district_code],
		Source.[area],
		Source.[area_name],
		--Source.[area_code],
		Source.[facility],
		Source.[facility_name],
		--Source.[facility_code],
		Source.[cc_type],
		Source.[budget_group],
		Source.[budget_year],
		Source.[op_nonop],
		Source.[origin],
		Source.[province],
		Source.[create_date],
		Source.[spud_date],
		Source.[rig_release_date],
		Source.[on_production_date],
		Source.[acquired_from],
		Source.[current_reserves_property],
		Source.[disposition_package],
		Source.[disposition_type],
		Source.[disposition_area],
		Source.[disposition_facility],
		Source.[disposed_flag],
		Source.[focus_area_flag],
		Source.[primary_product],
		Source.[cgu],
		Source.[working_interest],
		--Source.[year_end_reserves_property],
		Source.[unit_cc_num],
		Source.[unit_cc_name],
		Source.[survey_system_code],
		Source.[uwi],
		Source.[uwi_desc],
		Source.[meridian],
		Source.[range],
		Source.[township],
		Source.[section],
		Source.[tax_pools],
		Source.[strat_unit_id],
		Source.[crstatus_desc],
		Source.[license_no],
		Source.[surf_location],
		Source.[tvd_depth],
		Source.[total_depth],
		Source.[zone_desc],
		Source.[deviation_flag],
		Source.[formatted_uwi],
		Source.[bottom_hole_latitude],
		Source.[bottom_hole_longitude],
		Source.[surface_latitude],
		Source.[surface_longitude],
		Source.[gas_shrinkage_factor],
		Source.[ngl_yield_factor],
		Source.[pvunit_completion_name],
		Source.[pvunit_name],
		Source.[pvunit_short_name],
		Source.[entity_source],
		0 [is_cc_dim],
		Source.[cc_term_date],
		Source.[chance_of_success],
		Source.[budget_quarter],
		Source.[capital_group],
		Source.[capital_type],
		Source.[de_risk],
		Source.[depth_gci],
		Source.[drill_days],
		Source.[nra],
		Source.[reserve_realized_date],
		Source.[royalty_income_interest],
		Source.[well_direction],
		Source.[zone_play],
		Source.[is_valnav],
		Source.[budget_year_group],
		Source.[origin_group],
		Source.[cc_type_code],
		Source.[valnav_budget_year],
		Source.[cc_num_working_interest_pct],
		Source.[lateral_length],
		Source.[segment_start_date],
		Source.[budget_quarter] valnav_budget_quarter, --valnav_budget_quarter
		Source.[last_production_date],
		Source.completion_type,
		Source.total_proppant_placed,
		Source.c_star,
		Source.production_category,
		Source.incentive_type,
		Source.Meter_Station,
		Source.type_curve_kpi,
		Source.royalty_type,
		Source.first_prod_month,
		Source.group1,
		Source.group2,
		Source.group3,
		Source.group4,
		Source.group5,
		Source.group6,
		Source.group7,
		Source.group8,
		Source.group9,
		Source.group10,
		Source.completion_month,
		Source.plant,
		Source.keyera_inlet
      FROM [stage].[v_dim_source_entity_valnav_entities] Source
      INNER JOIN [data_mart].[t_dim_entity] Target
  	    ON Source.entity_key = Target.entity_key
	  
      EXCEPT
	  
      SELECT 
		'UPDATE' Flag,
		Source.[entity_key],
		Source.[entity_name],
		Source.[cost_centre],
		Source.[cost_centre_name],
		Source.[corp],
		Source.[corp_name],
		Source.[region],
		Source.[region_name],
	--	Source.[region_code],
		Source.[district],
		Source.[district_name],
	--	Source.[district_code],
		Source.[area],
		Source.[area_name],
		--Source.[area_code],
		Source.[facility],
		Source.[facility_name],
		--Source.[facility_code],
		Source.[cc_type],
		Source.[budget_group],
		Source.[budget_year],
		Source.[op_nonop],
		Source.[origin],
		Source.[province],
		Source.[create_date],
		Source.[spud_date],
		Source.[rig_release_date],
		Source.[on_production_date],
		Source.[acquired_from],
		Source.[current_reserves_property],
		Source.[disposition_package],
		Source.[disposition_type],
		Source.[disposition_area],
		Source.[disposition_facility],
		Source.[disposed_flag],
		Source.[focus_area_flag],
		Source.[primary_product],
		Source.[cgu],
		Source.[working_interest_pct],
		--Source.[year_end_reserves_property],
		Source.[unit_cc_num],
		Source.[unit_cc_name],
		Source.[survey_system_code],
		Source.[uwi],
		Source.[uwi_desc],
		Source.[meridian],
		Source.[range],
		Source.[township],
		Source.[section],
		Source.[tax_pools],
		Source.[strat_unit_id],
		Source.[crstatus_desc],
		Source.[license_no],
		Source.[surf_location],
		Source.[tvd_depth],
		Source.[total_depth],
		Source.[zone_desc],
		Source.[deviation_flag],
		Source.[formatted_uwi],
		Source.[bottom_hole_latitude],
		Source.[bottom_hole_longitude],
		Source.[surface_latitude],
		Source.[surface_longitude],
		Source.[gas_shrinkage_factor],
		Source.[ngl_yield_factor],
		Source.[pvunit_completion_name],
		Source.[pvunit_name],
		Source.[pvunit_short_name],
		Source.[entity_source],
		0 [is_cc_dim],
		Source.[cc_term_date],
		Source.[chance_of_success],
		Source.[budget_quarter],
		Source.[capital_group],
		Source.[capital_type],
		Source.[de_risk],
		Source.[depth_gci],
		Source.[drill_days],
		Source.[nra],
		Source.[reserve_realized_date],
		Source.[royalty_income_interest],
		Source.[well_direction],
		Source.[zone_play],
		Source.[is_valnav],
		Source.[budget_year_group],
		Source.[origin_group],
		Source.[cc_type_code],
		Source.[valnav_budget_year],
		Source.[cc_num_working_interest_pct],
		Source.[lateral_length],
		Source.[segment_start_date],
		Source.[budget_quarter] valnav_budget_quarter, --valnav_budget_quarter
		Source.[last_production_date],
		Source.completion_type,
		Source.total_proppant_placed,
		Source.c_star,
		Source.production_category,
		Source.incentive_type,
		Source.Meter_Station,
		Source.type_curve_kpi,
		Source.royalty_type,
		Source.first_prod_month,
		Source.group1,
		Source.group2,
		Source.group3,
		Source.group4,
		Source.group5,
		Source.group6,
		Source.group7,
		Source.group8,
		Source.group9,
		Source.group10,
		Source.completion_month,
		Source.plant,
		Source.keyera_inlet
      FROM [data_mart].[t_dim_entity] Source

	  INSERT INTO [data_mart].[t_dim_entity]
	    (
		 -- [Flag],
		 [entity_key],
		 [entity_name],
		 [cost_centre],
		 [cost_centre_name],
		 [corp],
		 [corp_name],
		 [region],
		 [region_name],
		 [district],
		 [district_name],
		 [area],
		 [area_name],
		 [facility],
		 [facility_name],
		 [cc_type],
		 [budget_group],
		 [budget_year],
		 [op_nonop],
		 [origin],
		 [province],
		 [create_date],
		 [spud_date],
		 [rig_release_date],
		 [on_production_date],
		 [acquired_from],
		 [current_reserves_property],
		 [disposition_package],
		 [disposition_type],
		 [disposition_area],
		 [disposition_facility],
		 [disposed_flag],
		 [focus_area_flag],
		 [primary_product],
		 [cgu],
		 [working_interest_pct],
		 [unit_cc_num],
		 [unit_cc_name],
		 [survey_system_code],
		 [uwi],
		 [uwi_desc],
		 [meridian],
		 [range],
		 [township],
		 [section],
		 [tax_pools],
		 [strat_unit_id],
		 [crstatus_desc],
		 [license_no],
		 [surf_location],
		 [tvd_depth],
		 [total_depth],
		 [zone_desc],
		 [deviation_flag],
		 [formatted_uwi],
		 [bottom_hole_latitude],
		 [bottom_hole_longitude],
		 [surface_latitude],
		 [surface_longitude],
		 [gas_shrinkage_factor],
		 [ngl_yield_factor],
		 [pvunit_completion_name],
		 [pvunit_name],
		 [pvunit_short_name],
		 [entity_source],
		 [is_cc_dim],
		 [cc_term_date],
		 [chance_of_success],
		 [budget_quarter],
		 [capital_group],
		 [capital_type],
		 [de_risk],
		 [depth_gci],
		 [drill_days],
		 [nra],
		 [reserve_realized_date],
		 [royalty_income_interest],
		 [well_direction],
		 [zone_play],
		 [is_valnav],
		 [budget_year_group],
		 [origin_group],
		 [cc_type_code],
		 [valnav_budget_year],
		 [cc_num_working_interest_pct],
		 [lateral_length],
		 [segment_start_date],
		 [valnav_budget_quarter],
		 [last_production_date],
		 [completion_type],
		 [total_proppant_placed],
		 [c_star],
		 [production_category],
		 [incentive_type],
		 [Meter_Station],
		 [type_curve_kpi],
		 [royalty_type],
		 [first_prod_month],
		 [group1],
		 [group2],
		 [group3],
		 [group4],
		 [group5],
		 [group6],
		 [group7],
		 [group8],
		 [group9],
		 [group10],
		 [completion_month],
		 [plant],
		 [keyera_inlet]
	    )
      SELECT
	    --  [Flag],
	    [entity_key],
	    [entity_name],
	    [cost_centre],
	    [cost_centre_name],
	    [corp],
	    [corp_name],
	    [region],
	    [region_name],
	    [district],
	    [district_name],
	    [area],
	    [area_name],
	    [facility],
	    [facility_name],
	    [cc_type],
	    [budget_group],
	    [budget_year],
	    [op_nonop],
	    [origin],
	    [province],
	    [create_date],
	    [spud_date],
	    [rig_release_date],
	    [on_production_date],
	    [acquired_from],
	    [current_reserves_property],
	    [disposition_package],
	    [disposition_type],
	    [disposition_area],
	    [disposition_facility],
	    [disposed_flag],
	    [focus_area_flag],
	    [primary_product],
	    [cgu],
	    [working_interest_pct],
	    [unit_cc_num],
	    [unit_cc_name],
	    [survey_system_code],
	    [uwi],
	    [uwi_desc],
	    [meridian],
	    [range],
	    [township],
	    [section],
	    [tax_pools],
	    [strat_unit_id],
	    [crstatus_desc],
	    [license_no],
	    [surf_location],
	    [tvd_depth],
	    [total_depth],
	    [zone_desc],
	    [deviation_flag],
	    [formatted_uwi],
	    [bottom_hole_latitude],
	    [bottom_hole_longitude],
	    [surface_latitude],
	    [surface_longitude],
	    [gas_shrinkage_factor],
	    [ngl_yield_factor],
	    [pvunit_completion_name],
	    [pvunit_name],
	    [pvunit_short_name],
	    [entity_source],
	    [is_cc_dim],
	    [cc_term_date],
	    [chance_of_success],
	    [budget_quarter],
	    [capital_group],
	    [capital_type],
	    [de_risk],
	    [depth_gci],
	    [drill_days],
	    [nra],
	    [reserve_realized_date],
	    [royalty_income_interest],
	    [well_direction],
	    [zone_play],
	    [is_valnav],
	    [budget_year_group],
	    [origin_group],
	    [cc_type_code],
	    [valnav_budget_year],
	    [cc_num_working_interest_pct],
	    [lateral_length],
	    [segment_start_date],
	    [valnav_budget_quarter],
	    [last_production_date],
	    [completion_type],
	    [total_proppant_placed],
	    [c_star],
	    [production_category],
	    [incentive_type],
	    [Meter_Station],
	    [type_curve_kpi],
	    [royalty_type],
	    [first_prod_month],
	    [group1],
	    [group2],
	    [group3],
	    [group4],
	    [group5],
	    [group6],
	    [group7],
	    [group8],
	    [group9],
	    [group10],
	    [completion_month],
	    [plant],
	    [keyera_inlet]	  
	  FROM
	    #t_dim_entity_MERGE
      WHERE 
	    Flag = 'NEW'
	
	  ------ ROW_COUNT
	  DECLARE  @rowcnt INT
	  EXEC [dbo].[LastRowCount] @rowcnt OUTPUT	
	  --SELECT @rowcnt

      UPDATE [data_mart].[t_dim_entity]
      SET --[data_mart].[t_dim_entity].entity_key = UPD.entity_key
		[data_mart].[t_dim_entity].[entity_name]					=  UPD.[entity_name],
		[data_mart].[t_dim_entity].[cost_centre]					=  UPD.[cost_centre],
		[data_mart].[t_dim_entity].[cost_centre_name]				=  UPD.[cost_centre_name],
		[data_mart].[t_dim_entity].[corp]                          =  UPD.[corp],
		[data_mart].[t_dim_entity].[corp_name]                     =  UPD.[corp_name],
		[data_mart].[t_dim_entity].[region]                        =  UPD.[region],
		[data_mart].[t_dim_entity].[region_name]                   =  UPD.[region_name],
		--[data_mart].[t_dim_entity].[region_code]                   =  UPD.[region_code],
		[data_mart].[t_dim_entity].[district]                      =  UPD.[district],
		[data_mart].[t_dim_entity].[district_name]                 =  UPD.[district_name],
		--[data_mart].[t_dim_entity].[district_code]                 =  UPD.[district_code],
		[data_mart].[t_dim_entity].[area]                          =  UPD.[area],
		[data_mart].[t_dim_entity].[area_name]                     =  UPD.[area_name],
		--[data_mart].[t_dim_entity].[area_code]                     =  UPD.[area_code],
		[data_mart].[t_dim_entity].[facility]                      =  UPD.[facility],
		[data_mart].[t_dim_entity].[facility_name]                 =  UPD.[facility_name],
		--[data_mart].[t_dim_entity].[facility_code]                 =  UPD.[facility_code],
		[data_mart].[t_dim_entity].[cc_type]                       =  UPD.[cc_type],
		[data_mart].[t_dim_entity].[budget_group]                  =  UPD.[budget_group],
		[data_mart].[t_dim_entity].[budget_year]                   =  UPD.[budget_year],
		[data_mart].[t_dim_entity].[op_nonop]                      =  UPD.[op_nonop],
		[data_mart].[t_dim_entity].[origin]                        =  UPD.[origin],
		[data_mart].[t_dim_entity].[province]                      =  UPD.[province],
		[data_mart].[t_dim_entity].[create_date]                   =  UPD.[create_date],
		[data_mart].[t_dim_entity].[spud_date]                     =  UPD.[spud_date],
		[data_mart].[t_dim_entity].[rig_release_date]              =  UPD.[rig_release_date],
		[data_mart].[t_dim_entity].[on_production_date]            =  UPD.[on_production_date],
		[data_mart].[t_dim_entity].[acquired_from]                 =  UPD.[acquired_from],
		[data_mart].[t_dim_entity].[current_reserves_property]     =  UPD.[current_reserves_property],
		[data_mart].[t_dim_entity].[disposition_package]           =  UPD.[disposition_package],
		[data_mart].[t_dim_entity].[disposition_type]              =  UPD.[disposition_type],
		[data_mart].[t_dim_entity].[disposition_area]              =  UPD.[disposition_area],
		[data_mart].[t_dim_entity].[disposition_facility]          =  UPD.[disposition_facility],
		[data_mart].[t_dim_entity].[disposed_flag]                 =  UPD.[disposed_flag],
		[data_mart].[t_dim_entity].[focus_area_flag]               =  UPD.[focus_area_flag],
		[data_mart].[t_dim_entity].[primary_product]               =  UPD.[primary_product],
		[data_mart].[t_dim_entity].[cgu]							=  UPD.[cgu],
		[data_mart].[t_dim_entity].[working_interest_pct]          =  UPD.[working_interest_pct],
		[data_mart].[t_dim_entity].[unit_cc_num]                   =  UPD.[unit_cc_num],
		[data_mart].[t_dim_entity].[unit_cc_name]                  =  UPD.[unit_cc_name],
		[data_mart].[t_dim_entity].[survey_system_code]            =  UPD.[survey_system_code],
		[data_mart].[t_dim_entity].[uwi]						    =  UPD.[uwi],
		[data_mart].[t_dim_entity].[uwi_desc]						=  UPD.[uwi_desc],
		[data_mart].[t_dim_entity].[meridian]                      =  UPD.[meridian],
		[data_mart].[t_dim_entity].[range]                         =  UPD.[range],
		[data_mart].[t_dim_entity].[township]                      =  UPD.[township],
		[data_mart].[t_dim_entity].[section]                       =  UPD.[section],
		[data_mart].[t_dim_entity].[tax_pools]						=  UPD.[tax_pools],
		[data_mart].[t_dim_entity].[strat_unit_id]                 =  UPD.[strat_unit_id],
		[data_mart].[t_dim_entity].[crstatus_desc]                 =  UPD.[crstatus_desc],
		[data_mart].[t_dim_entity].[license_no]                    =  UPD.[license_no],
		[data_mart].[t_dim_entity].[surf_location]                 =  UPD.[surf_location],
		[data_mart].[t_dim_entity].[tvd_depth]                     =  UPD.[tvd_depth],
		[data_mart].[t_dim_entity].[total_depth]                   =  UPD.[total_depth],
		[data_mart].[t_dim_entity].[zone_desc]                     =  UPD.[zone_desc],
		[data_mart].[t_dim_entity].[deviation_flag]                =  UPD.[deviation_flag],
		[data_mart].[t_dim_entity].[formatted_uwi]                 =  UPD.[formatted_uwi],
		[data_mart].[t_dim_entity].[bottom_hole_latitude]          =  UPD.[bottom_hole_latitude],
		[data_mart].[t_dim_entity].[bottom_hole_longitude]         =  UPD.[bottom_hole_longitude],
		[data_mart].[t_dim_entity].[surface_latitude]				=  UPD.[surface_latitude],
		[data_mart].[t_dim_entity].[surface_longitude]				=  UPD.[surface_longitude],
		[data_mart].[t_dim_entity].[gas_shrinkage_factor]          =  UPD.[gas_shrinkage_factor],
		[data_mart].[t_dim_entity].[ngl_yield_factor]              =  UPD.[ngl_yield_factor],
		[data_mart].[t_dim_entity].[pvunit_completion_name]        =  UPD.[pvunit_completion_name],
		[data_mart].[t_dim_entity].[pvunit_name]                   =  UPD.[pvunit_name],
		[data_mart].[t_dim_entity].[pvunit_short_name]             =  UPD.[pvunit_short_name],
		[data_mart].[t_dim_entity].[entity_source]				    =  UPD.[entity_source],
		[data_mart].[t_dim_entity].[is_cc_dim]						=  0,
		[data_mart].[t_dim_entity].[cc_term_date]					=  UPD.[cc_term_date],
		[data_mart].[t_dim_entity].[chance_of_success]				=  UPD.[chance_of_success],
		[data_mart].[t_dim_entity].[budget_quarter]				= UPD.[budget_quarter],
		[data_mart].[t_dim_entity].[capital_group]					= UPD.[capital_group],
		[data_mart].[t_dim_entity].[capital_type]					= UPD.[capital_type],
		[data_mart].[t_dim_entity].[de_risk]						= UPD.[de_risk],
		[data_mart].[t_dim_entity].[depth_gci]						= UPD.[depth_gci],
		[data_mart].[t_dim_entity].[drill_days]					= UPD.[drill_days],
		[data_mart].[t_dim_entity].[nra]							= UPD.[nra],
		[data_mart].[t_dim_entity].[reserve_realized_date]			= UPD.[reserve_realized_date],
		[data_mart].[t_dim_entity].[royalty_income_interest]       = UPD.[royalty_income_interest],
		[data_mart].[t_dim_entity].[well_direction]				= UPD.[well_direction],
		[data_mart].[t_dim_entity].[zone_play]						= UPD.[zone_play],
		[data_mart].[t_dim_entity].[is_valnav]						= UPD.[is_valnav],
		[data_mart].[t_dim_entity].[budget_year_group]			    = UPD.[budget_year_group],
		[data_mart].[t_dim_entity].[origin_group]					= UPD.[origin_group],
		[data_mart].[t_dim_entity].[cc_type_code]					= UPD.[cc_type_code],
		[data_mart].[t_dim_entity].[valnav_budget_year]			= UPD.[valnav_budget_year],
		[data_mart].[t_dim_entity].[cc_num_working_interest_pct]   = UPD.[cc_num_working_interest_pct],
		[data_mart].[t_dim_entity].[lateral_length]				= UPD.[lateral_length],
		[data_mart].[t_dim_entity].[segment_start_date]			= UPD.[segment_start_date],
		[data_mart].[t_dim_entity].[valnav_budget_quarter]		    = UPD.[budget_quarter],
		[data_mart].[t_dim_entity].[last_production_date]			= UPD.[last_production_date],
		[data_mart].[t_dim_entity].completion_type					= UPD.completion_type,
		[data_mart].[t_dim_entity].total_proppant_placed			= UPD.total_proppant_placed,
		[data_mart].[t_dim_entity].c_star							= UPD.c_star,
		[data_mart].[t_dim_entity].production_category				= UPD.production_category,
		[data_mart].[t_dim_entity].incentive_type					= UPD.incentive_type,
		[data_mart].[t_dim_entity].Meter_Station					= UPD.Meter_Station,
		[data_mart].[t_dim_entity].type_curve_kpi					= UPD.type_curve_kpi,
		[data_mart].[t_dim_entity].royalty_type					= UPD.royalty_type,
		[data_mart].[t_dim_entity].first_prod_month				= UPD.first_prod_month,
		[data_mart].[t_dim_entity].group1						= UPD.group1,
		[data_mart].[t_dim_entity].group2						= UPD.group2,
		[data_mart].[t_dim_entity].group3						= UPD.group3,
		[data_mart].[t_dim_entity].group4						= UPD.group4,
		[data_mart].[t_dim_entity].group5						= UPD.group5,
		[data_mart].[t_dim_entity].group6						= UPD.group6,
		[data_mart].[t_dim_entity].group7						= UPD.group7,
		[data_mart].[t_dim_entity].group8						= UPD.group8,
		[data_mart].[t_dim_entity].group9						= UPD.group9,
		[data_mart].[t_dim_entity].group10						= UPD.group10,
		[data_mart].[t_dim_entity].completion_month	        = UPD.completion_month,
		[data_mart].[t_dim_entity].plant				        = UPD.plant,
		[data_mart].[t_dim_entity].keyera_inlet		        = UPD.keyera_inlet
      FROM #t_dim_entity_MERGE UPD
      WHERE 
        [data_mart].[t_dim_entity].entity_key = UPD.entity_key AND
	    UPD.Flag = 'UPDATE'
	  
  --SELECT @rowcnt, COUNT(0) CNT FROM #t_dim_entity_MERGE

      IF OBJECT_ID('tempdb..#t_dim_entity_MERGE') IS NOT NULL
	    DROP TABLE #t_dim_entity_MERGE

   SELECT @rowcnt INSERTED
   -- COMMIT TRANSACTION

 --RETURN  
 END TRY
 
 BEGIN CATCH
	DECLARE @ErrorSeverity INT	= ERROR_SEVERITY()
			,@ErrorNumber INT	= ERROR_NUMBER()
			,@ErrorMessage nvarchar(4000)	= ERROR_MESSAGE()
			,@ErrorState INT = ERROR_STATE()
		--	,@ErrorLine  INT = ERROR_LINE()
			,@ErrorProc nvarchar(200) = ERROR_PROCEDURE()
			
	-- If the error renders the transaction as uncommittable or we have open transactions, rollback
	--IF @@TRANCOUNT > 0
 --	  ROLLBACK TRANSACTION

	RAISERROR (@ErrorMessage , @ErrorSeverity, @ErrorState, @ErrorNumber)

  END CATCH
  --RETURN @@ERROR
END