CREATE VIEW [stage].[v_dim_source_entity_valnav_history_entities]
AS SELECT vhh.entity_guid entity_key,
	   vhh.uwi entity_name,
	   vhh.cc_num cost_centre,
	   cast(vhh.cc_name as varchar(1000)) cost_centre_name,
	    cc.corp,
		cc.corp_name,
		cc.region,
		cc.region_name,
		vhh.region_display region_code,
		cc.district,
		cc.district_name,
		vhh.district_display district_code,
		cc.area,
		cc.area_name,
		vhh.area_display area_code,
		cc.facility,
		cc.facility_name,
		vhh.facility_display facility_code,
		cc.cc_type,
		cc.cc_type_code,
		cc.budget_group,
		cast (cc.budget_year as varchar(50))  budget_year,
		cast (vhh.budget_year as varchar(50)) valnav_budget_year,
		cast(vhh.op_nonop as varchar(10)) op_nonop,
		cc.origin,
		cast (vhh.province as varchar(50)) province,
		cc.create_date,
		uwi.spud_date,
		--uwi.rig_release_date,
		cast(case when vhh.on_prod_date is null
		     then CASE WHEN  uwi.on_production_date IS NULL 
				     THEN NULL
					 ELSE CONCAT(DATEPART(year,uwi.on_production_date),'-',RIGHT(CONCAT('0', DATEPART(mm,uwi.on_production_date)),2),'-',RIGHT(CONCAT('0', DATEPART(dd,uwi.on_production_date)),2)) 
			      END
			 else cast(vhh.on_prod_date as date)
		     end
			  as varchar(50)) on_production_date,
	   uwi.last_production_date,
       uwi.acquired_from,
	   vhh.current_reserve_property,
	   uwi.disposition_package,
	   uwi.disposition_type,
	   uwi.disposition_area,
	   uwi.disposition_facility,
	   uwi.disposed_flag,
	   uwi.focus_area_flag,
	   vhh.primary_product,
	   vhh.cgu,
	   vhh.working_interest,
       vhh.year_end_reserve_property,
	   cast(vhh.unit_cc_num as varchar(50)) unit_cc_num,
	   cast(vhh.unit_cc_name as varchar(1000)) unit_cc_name,
	   uwi.survey_system_code,
	   vhh.uwi,
	   cast(uwi.well_name as varchar(500)) uwi_desc,
	   uwi.meridian,
	   uwi.range,
	   uwi.township,
	   uwi.section,
	   uwi.tax_pools,
	   uwi.strat_unit_id,
	   uwi.crstatus_desc,
	   uwi.license_no,
	   uwi.surf_location,
	   uwi.tvd_depth,
	   uwi.total_depth,
	   uwi.zone_desc,
	   uwi.deviation_flag,
	   vhh.formatted_uwi,
	   uwi.bottom_hole_latitude,
	   uwi.bottom_hole_longitude,
	   uwi.surface_latitude,
	   uwi.surface_longitude,
	   uwi.gas_shrinkage_factor,
	   uwi.ngl_yield_factor,
	   uwi.pvunit_completion_name,
	   uwi.pvunit_name,
	   uwi.pvunit_short_name,
       'VALNAV' entity_source,
       0 is_cc_dim,
       cc.cc_term_date,
      vhh.chance_of_success,
	  vhh.budget_quarter,
	  vhh.capital_group,
	  vhh.capital_type,
	  vhh.de_risk,
      vhh.depth_gci,
      vhh.drill_days,
      vhh.nra,
	  cast (vhh.reserve_realized_date as varchar(50)) reserve_realized_date,
     vhh.royalty_income_interest,
     vhh.well_direction,
	 vhh.zone_play,
     1 is_valnav,
	 uwi.budget_year_group,
	 uwi.origin_group,
	 cc.working_interest_pct cc_num_working_interest_pct
FROM [stage].[t_valnav_dim_hierarchy_history] vhh
LEFT OUTER JOIN  [stage].t_cost_centre_hierarchy cc
ON vhh.cc_num = cc.cost_centre_id
LEFT OUTER JOIN [stage].v_dim_source_entity_uwi_hierarchy_attributes uwi
ON vhh.uwi = uwi.uwi;