CREATE VIEW [stage].[v_fact_source_opex_accrual_voucher_upload_detail]
AS with voucher_source 
as (
	SELECT CAST (1 AS numeric) voucher,
		CAST (org_id AS numeric) org_id,
		CAST (major_acct AS NCHAR (10)) major_acct,
		CAST (minor_acct AS NCHAR (10)) minor_acct,
		CAST (NULL AS NCHAR (10)) afe_number,
		CAST (NULL AS NCHAR (10)) afe_item_number,
		CAST (cc_num AS NCHAR (15)) cc_num,
		CAST (NULL AS NCHAR (10)) gl_sub_code,
		--CAST (CAD AS NCHAR (20)) voucher_amount,
		CAD AS voucher_amount,
		--amount as voucher_amount,
		CAST (actvy_per_date AS NCHAR (10)) actvy_per_date,
		CAST (NULL AS numeric) volume,
		CAST (NULL AS NCHAR (10)) non_standard_volume,
		CAST (NULL AS NCHAR (10)) enter_y_to_create_new_invoice,
		CAST (NULL AS NCHAR (10)) source_invoice_id,
		CAST (NULL AS NCHAR (10)) bussiness_associate,
		CAST (NULL AS NCHAR (10)) alternate_address,
		CAST (NULL AS NCHAR (10)) invoice_number,
		CAST (NULL AS NCHAR (10)) invoice_date,
		CAST (NULL AS NCHAR (10)) governing_agreement_type_code,
		CAST (NULL AS NCHAR (10)) gorverning_agreement_id,
		CAST (NULL AS NCHAR (10)) line_item_remark,
		CAST (NULL AS NCHAR (10)) continuity_code,
		CAST (NULL AS NCHAR (10)) line_item_enery_amount,
		CAST (NULL AS NCHAR (10)) voucher_gst_amount,
		CAST (NULL AS NCHAR (10)) operating_translation_rate,
		CAST (NULL AS NCHAR (10)) operating_amount,
		CAST (NULL AS NCHAR (10)) operating_gst_amount,
		CAST (NULL AS NCHAR (10)) main_report_translation_rate,
		CAST (NULL AS NCHAR (10)) main_reporting_amount,
		CAST (NULL AS NCHAR (10)) voucher_gross_up_amount,
		CAST (NULL AS NCHAR (10)) operating_gross_up_amount,
		CAST (NULL AS NCHAR (10)) main_reporting_gross_up_amt,
		CAST (NULL AS NCHAR (10)) operating_gross_up_volume,
		CAST (NULL AS NCHAR (10)) operating_gros_up_energy_value,
		CAST (NULL AS NCHAR (10)) due_date,
		CAST (NULL AS NCHAR (10)) hold_date,
		CAST (NULL AS NCHAR (10)) invoice_remark,
		CAST (NULL AS NCHAR (10)) invoice_alternate_client_id,
		CAST (NULL AS NCHAR (10)) purchase_order_number,
		CAST (NULL AS NCHAR (10)) contract_number,
		CAST (NULL AS NCHAR (10)) quick_pay,
		CAST (NULL AS NCHAR (10)) payment_code,
		CAST (NULL AS NCHAR (10)) payment_format_code,
		CAST (NULL AS NCHAR (10)) payment_handling_code,
		CAST (NULL AS NCHAR (10)) separate_cheque_flag,
		CAST (NULL AS NCHAR (10)) cheque_mail_type_code,
		CAST (NULL AS NCHAR (10)) attachment_required_flag,
		CAST (NULL AS NCHAR (10)) invoice_approval_short_name,
		CAST (NULL AS NCHAR (10)) miscellaneous_code,
		CAST (NULL AS NCHAR (10)) user_defined_flag,
		CAST (NULL AS NCHAR (10)) alternate_gl_code,
		CAST (NULL AS NCHAR (10)) line_items_alternate_client_id,
		CAST (NULL AS NCHAR (10)) footnote,
		CAST (NULL AS NCHAR (10)) billed_date
	FROM (
			SELECT 1 org_id,
				SUBSTRING(oa.account_key,1,4) major_acct,
				SUBSTRING(oa.account_key,6,3) minor_acct,
				oa.entity_key cc_num,
				cast(oa.accounting_month_key as nchar(10))  actvy_per_date,
				oa.cad
			FROM (
					SELECT cast(SUBSTRING(cast(accounting_month_key as varchar(10)),1,4) +'-' + 
						SUBSTRING(cast(accounting_month_key as varchar(10)),5,2) +'-' + 
						SUBSTRING(cast(accounting_month_key as varchar(10)),7,2) as datetime) as acct_date,
						loa.*
					FROM [data_mart].t_fact_leaseops_opex_accruals loa
			) oa
			, (
					SELECT DATEADD(month, DATEDIFF(month, 0, DATEADD(month, cn.num_of_mths_back +1, me.month_end_date)), 0)  start_date, 
						me.month_end_date end_date
					FROM (
							SELECT int_value * -1 num_of_mths_back
							FROM [stage].t_ctrl_etl_variables
							WHERE variable_name = 'OPEX_ACCRUAL_NUM_OF_MONTHS'
					) cn
					, (		SELECT EOMONTH(date_value) month_end_date
							FROM [stage].t_ctrl_etl_variables
							WHERE variable_name = 'OPEX_ACCRUAL_QBYTE_MONTH_END_DATE'
					) me
			) dates
			WHERE UPPER(LTRIM(RTRIM(oa.scenario_key)))='ACCRUAL'
			AND oa.acct_date BETWEEN dates.start_date AND dates.end_date
	)  source
)		/*--end of cte*/


SELECT "VOUCHER",
	"ORG_ID",
	"MAJOR_ACCT",
	"MINOR_ACCT",
	"AFE_NUMBER",
	"AFE_ITEM_NUMBER",
	"CC_NUM",
	"GL_SUB_CODE",
	cast("VOUCHER_AMOUNT" as nchar(50)) "VOUCHER_AMOUNT",
	"ACTVY_PER_DATE",
	"VOLUME",
	"NON_STANDARD_VOLUME",
	"ENTER_Y_TO_CREATE_NEW_INVOICE",
	"SOURCE_INVOICE_ID",
	"BUSSINESS_ASSOCIATE",
	"ALTERNATE_ADDRESS",
	"INVOICE_NUMBER",
	"INVOICE_DATE",
	"GOVERNING_AGREEMENT_TYPE_CODE",
	"GORVERNING_AGREEMENT_ID",
	"LINE_ITEM_REMARK",
	"CONTINUITY_CODE",
	"LINE_ITEM_ENERY_AMOUNT",
	"VOUCHER_GST_AMOUNT",
	"OPERATING_TRANSLATION_RATE",
	"OPERATING_AMOUNT",
	"OPERATING_GST_AMOUNT",
	"MAIN_REPORT_TRANSLATION_RATE",
	"MAIN_REPORTING_AMOUNT",
	"VOUCHER_GROSS_UP_AMOUNT",
	"OPERATING_GROSS_UP_AMOUNT",
	"MAIN_REPORTING_GROSS_UP_AMT",
	"OPERATING_GROSS_UP_VOLUME",
	"OPERATING_GROS_UP_ENERGY_VALUE",
	"DUE_DATE",
	"HOLD_DATE",
	"INVOICE_REMARK",
	"INVOICE_ALTERNATE_CLIENT_ID",
	"PURCHASE_ORDER_NUMBER",
	"CONTRACT_NUMBER",
	"QUICK_PAY",
	"PAYMENT_CODE",
	"PAYMENT_FORMAT_CODE",
	"PAYMENT_HANDLING_CODE",
	"SEPARATE_CHEQUE_FLAG",
	"CHEQUE_MAIL_TYPE_CODE",
	"ATTACHMENT_REQUIRED_FLAG",
	"INVOICE_APPROVAL_SHORT_NAME",
	"MISCELLANEOUS_CODE",
	"USER_DEFINED_FLAG",
	"ALTERNATE_GL_CODE",
	"LINE_ITEMS_ALTERNATE_CLIENT_ID",
	"FOOTNOTE",
	"BILLED_DATE"
from (
	SELECT "VOUCHER",
		"ORG_ID",
		"MAJOR_ACCT",
		"MINOR_ACCT",
		"AFE_NUMBER",
		"AFE_ITEM_NUMBER",
		"CC_NUM",
		"GL_SUB_CODE",
		cast("VOUCHER_AMOUNT" as decimal(18,9)) "VOUCHER_AMOUNT",
		"ACTVY_PER_DATE",
		"VOLUME",
		"NON_STANDARD_VOLUME",
		"ENTER_Y_TO_CREATE_NEW_INVOICE",
		"SOURCE_INVOICE_ID",
		"BUSSINESS_ASSOCIATE",
		"ALTERNATE_ADDRESS",
		"INVOICE_NUMBER",
		"INVOICE_DATE",
		"GOVERNING_AGREEMENT_TYPE_CODE",
		"GORVERNING_AGREEMENT_ID",
		"LINE_ITEM_REMARK",
		"CONTINUITY_CODE",
		"LINE_ITEM_ENERY_AMOUNT",
		"VOUCHER_GST_AMOUNT",
		"OPERATING_TRANSLATION_RATE",
		"OPERATING_AMOUNT",
		"OPERATING_GST_AMOUNT",
		"MAIN_REPORT_TRANSLATION_RATE",
		"MAIN_REPORTING_AMOUNT",
		"VOUCHER_GROSS_UP_AMOUNT",
		"OPERATING_GROSS_UP_AMOUNT",
		"MAIN_REPORTING_GROSS_UP_AMT",
		"OPERATING_GROSS_UP_VOLUME",
		"OPERATING_GROS_UP_ENERGY_VALUE",
		"DUE_DATE",
		"HOLD_DATE",
		"INVOICE_REMARK",
		"INVOICE_ALTERNATE_CLIENT_ID",
		"PURCHASE_ORDER_NUMBER",
		"CONTRACT_NUMBER",
		"QUICK_PAY",
		"PAYMENT_CODE",
		"PAYMENT_FORMAT_CODE",
		"PAYMENT_HANDLING_CODE",
		"SEPARATE_CHEQUE_FLAG",
		"CHEQUE_MAIL_TYPE_CODE",
		"ATTACHMENT_REQUIRED_FLAG",
		"INVOICE_APPROVAL_SHORT_NAME",
		"MISCELLANEOUS_CODE",
		"USER_DEFINED_FLAG",
		"ALTERNATE_GL_CODE",
		"LINE_ITEMS_ALTERNATE_CLIENT_ID",
		"FOOTNOTE",
		"BILLED_DATE"
	FROM voucher_source
	--
	UNION ALL

	SELECT DISTINCT "VOUCHER",
		"ORG_ID",
		CAST ('3300' AS NCHAR (10)) AS "MAJOR_ACCT",
		CAST ('050' AS NCHAR (10)) AS "MINOR_ACCT",
		"AFE_NUMBER",
		"AFE_ITEM_NUMBER",
		CAST (NULL AS NCHAR (15)) AS CC_NUM,
		"GL_SUB_CODE",
		cast (SUM ("VOUCHER_AMOUNT" * -1) OVER (PARTITION BY ORG_ID) as decimal(18,9))	VOUCHER_AMOUNT,
		CAST (NULL AS NCHAR (10)) "ACTVY_PER_DATE",
		"VOLUME",
		"NON_STANDARD_VOLUME",
		"ENTER_Y_TO_CREATE_NEW_INVOICE",
		"SOURCE_INVOICE_ID",
		"BUSSINESS_ASSOCIATE",
		"ALTERNATE_ADDRESS",
		"INVOICE_NUMBER",
		"INVOICE_DATE",
		"GOVERNING_AGREEMENT_TYPE_CODE",
		"GORVERNING_AGREEMENT_ID",
		"LINE_ITEM_REMARK",
		"CONTINUITY_CODE",
		"LINE_ITEM_ENERY_AMOUNT",
		"VOUCHER_GST_AMOUNT",
		"OPERATING_TRANSLATION_RATE",
		"OPERATING_AMOUNT",
		"OPERATING_GST_AMOUNT",
		"MAIN_REPORT_TRANSLATION_RATE",
		"MAIN_REPORTING_AMOUNT",
		"VOUCHER_GROSS_UP_AMOUNT",
		"OPERATING_GROSS_UP_AMOUNT",
		"MAIN_REPORTING_GROSS_UP_AMT",
		"OPERATING_GROSS_UP_VOLUME",
		"OPERATING_GROS_UP_ENERGY_VALUE",
		"DUE_DATE",
		"HOLD_DATE",
		"INVOICE_REMARK",
		"INVOICE_ALTERNATE_CLIENT_ID",
		"PURCHASE_ORDER_NUMBER",
		"CONTRACT_NUMBER",
		"QUICK_PAY",
		"PAYMENT_CODE",
		"PAYMENT_FORMAT_CODE",
		"PAYMENT_HANDLING_CODE",
		"SEPARATE_CHEQUE_FLAG",
		"CHEQUE_MAIL_TYPE_CODE",
		"ATTACHMENT_REQUIRED_FLAG",
		"INVOICE_APPROVAL_SHORT_NAME",
		"MISCELLANEOUS_CODE",
		"USER_DEFINED_FLAG",
		"ALTERNATE_GL_CODE",
		"LINE_ITEMS_ALTERNATE_CLIENT_ID",
		"FOOTNOTE",
		"BILLED_DATE"
	FROM voucher_source
) sq;