CREATE TABLE [stage_prodview].[t_pvt_pvunit] (
    [idflownet]                VARCHAR (32)   NOT NULL,
    [idrec]                    VARCHAR (32)   NOT NULL,
    [name]                     VARCHAR (100)  NULL,
    [nameshort]                VARCHAR (50)   NULL,
    [typ1]                     VARCHAR (50)   NULL,
    [typ2]                     VARCHAR (50)   NULL,
    [typdisphcliq]             VARCHAR (50)   NULL,
    [dispproductname]          VARCHAR (50)   NULL,
    [idrecroutesetroutecalc]   VARCHAR (32)   NULL,
    [idrecroutesetroutecalctk] VARCHAR (26)   NULL,
    [idrecfacilitycalc]        VARCHAR (32)   NULL,
    [idrecfacilitycalctk]      VARCHAR (26)   NULL,
    [typregulatory]            VARCHAR (50)   NULL,
    [typpa]                    VARCHAR (50)   NULL,
    [displaysizefactor]        FLOAT (53)     NULL,
    [dttmstart]                DATETIME       NULL,
    [dttmend]                  DATETIME       NULL,
    [dttmhide]                 DATETIME       NULL,
    [elevation]                FLOAT (53)     NULL,
    [unitidregulatory]         VARCHAR (50)   NULL,
    [unitidpa]                 VARCHAR (50)   NULL,
    [unitida]                  VARCHAR (50)   NULL,
    [unitidb]                  VARCHAR (50)   NULL,
    [unitidc]                  VARCHAR (50)   NULL,
    [purchaser]                SMALLINT       NULL,
    [operated]                 SMALLINT       NULL,
    [operator]                 VARCHAR (50)   NULL,
    [operatorida]              VARCHAR (50)   NULL,
    [com]                      VARCHAR (2000) NULL,
    [legalsurfloc]             VARCHAR (100)  NULL,
    [division]                 VARCHAR (100)  NULL,
    [divisioncode]             VARCHAR (100)  NULL,
    [district]                 VARCHAR (100)  NULL,
    [country]                  VARCHAR (50)   NULL,
    [area]                     VARCHAR (50)   NULL,
    [field]                    VARCHAR (50)   NULL,
    [fieldcode]                VARCHAR (50)   NULL,
    [fieldoffice]              VARCHAR (50)   NULL,
    [fieldofficecode]          VARCHAR (50)   NULL,
    [stateprov]                VARCHAR (50)   NULL,
    [county]                   VARCHAR (50)   NULL,
    [latitude]                 FLOAT (53)     NULL,
    [longitude]                FLOAT (53)     NULL,
    [latlongsource]            VARCHAR (50)   NULL,
    [latlongdatum]             VARCHAR (50)   NULL,
    [utmgridzone]              INT            NULL,
    [utmsource]                VARCHAR (50)   NULL,
    [utmx]                     FLOAT (53)     NULL,
    [utmy]                     FLOAT (53)     NULL,
    [lease]                    VARCHAR (50)   NULL,
    [leaseida]                 VARCHAR (50)   NULL,
    [locationtyp]              VARCHAR (50)   NULL,
    [platform]                 VARCHAR (50)   NULL,
    [padcode]                  VARCHAR (50)   NULL,
    [padname]                  VARCHAR (50)   NULL,
    [slot]                     VARCHAR (20)   NULL,
    [govauthority]             VARCHAR (50)   NULL,
    [costcenterida]            VARCHAR (50)   NULL,
    [costcenteridb]            VARCHAR (50)   NULL,
    [sortbyuser]               VARCHAR (50)   NULL,
    [priority]                 SMALLINT       NULL,
    [timezone]                 VARCHAR (100)  NULL,
    [idrecresp1]               VARCHAR (32)   NULL,
    [idrecresp1tk]             VARCHAR (26)   NULL,
    [idrecresp2]               VARCHAR (32)   NULL,
    [idrecresp2tk]             VARCHAR (26)   NULL,
    [keymigrationsource]       VARCHAR (100)  NULL,
    [typmigrationsource]       VARCHAR (100)  NULL,
    [usertxt1]                 VARCHAR (50)   NULL,
    [usertxt2]                 VARCHAR (50)   NULL,
    [usertxt3]                 VARCHAR (50)   NULL,
    [usertxt4]                 VARCHAR (50)   NULL,
    [usertxt5]                 VARCHAR (50)   NULL,
    [usernum1]                 FLOAT (53)     NULL,
    [usernum2]                 FLOAT (53)     NULL,
    [usernum3]                 FLOAT (53)     NULL,
    [usernum4]                 FLOAT (53)     NULL,
    [usernum5]                 FLOAT (53)     NULL,
    [userdttm1]                DATETIME       NULL,
    [userdttm2]                DATETIME       NULL,
    [userdttm3]                DATETIME       NULL,
    [userdttm4]                DATETIME       NULL,
    [userdttm5]                DATETIME       NULL,
    [syslockmeui]              SMALLINT       NULL,
    [syslockchildrenui]        SMALLINT       NULL,
    [syslockme]                SMALLINT       NULL,
    [syslockchildren]          SMALLINT       NULL,
    [syslockdate]              DATETIME       NULL,
    [sysmoddate]               DATETIME       NULL,
    [sysmoduser]               VARCHAR (50)   NULL,
    [syscreatedate]            DATETIME       NULL,
    [syscreateuser]            VARCHAR (50)   NULL,
    [systag]                   VARCHAR (255)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

