CREATE TABLE [pv30_prodcopy].[pvt_pvfacilitymonthdaycalc] (
    [idflownet]                     VARCHAR (32)  NOT NULL,
    [idrecparent]                   VARCHAR (32)  NULL,
    [idrec]                         VARCHAR (32)  NOT NULL,
    [idrecfacility]                 VARCHAR (32)  NULL,
    [idrecfacilitytk]               VARCHAR (26)  NULL,
    [dttm]                          DATETIME      NULL,
    [year]                          INT           NULL,
    [month]                         INT           NULL,
    [dayofmonth]                    INT           NULL,
    [volprodhcliq]                  FLOAT (53)    NULL,
    [volprodgas]                    FLOAT (53)    NULL,
    [volprodgasplusgaseq]           FLOAT (53)    NULL,
    [volprodwater]                  FLOAT (53)    NULL,
    [volprodsand]                   FLOAT (53)    NULL,
    [volnewprodgathhcliq]           FLOAT (53)    NULL,
    [volnewprodgathgas]             FLOAT (53)    NULL,
    [volnewprodgathgasplusgaseq]    FLOAT (53)    NULL,
    [volnewprodgathwater]           FLOAT (53)    NULL,
    [volnewprodgathsand]            FLOAT (53)    NULL,
    [balfacthcliq]                  FLOAT (53)    NULL,
    [balfactgas]                    FLOAT (53)    NULL,
    [balfactgasplusgaseq]           FLOAT (53)    NULL,
    [balfactwater]                  FLOAT (53)    NULL,
    [balfactsand]                   FLOAT (53)    NULL,
    [volbalhcliq]                   FLOAT (53)    NULL,
    [volbalgas]                     FLOAT (53)    NULL,
    [volbalgasplusgaseq]            FLOAT (53)    NULL,
    [volbalwater]                   FLOAT (53)    NULL,
    [volbalsand]                    FLOAT (53)    NULL,
    [balanced]                      SMALLINT      NULL,
    [balhcliq]                      SMALLINT      NULL,
    [balgas]                        SMALLINT      NULL,
    [balgasplusgaseq]               SMALLINT      NULL,
    [balwater]                      SMALLINT      NULL,
    [balsand]                       SMALLINT      NULL,
    [volinrecovhcliq]               FLOAT (53)    NULL,
    [volinrecovgas]                 FLOAT (53)    NULL,
    [volinrecovgasplusgaseq]        FLOAT (53)    NULL,
    [volinrecovwater]               FLOAT (53)    NULL,
    [volinrecovsand]                FLOAT (53)    NULL,
    [volinotherhcliq]               FLOAT (53)    NULL,
    [volinothergas]                 FLOAT (53)    NULL,
    [volinothergasplusgaseq]        FLOAT (53)    NULL,
    [volinotherwater]               FLOAT (53)    NULL,
    [volinothersand]                FLOAT (53)    NULL,
    [voloutconsumehcliq]            FLOAT (53)    NULL,
    [voloutconsumegas]              FLOAT (53)    NULL,
    [voloutconsumegasplusgaseq]     FLOAT (53)    NULL,
    [voloutconsumewater]            FLOAT (53)    NULL,
    [voloutconsumesand]             FLOAT (53)    NULL,
    [voloutinjectrecovhcliq]        FLOAT (53)    NULL,
    [voloutinjectrecovgas]          FLOAT (53)    NULL,
    [voloutinjectrecovgasplusgaseq] FLOAT (53)    NULL,
    [voloutinjectrecovwater]        FLOAT (53)    NULL,
    [voloutinjectrecovsand]         FLOAT (53)    NULL,
    [voloutotherhcliq]              FLOAT (53)    NULL,
    [voloutothergas]                FLOAT (53)    NULL,
    [voloutothergasplusgaseq]       FLOAT (53)    NULL,
    [voloutotherwater]              FLOAT (53)    NULL,
    [voloutothersand]               FLOAT (53)    NULL,
    [volstartremainrecovhcliq]      FLOAT (53)    NULL,
    [volstartremainrecovgas]        FLOAT (53)    NULL,
    [volstartremainrecovgasplusgeq] FLOAT (53)    NULL,
    [volstartremainrecovwater]      FLOAT (53)    NULL,
    [volstartremainrecovsand]       FLOAT (53)    NULL,
    [volendremainrecovhcliq]        FLOAT (53)    NULL,
    [volendremainrecovgas]          FLOAT (53)    NULL,
    [volendremainrecovgasplusgeq]   FLOAT (53)    NULL,
    [volendremainrecovwater]        FLOAT (53)    NULL,
    [volendremainrecovsand]         FLOAT (53)    NULL,
    [volstartinvhcliq]              FLOAT (53)    NULL,
    [volstartinvhcliqgaseq]         FLOAT (53)    NULL,
    [volstartinvwater]              FLOAT (53)    NULL,
    [volstartinvsand]               FLOAT (53)    NULL,
    [volendinvhcliq]                FLOAT (53)    NULL,
    [volendinvhcliqgaseq]           FLOAT (53)    NULL,
    [volendinvwater]                FLOAT (53)    NULL,
    [volendinvsand]                 FLOAT (53)    NULL,
    [volchginvhcliq]                FLOAT (53)    NULL,
    [volchginvhcliqgaseq]           FLOAT (53)    NULL,
    [volchginvwater]                FLOAT (53)    NULL,
    [volchginvsand]                 FLOAT (53)    NULL,
    [volstvgas]                     FLOAT (53)    NULL,
    [syslockmeui]                   SMALLINT      NULL,
    [syslockchildrenui]             SMALLINT      NULL,
    [syslockme]                     SMALLINT      NULL,
    [syslockchildren]               SMALLINT      NULL,
    [syslockdate]                   DATETIME      NULL,
    [sysmoddate]                    DATETIME      NULL,
    [sysmoduser]                    VARCHAR (50)  NULL,
    [syscreatedate]                 DATETIME      NULL,
    [syscreateuser]                 VARCHAR (50)  NULL,
    [systag]                        VARCHAR (255) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

