CREATE TABLE [pv30_prodcopy].[pvt_pvunitcompstatus] (
    [idflownet]         VARCHAR (32)   NOT NULL,
    [idrecparent]       VARCHAR (32)   NULL,
    [idrec]             VARCHAR (32)   NOT NULL,
    [dttm]              DATETIME       NULL,
    [status]            VARCHAR (50)   NULL,
    [primaryfluidtyp]   VARCHAR (50)   NULL,
    [flowdirection]     VARCHAR (20)   NULL,
    [commingled]        VARCHAR (50)   NULL,
    [typfluidprod]      VARCHAR (50)   NULL,
    [typcompletion]     VARCHAR (20)   NULL,
    [methodprod]        VARCHAR (50)   NULL,
    [calclostprod]      SMALLINT       NULL,
    [wellcountincl]     SMALLINT       NULL,
    [usertxt1]          VARCHAR (50)   NULL,
    [usertxt2]          VARCHAR (50)   NULL,
    [usertxt3]          VARCHAR (50)   NULL,
    [usernum1]          FLOAT (53)     NULL,
    [usernum2]          FLOAT (53)     NULL,
    [usernum3]          FLOAT (53)     NULL,
    [com]               VARCHAR (2000) NULL,
    [syslockmeui]       SMALLINT       NULL,
    [syslockchildrenui] SMALLINT       NULL,
    [syslockme]         SMALLINT       NULL,
    [syslockchildren]   SMALLINT       NULL,
    [syslockdate]       DATETIME       NULL,
    [sysmoddate]        DATETIME       NULL,
    [sysmoduser]        VARCHAR (50)   NULL,
    [syscreatedate]     DATETIME       NULL,
    [syscreateuser]     VARCHAR (50)   NULL,
    [systag]            VARCHAR (255)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

