CREATE TABLE [stage_valnav].[t_basedecline_ent_detail] (
    [PARENT_ID]                   NVARCHAR (50)  NOT NULL,
    [WELL_NAME]                   NVARCHAR (100) NULL,
    [FIELD]                       NVARCHAR (100) NULL,
    [FIELD_CODE]                  NVARCHAR (25)  NULL,
    [POOL]                        NVARCHAR (100) NULL,
    [POOL_CODE]                   NVARCHAR (25)  NULL,
    [OPERATOR]                    NVARCHAR (100) NULL,
    [LICENSEE]                    NVARCHAR (100) NULL,
    [UNIT]                        NVARCHAR (100) NULL,
    [WELL_STATUS]                 NVARCHAR (100) NULL,
    [COUNTRY_ID]                  NVARCHAR (50)  NULL,
    [PROVINCE_ID]                 NVARCHAR (50)  NULL,
    [DISTRICT]                    NVARCHAR (50)  NULL,
    [WELL_TYPE]                   NVARCHAR (20)  NULL,
    [PRODUCT]                     NVARCHAR (100) NULL,
    [RIG_RELEASE_DATE]            DATETIME2 (7)  NULL,
    [CURRENT_MONTH]               DATETIME2 (7)  NOT NULL,
    [SURFACE_LATITUDE]            FLOAT (53)     NULL,
    [SURFACE_LONGITUDE]           FLOAT (53)     NULL,
    [BOTTOMHOLE_LATITUDE]         FLOAT (53)     NULL,
    [BOTTOMHOLE_LONGITUDE]        FLOAT (53)     NULL,
    [IS_GROUPED]                  TINYINT        NOT NULL,
    [ROOT_GROUP_ID]               NVARCHAR (50)  NULL,
    [INCLUDE_IN_RESERVES]         TINYINT        NOT NULL,
    [FORECAST_CHANGE_DATE]        BIGINT         NOT NULL,
    [ECON_CHANGE_DATE]            BIGINT         NOT NULL,
    [FIRST_PROD_MONTH]            DATETIME2 (7)  NULL,
    [LAST_PROD_MONTH]             DATETIME2 (7)  NULL,
    [FIRST_INJ_MONTH]             DATETIME2 (7)  NULL,
    [FIRST_MONTH_WITH_DAILY]      DATETIME2 (7)  NULL,
    [LAST_MONTH_WITH_DAILY]       DATETIME2 (7)  NULL,
    [LAST_INJ_MONTH]              DATETIME2 (7)  NULL,
    [DATA_SOURCE]                 NVARCHAR (100) NULL,
    [REVIEW_STATE]                INT            NOT NULL,
    [WELL_PROFILE_TYPE]           INT            NULL,
    [LAST_UPDATE_DATE]            BIGINT         NOT NULL,
    [LAST_UPDATE_USER]            NVARCHAR (50)  NULL,
    [CROSS_PLOT_IP_CALC]          NVARCHAR (50)  NULL,
    [CROSS_PLOT_DISTRIBUTION]     INT            NULL,
    [CROSS_PLOT_NUM_MONTHS]       INT            NULL,
    [CROSS_PLOT_USE_INIT_RATE]    TINYINT        NULL,
    [FACTOR_ID]                   NVARCHAR (50)  NULL,
    [SUPPRESS_DEFAULT_CALC_SETUP] TINYINT        NOT NULL,
    [PRIMARY_API]                 NVARCHAR (100) NULL,
    [PRODUCT_LIST_ID]             NVARCHAR (50)  NULL,
    [CHANGE_REASON_ENTITY_ID]     NVARCHAR (50)  NULL,
    [CHANGE_REASON_DETAIL_ID]     NVARCHAR (50)  NULL,
    [ZONE]                        NVARCHAR (50)  NULL,
    [LICENSE]                     NVARCHAR (20)  NULL,
    [CROSS_PLOT_NORMLZ_BASE]      NVARCHAR (80)  NULL,
    [CROSS_PLOT_NORMLZ_FIELD]     NVARCHAR (80)  NULL,
    [CROSS_PLOT_NORMLZ_ENABLED]   TINYINT        NULL,
    [CROSS_PLOT_PRODUCT_ID]       NVARCHAR (50)  NULL,
    [CROSS_PLOT_PRODUCT_TYPE]     INT            NULL,
    [OIL_DENSITY]                 FLOAT (53)     NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

