CREATE TABLE [stage_valnav].[t_budget_ent_segment] (
    [OBJECT_ID]                     NVARCHAR (50) NOT NULL,
    [PARENT_ID]                     NVARCHAR (50) NOT NULL,
    [SEGMENT_INDEX]                 INT           NOT NULL,
    [START_DATE]                    DATETIME2 (7) NOT NULL,
    [START_DATE_LINKED]             TINYINT       NOT NULL,
    [END_DATE]                      DATETIME2 (7) NOT NULL,
    [TIME_CALCULATED]               TINYINT       NOT NULL,
    [QI]                            FLOAT (53)    NOT NULL,
    [QI_LINKED]                     TINYINT       NOT NULL,
    [DI]                            FLOAT (53)    NOT NULL,
    [DI_LINKED]                     TINYINT       NOT NULL,
    [DI_CALCULATED]                 TINYINT       NOT NULL,
    [N]                             FLOAT (53)    NOT NULL,
    [N_LINKED]                      TINYINT       NOT NULL,
    [EI]                            FLOAT (53)    NOT NULL,
    [QF]                            FLOAT (53)    NOT NULL,
    [QF_LINKED]                     TINYINT       NOT NULL,
    [QF_CALCULATED]                 TINYINT       NOT NULL,
    [MAX_RATE]                      FLOAT (53)    NOT NULL,
    [MAX_RATE_LINKED]               TINYINT       NOT NULL,
    [START_CUM]                     FLOAT (53)    NOT NULL,
    [END_CUM]                       FLOAT (53)    NOT NULL,
    [DENOMINATOR_START_CUM]         FLOAT (53)    NOT NULL,
    [DENOMINATOR_END_CUM]           FLOAT (53)    NOT NULL,
    [DENOMINATOR_VOLUME_CALCULATED] TINYINT       NOT NULL,
    [START_TIME]                    FLOAT (53)    NOT NULL,
    [END_TIME]                      FLOAT (53)    NOT NULL,
    [VOLUME_CALCULATED]             TINYINT       NOT NULL,
    [DF]                            FLOAT (53)    NOT NULL,
    [DF_CALCULATED]                 TINYINT       NOT NULL,
    [FINAL_VOLUME]                  FLOAT (53)    NOT NULL,
    [FINAL_VOLUME_LINKED]           TINYINT       NOT NULL,
    [FINAL_VOLUME_CALCULATED]       TINYINT       NOT NULL,
    [ERROR_TYPE]                    INT           NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

