CREATE TABLE [stage_valnav].[t_typecurves_ent_shared_plan_data] (
    [PARENT_ID]                     NVARCHAR (50) NOT NULL,
    [PLAN_DEFINITION_ID]            NVARCHAR (50) NOT NULL,
    [CURRENCY_ID]                   NVARCHAR (50) NULL,
    [KELLY_BUSHING]                 FLOAT (53)    NULL,
    [CASING_FLANGE]                 FLOAT (53)    NULL,
    [PERF_TOP]                      FLOAT (53)    NULL,
    [PERF_BOTTOM]                   FLOAT (53)    NULL,
    [MID_POINT_PERF]                FLOAT (53)    NULL,
    [WELL_DATUM]                    FLOAT (53)    NULL,
    [POOL_DATUM]                    FLOAT (53)    NULL,
    [POOL_DATUM_CORRECTION]         FLOAT (53)    NULL,
    [OIL_PRODUCT_TYPE]              NVARCHAR (50) NULL,
    [GAS_PRODUCT_TYPE]              NVARCHAR (50) NULL,
    [GROSS_COMP_INTERVAL]           FLOAT (53)    NULL,
    [SPUD_DATE]                     DATETIME2 (7) NULL,
    [MEASURED_DEPTH]                FLOAT (53)    NULL,
    [TOTAL_MEASURED_DEPTH]          FLOAT (53)    NULL,
    [FORMATION_TEMPERATURE]         FLOAT (53)    NULL,
    [USE_UNECONOMIC_ABAN_RULES]     TINYINT       NULL,
    [RING_FENCE_REGIME_ID]          NVARCHAR (50) NULL,
    [ALLOW_NEGATIVE_WEDGE]          INT           NULL,
    [APPLY_TERMINATION_TO_CHILDREN] TINYINT       NULL,
    [HONOR_CHILD_LIMIT]             INT           NULL,
    [TRUE_VERTICAL_DEPTH]           FLOAT (53)    NULL,
    [TRUE_VERTICAL_DEPTH_AVG]       FLOAT (53)    NULL,
    [TRUE_VERTICAL_DEPTH_MAX]       FLOAT (53)    NULL,
    [LATERAL_LENGTH]                FLOAT (53)    NULL,
    [TOTAL_LATERAL_LENGTH]          FLOAT (53)    NULL,
    [TOTAL_PROPPANT_PLACED]         FLOAT (53)    NULL,
    [COMPLETION_TYPE]               INT           NOT NULL,
    [ACID_CONCENTRATION]            FLOAT (53)    NULL,
    [ACID_FRACTURE_VOLUME]          FLOAT (53)    NULL,
    [RING_FENCE_CALCULATION_ID]     NVARCHAR (50) NULL,
    [FORECAST_MODE]                 INT           NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

