CREATE TABLE [OLAPControl].[t_Run_Task_Log] (
    [Run_Task_key]   BIGINT           IDENTITY (1, 1) NOT NULL,
    [RunID]          UNIQUEIDENTIFIER NOT NULL,
    [Job]            NVARCHAR (100)   NULL,
    [Cube]           NVARCHAR (100)   NULL,
    [Package]        NVARCHAR (100)   NULL,
    [Task]           NVARCHAR (100)   NULL,
    [Description]    NVARCHAR (500)   NULL,
    [Message]        NVARCHAR (1000)  NULL,
    [Information]    NVARCHAR (1000)  NULL,
    [FailedTask]     NVARCHAR (100)   NULL,
    [ExceptionMsg]   NVARCHAR (1000)  NULL,
    [Start_date]     DATETIME         NOT NULL,
    [End_date]       DATETIME         NULL,
    [End_date_calc]  DATETIME         NULL,
    [Duration_sec]   INT              NULL,
    [Inserted_count] INT              NULL,
    [Updated_count]  INT              NULL,
    [Deleted_count]  INT              NULL,
    [Total]          FLOAT (53)       NULL,
    [Data_01]        NVARCHAR (100)   NULL,
    [Data_02]        NVARCHAR (100)   NULL,
    [Data_03]        NVARCHAR (100)   NULL,
    [Data_Value_01]  FLOAT (53)       NULL,
    [Data_Value_02]  FLOAT (53)       NULL,
    [Data_Value_03]  FLOAT (53)       NULL,
    [Status_Code]    INT              NULL,
    [Status]         NVARCHAR (50)    NOT NULL,
    [Username]       NVARCHAR (100)   NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

