CREATE TABLE [STAGE_METRIX_METRIX].[BATTERY_MASTERS] (
    [CREATE_USER]                  VARCHAR (30)  NOT NULL,
    [CREATE_PROGRAM]               VARCHAR (120) NULL,
    [CREATE_DATE_TIME]             DATETIME2 (7) NOT NULL,
    [LAST_UPDATE_USER]             VARCHAR (30)  NOT NULL,
    [LAST_UPDATE_PROGRAM]          VARCHAR (120) NULL,
    [LAST_UPDATE_DATE_TIME]        DATETIME2 (7) NOT NULL,
    [LAST_UPDATE_AUDIT_ID]         NUMERIC (16)  NULL,
    [VERSION]                      NUMERIC (10)  NOT NULL,
    [SYS_ID]                       NUMERIC (16)  NOT NULL,
    [PRODUCTION_DATE]              NUMERIC (6)   NOT NULL,
    [NAME]                         VARCHAR (40)  NOT NULL,
    [BATTERY_TYPE]                 VARCHAR (1)   NOT NULL,
    [GOVERNMENT_CODE]              VARCHAR (16)  NOT NULL,
    [COST_CENTRE_CODE]             VARCHAR (16)  NULL,
    [PRODUCTION_STATUS]            VARCHAR (6)   NOT NULL,
    [FLUID_TYPE]                   VARCHAR (6)   NOT NULL,
    [USER_DEFINED1]                VARCHAR (16)  NULL,
    [USER_DEFINED2]                VARCHAR (16)  NULL,
    [REGISTRY_PROVINCE]            VARCHAR (2)   NULL,
    [REGISTRY_ENTITY_TYPE]         VARCHAR (2)   NULL,
    [REGISTRY_GOVERNMENT_CODE]     VARCHAR (16)  NULL,
    [CONTACT_NAME]                 VARCHAR (60)  NOT NULL,
    [CONTACT_PHONE]                VARCHAR (16)  NULL,
    [SURVEY_SYSTEM]                VARCHAR (6)   NOT NULL,
    [DLS_LOCATION_EXCEPTION]       VARCHAR (2)   NULL,
    [DLS_MERIDIAN]                 NUMERIC (1)   NULL,
    [DLS_RANGE]                    NUMERIC (2)   NULL,
    [DLS_SECTION]                  NUMERIC (2)   NULL,
    [DLS_TOWNSHIP]                 NUMERIC (3)   NULL,
    [DLS_EVENT_SEQUENCE]           NUMERIC (1)   NULL,
    [NTS_LOCATION_EXCEPTION]       VARCHAR (2)   NULL,
    [NTS_QUARTER_UNIT]             VARCHAR (1)   NULL,
    [NTS_UNIT]                     VARCHAR (3)   NULL,
    [NTS_BLOCK]                    VARCHAR (1)   NULL,
    [NTS_MAP_NUMBER1]              VARCHAR (3)   NULL,
    [NTS_MAP_NUMBER2]              VARCHAR (1)   NULL,
    [NTS_MAP_NUMBER3]              VARCHAR (2)   NULL,
    [NTS_EVENT_SEQUENCE]           NUMERIC (1)   NULL,
    [OFF_SHORE_BLOCK]              NUMERIC (3)   NULL,
    [OFF_SHORE_TRACT]              VARCHAR (1)   NULL,
    [OFF_SHORE_SUB_TRACT]          NUMERIC (1)   NULL,
    [DLS_SUB_DIVISION]             NUMERIC (2)   NULL,
    [OFF_SHORE_QUADRANT]           VARCHAR (1)   NULL,
    [ON_SHORE_TRACT]               VARCHAR (1)   NULL,
    [ON_SHORE_LOT]                 VARCHAR (3)   NULL,
    [ON_SHORE_CONCESSION]          VARCHAR (4)   NULL,
    [ON_SHORE_ZONE]                VARCHAR (1)   NULL,
    [END_OF_STREAM_FACILITY]       VARCHAR (1)   NULL,
    [PRA_FACILITY]                 VARCHAR (1)   NULL,
    [PROCESS_VOLUMETRICS]          VARCHAR (1)   NULL,
    [PRODUCE_PIPELINE_SPLIT]       VARCHAR (1)   NULL,
    [OIL_PIPELINE_SPLIT]           VARCHAR (1)   NULL,
    [BC08_FACILITY]                VARCHAR (1)   NULL,
    [BC09_FACILITY]                VARCHAR (1)   NULL,
    [WESTFLO_RECEIPT_POINT]        VARCHAR (1)   NULL,
    [CTP_REGISTRY_ENTITY_TYPE]     VARCHAR (2)   NULL,
    [CTP_REGISTRY_PROVINCE]        VARCHAR (2)   NULL,
    [CTP_REGISTRY_GOVERNMENT_CODE] VARCHAR (16)  NULL,
    [BATTERY_FACILITY_ID]          VARCHAR (16)  NOT NULL,
    [BATTERY_OPERATOR_ID]          VARCHAR (16)  NOT NULL,
    [PA_RESPONSIBLE_USER_ID]       VARCHAR (30)  NOT NULL,
    [OIL_CTP_PRODUCT_CODE]         VARCHAR (16)  NULL,
    [ON_SHORE_TOWNSHIP]            VARCHAR (16)  NULL,
    [ENTITY_SUBTYPE_SYS_ID]        NUMERIC (16)  NULL,
    [PSEUDO_BATTERY_FLAG]          VARCHAR (1)   NOT NULL,
    [PROCESS_SAFOAF_FLAG]          VARCHAR (1)   NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

