CREATE TABLE [STAGE_METRIX_METRIX].[CONTROL_GROUP_HIERARCHIES] (
    [CREATE_USER]             VARCHAR (30)  NOT NULL,
    [CREATE_PROGRAM]          VARCHAR (120) NULL,
    [CREATE_DATE_TIME]        DATETIME2 (7) NOT NULL,
    [LAST_UPDATE_USER]        VARCHAR (30)  NOT NULL,
    [LAST_UPDATE_PROGRAM]     VARCHAR (120) NULL,
    [LAST_UPDATE_DATE_TIME]   DATETIME2 (7) NOT NULL,
    [LAST_UPDATE_AUDIT_ID]    NUMERIC (16)  NULL,
    [VERSION]                 NUMERIC (10)  NOT NULL,
    [SYS_ID]                  NUMERIC (16)  NOT NULL,
    [PRODUCTION_DATE]         NUMERIC (6)   NOT NULL,
    [LEVEL_NUMBER]            NUMERIC (2)   NULL,
    [CONTROL_GROUP_ID]        VARCHAR (16)  NOT NULL,
    [PARENT_HIERARCHY_SYS_ID] NUMERIC (16)  NULL,
    [FACILITY_SYS_ID]         NUMERIC (16)  NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

