CREATE TABLE [STAGE_METRIX_METRIX].[DIVISION_OF_INTERESTS] (
    [CREATE_USER]           VARCHAR (30)  NULL,
    [CREATE_DATE_TIME]      DATETIME2 (7) NULL,
    [LAST_UPDATE_USER]      VARCHAR (30)  NULL,
    [LAST_UPDATE_DATE_TIME] DATETIME2 (7) NULL,
    [VERSION]               NUMERIC (10)  NULL,
    [SYS_ID]                NUMERIC (16)  NULL,
    [CREATE_PROGRAM]        VARCHAR (120) NULL,
    [LAST_UPDATE_PROGRAM]   VARCHAR (120) NULL,
    [LAST_UPDATE_AUDIT_ID]  NUMERIC (16)  NULL,
    [FACILITY_SYS_ID]       NUMERIC (16)  NULL,
    [WELL_TRACT_SYS_ID]     NUMERIC (16)  NULL,
    [UNIT_ID]               VARCHAR (16)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

