CREATE TABLE [STAGE_METRIX_METRIX].[FC_EXPENSE_INCOME_REPORTS] (
    [SYS_ID]                        NUMERIC (18)    NULL,
    [CREATE_USER]                   VARCHAR (30)    NULL,
    [CREATE_DATE_TIME]              DATETIME2 (7)   NULL,
    [PRODUCTION_DATE]               NUMERIC (18)    NULL,
    [JOB_ID]                        NUMERIC (18)    NULL,
    [REPORT_TITLE]                  VARCHAR (40)    NULL,
    [OWNER_ID]                      VARCHAR (16)    NULL,
    [FACILITY_TYPE]                 VARCHAR (16)    NULL,
    [FACILITY_ID]                   VARCHAR (16)    NULL,
    [BATTERY_ID]                    VARCHAR (16)    NULL,
    [EXPENSE_FACILITY_TYPE]         VARCHAR (16)    NULL,
    [EXPENSE_FACILITY_ID]           VARCHAR (16)    NULL,
    [PRODUCT_CODE]                  VARCHAR (16)    NULL,
    [CHARGE_TYPE]                   VARCHAR (16)    NULL,
    [CHARGE_DESCRIPTION]            VARCHAR (60)    NULL,
    [PRIMARY_RETRIEVAL]             VARCHAR (6)     NULL,
    [PRIMARY_RETRIEVAL_DESCRIPTION] VARCHAR (60)    NULL,
    [CHARGE_SEQUENCE_NUMBER]        NUMERIC (18)    NULL,
    [COST_CENTRE_ID]                VARCHAR (16)    NULL,
    [REVISED_VOLUME]                NUMERIC (9, 1)  NULL,
    [PREVIOUS_VOLUME]               NUMERIC (9, 1)  NULL,
    [NET_VOLUME]                    NUMERIC (9, 1)  NULL,
    [REVISED_VALUE]                 NUMERIC (11, 2) NULL,
    [PREVIOUS_VALUE]                NUMERIC (11, 2) NULL,
    [NET_VALUE]                     NUMERIC (11, 2) NULL,
    [ACCOUNTING_DATE]               NUMERIC (18)    NULL,
    [REVISED_GST_VALUE]             NUMERIC (11, 2) NULL,
    [REVISED_PST_VALUE]             NUMERIC (11, 2) NULL,
    [PREVIOUS_GST_VALUE]            NUMERIC (11, 2) NULL,
    [PREVIOUS_PST_VALUE]            NUMERIC (11, 2) NULL,
    [NET_GST_VALUE]                 NUMERIC (11, 2) NULL,
    [NET_PST_VALUE]                 NUMERIC (11, 2) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

