CREATE TABLE [STAGE_METRIX_METRIX].[FC_FORMULA_MASTERS] (
    [CREATE_USER]                  VARCHAR (30)  NOT NULL,
    [CREATE_PROGRAM]               VARCHAR (120) NULL,
    [CREATE_DATE_TIME]             DATETIME2 (7) NOT NULL,
    [LAST_UPDATE_USER]             VARCHAR (30)  NOT NULL,
    [LAST_UPDATE_PROGRAM]          VARCHAR (120) NULL,
    [LAST_UPDATE_DATE_TIME]        DATETIME2 (7) NOT NULL,
    [LAST_UPDATE_AUDIT_ID]         NUMERIC (16)  NULL,
    [VERSION]                      NUMERIC (10)  NOT NULL,
    [SYS_ID]                       NUMERIC (16)  NOT NULL,
    [PRODUCTION_DATE]              NUMERIC (6)   NOT NULL,
    [DESCRIPTION]                  VARCHAR (40)  NOT NULL,
    [PRIMARY_RETRIEVAL_CODE]       VARCHAR (6)   NOT NULL,
    [VOLUME_TYPE]                  VARCHAR (6)   NOT NULL,
    [VALUE_TYPE]                   VARCHAR (6)   NOT NULL,
    [UNIT_TRACT_CRITERIA]          VARCHAR (6)   NULL,
    [FACILITY_CHARGE_FORMULA_ID]   VARCHAR (16)  NOT NULL,
    [FC_SHUTIN_LOOKUP_ID]          VARCHAR (16)  NULL,
    [FACILITY_CHARGE_FORMULA_TYPE] VARCHAR (6)   NOT NULL,
    [CONTROL_GROUP_ID]             VARCHAR (16)  NULL,
    [FC_MONTHLY_INPUT_ID]          VARCHAR (16)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

