CREATE TABLE [STAGE_METRIX_METRIX].[INDIAN_RESERVE_WELL_DETAILS] (
    [CREATE_USER]            VARCHAR (30)    NOT NULL,
    [CREATE_PROGRAM]         VARCHAR (120)   NULL,
    [CREATE_DATE_TIME]       DATETIME2 (7)   NOT NULL,
    [LAST_UPDATE_USER]       VARCHAR (30)    NOT NULL,
    [LAST_UPDATE_PROGRAM]    VARCHAR (120)   NULL,
    [LAST_UPDATE_DATE_TIME]  DATETIME2 (7)   NOT NULL,
    [LAST_UPDATE_AUDIT_ID]   NUMERIC (16)    NULL,
    [VERSION]                NUMERIC (10)    NOT NULL,
    [SYS_ID]                 NUMERIC (16)    NOT NULL,
    [PRODUCTION_DATE]        NUMERIC (6)     NOT NULL,
    [INCLUDED_EXCLUDED]      VARCHAR (6)     NOT NULL,
    [TOTAL_SALES_VALUE]      NUMERIC (11, 2) NULL,
    [TOTAL_ROYALTY_VALUE]    NUMERIC (11, 2) NULL,
    [GROSS_ROYALTY_PERCENT]  NUMERIC (11, 8) NULL,
    [TOTAL_GCA_DEDUCTION]    NUMERIC (11, 2) NULL,
    [ROYALTY_NET_AMOUNT]     NUMERIC (11, 2) NULL,
    [WELL_TRACT_SYS_ID]      NUMERIC (16)    NULL,
    [UNIT_ID]                VARCHAR (16)    NULL,
    [INDIAN_RESERVE_ID]      VARCHAR (16)    NOT NULL,
    [CONFIDENTIAL_WELL_FLAG] VARCHAR (1)     NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

