CREATE TABLE [STAGE_METRIX_METRIX].[ROYALTY_OBLIGATION_MASTERS] (
    [CREATE_USER]                VARCHAR (30)  NULL,
    [CREATE_PROGRAM]             VARCHAR (120) NULL,
    [CREATE_DATE_TIME]           DATETIME2 (7) NULL,
    [LAST_UPDATE_USER]           VARCHAR (30)  NULL,
    [LAST_UPDATE_PROGRAM]        VARCHAR (120) NULL,
    [LAST_UPDATE_DATE_TIME]      DATETIME2 (7) NULL,
    [LAST_UPDATE_AUDIT_ID]       NUMERIC (18)  NULL,
    [VERSION]                    NUMERIC (18)  NULL,
    [SYS_ID]                     NUMERIC (18)  NULL,
    [PRODUCTION_DATE]            NUMERIC (18)  NULL,
    [OBLIGATION_TYPE]            VARCHAR (6)   NULL,
    [TAKEN_IN_KIND]              VARCHAR (1)   NULL,
    [DOI_OWNERSHIP_EXTENSION_ID] NUMERIC (18)  NULL,
    [PAYMENT_TYPE]               VARCHAR (6)   NULL,
    [TAX_TYPE]                   VARCHAR (6)   NULL,
    [USER_DEFINED1]              VARCHAR (16)  NULL,
    [USER_DEFINED2]              VARCHAR (16)  NULL,
    [USER_DEFINED3]              VARCHAR (16)  NULL,
    [ROYALTY_OBLIGATION_SYS_ID]  NUMERIC (18)  NULL,
    [ROYALTY_FORMULA_ID]         VARCHAR (16)  NULL,
    [ROYALTY_OWNER_ID]           VARCHAR (16)  NULL,
    [PAID_BY_OWNER_ID]           VARCHAR (16)  NULL,
    [PAYOR_TYPE]                 VARCHAR (6)   NULL,
    [ACTIVE_FLAG]                VARCHAR (1)   NULL,
    [ROYALTY_ENTITY_SYS_ID]      NUMERIC (18)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

