CREATE TABLE [STAGE_METRIX_METRIX].[ROYALTY_FORMULA_MASTERS] (
    [CREATE_USER]           VARCHAR (30)  NULL,
    [CREATE_DATE_TIME]      DATETIME2 (7) NULL,
    [LAST_UPDATE_USER]      VARCHAR (30)  NULL,
    [LAST_UPDATE_DATE_TIME] DATETIME2 (7) NULL,
    [VERSION]               NUMERIC (10)  NULL,
    [SYS_ID]                NUMERIC (16)  NULL,
    [PRODUCTION_DATE]       NUMERIC (6)   NULL,
    [DESCRIPTION]           VARCHAR (60)  NULL,
    [ROYALTY_FORMULA_ID]    VARCHAR (16)  NULL,
    [CREATE_PROGRAM]        VARCHAR (120) NULL,
    [LAST_UPDATE_PROGRAM]   VARCHAR (120) NULL,
    [LAST_UPDATE_AUDIT_ID]  NUMERIC (16)  NULL,
    [ROYALTY_FORMULA_TYPE]  VARCHAR (6)   NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

