CREATE TABLE [STAGE_METRIX_METRIX].[UNIT_TRACTS] (
    [CREATE_USER]            VARCHAR (30)    NOT NULL,
    [CREATE_PROGRAM]         VARCHAR (120)   NULL,
    [CREATE_DATE_TIME]       DATETIME2 (7)   NOT NULL,
    [LAST_UPDATE_USER]       VARCHAR (30)    NOT NULL,
    [LAST_UPDATE_PROGRAM]    VARCHAR (120)   NULL,
    [LAST_UPDATE_DATE_TIME]  DATETIME2 (7)   NOT NULL,
    [LAST_UPDATE_AUDIT_ID]   NUMERIC (16)    NULL,
    [VERSION]                NUMERIC (10)    NOT NULL,
    [SYS_ID]                 NUMERIC (16)    NOT NULL,
    [PRODUCTION_DATE]        NUMERIC (6)     NOT NULL,
    [PRODUCTION_PERCENT]     NUMERIC (11, 8) NOT NULL,
    [CROWN_PERCENT]          NUMERIC (11, 8) NULL,
    [FREEHOLD_PERCENT]       NUMERIC (11, 8) NULL,
    [CROWN_ACQUIRED_PERCENT] NUMERIC (11, 8) NULL,
    [FEDERAL_PERCENT]        NUMERIC (11, 8) NULL,
    [UNITIZED_WELL_ID]       VARCHAR (16)    NULL,
    [TRACT_ID]               VARCHAR (16)    NOT NULL,
    [PRODUCT_CODE]           VARCHAR (16)    NULL,
    [UNIT_ID]                VARCHAR (16)    NOT NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

