CREATE TABLE [STAGE_METRIX_METRIX].[USER_ACCOUNTS] (
    [CREATE_USER]              VARCHAR (30)  NOT NULL,
    [CREATE_PROGRAM]           VARCHAR (120) NULL,
    [CREATE_DATE_TIME]         DATETIME2 (7) NOT NULL,
    [LAST_UPDATE_USER]         VARCHAR (30)  NOT NULL,
    [LAST_UPDATE_PROGRAM]      VARCHAR (120) NULL,
    [LAST_UPDATE_DATE_TIME]    DATETIME2 (7) NOT NULL,
    [LAST_UPDATE_AUDIT_ID]     NUMERIC (16)  NULL,
    [VERSION]                  NUMERIC (10)  NOT NULL,
    [USER_ID]                  VARCHAR (30)  NOT NULL,
    [USER_NAME]                VARCHAR (60)  NOT NULL,
    [INACTIVE_USER]            VARCHAR (1)   NOT NULL,
    [ALL_CONTROL_GROUP_ACCESS] VARCHAR (1)   NOT NULL,
    [HOME_PAGE_SYS_ID]         NUMERIC (16)  NULL,
    [DEFAULT_EXPAND_ALL_FLAG]  VARCHAR (1)   NOT NULL,
    [DEFAULT_PRODUCTION_DATE]  NUMERIC (6)   NULL,
    [DEFAULT_CONTROL_GROUP_ID] VARCHAR (16)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

