CREATE TABLE [STAGE_METRIX_METRIX].[WELL_MASTERS] (
    [CREATE_USER]                  VARCHAR (30)   NOT NULL,
    [CREATE_PROGRAM]               VARCHAR (120)  NULL,
    [CREATE_DATE_TIME]             DATETIME2 (7)  NOT NULL,
    [LAST_UPDATE_USER]             VARCHAR (30)   NOT NULL,
    [LAST_UPDATE_PROGRAM]          VARCHAR (120)  NULL,
    [LAST_UPDATE_DATE_TIME]        DATETIME2 (7)  NOT NULL,
    [LAST_UPDATE_AUDIT_ID]         NUMERIC (16)   NULL,
    [VERSION]                      NUMERIC (10)   NOT NULL,
    [SYS_ID]                       NUMERIC (16)   NOT NULL,
    [PRODUCTION_DATE]              NUMERIC (6)    NOT NULL,
    [NAME]                         VARCHAR (40)   NOT NULL,
    [UNIQUE_WELL_IDENTIFIER]       VARCHAR (30)   NOT NULL,
    [PRODUCTION_STATUS]            VARCHAR (6)    NOT NULL,
    [SURVEY_SYSTEM]                VARCHAR (6)    NOT NULL,
    [DLS_LOCATION_EXCEPTION]       VARCHAR (2)    NULL,
    [DLS_SUB_DIVISION]             NUMERIC (2)    NULL,
    [DLS_SECTION]                  NUMERIC (2)    NULL,
    [DLS_TOWNSHIP]                 NUMERIC (3)    NULL,
    [DLS_RANGE]                    NUMERIC (2)    NULL,
    [DLS_MERIDIAN]                 NUMERIC (1)    NULL,
    [DLS_EVENT_SEQUENCE]           NUMERIC (1)    NULL,
    [NTS_LOCATION_EXCEPTION]       VARCHAR (2)    NULL,
    [NTS_QUARTER_UNIT]             VARCHAR (1)    NULL,
    [NTS_UNIT]                     VARCHAR (3)    NULL,
    [NTS_BLOCK]                    VARCHAR (1)    NULL,
    [NTS_MAP_NUMBER1]              VARCHAR (3)    NULL,
    [NTS_MAP_NUMBER2]              VARCHAR (1)    NULL,
    [NTS_MAP_NUMBER3]              VARCHAR (2)    NULL,
    [NTS_EVENT_SEQUENCE]           NUMERIC (1)    NULL,
    [OFF_SHORE_BLOCK]              NUMERIC (3)    NULL,
    [OFF_SHORE_TRACT]              VARCHAR (1)    NULL,
    [OFF_SHORE_SUB_TRACT]          NUMERIC (1)    NULL,
    [OFF_SHORE_QUADRANT]           VARCHAR (1)    NULL,
    [ON_SHORE_TRACT]               VARCHAR (1)    NULL,
    [ON_SHORE_LOT]                 VARCHAR (3)    NULL,
    [ON_SHORE_CONCESSION]          VARCHAR (4)    NULL,
    [ON_SHORE_ZONE]                VARCHAR (1)    NULL,
    [FLUID_TYPE]                   VARCHAR (6)    NULL,
    [FIELD_CODE]                   VARCHAR (12)   NULL,
    [POOL_CODE]                    VARCHAR (12)   NULL,
    [FIELD_POOL_CODE]              VARCHAR (16)   NULL,
    [GOVERNMENT_LICENSE_NUMBER]    NUMERIC (6)    NULL,
    [USER_DEFINED1]                VARCHAR (16)   NULL,
    [USER_DEFINED2]                VARCHAR (16)   NULL,
    [REPORT_LIQUID_AS_CONDENSATE]  VARCHAR (1)    NULL,
    [REPORT_ZERO_PRODUCTION]       VARCHAR (1)    NULL,
    [HEAVY_OIL]                    VARCHAR (1)    NULL,
    [PARTNER_OPERATED_REGISTRY_ID] VARCHAR (30)   NULL,
    [MB_WELL_TYPE]                 VARCHAR (1)    NULL,
    [CAP_SOLUTION_WELL_TYPE]       VARCHAR (6)    NULL,
    [COMMINGLED_WELL_TYPE]         VARCHAR (6)    NULL,
    [RECOMBINED_LIQUID_AND_GAS]    VARCHAR (1)    NULL,
    [MEASUREMENT_TYPE]             VARCHAR (6)    NULL,
    [REPORTING_WELL_IDENTIFIER]    VARCHAR (30)   NULL,
    [BATTERY_FACILITY_ID]          VARCHAR (16)   NULL,
    [ROYALTY_ENTITY_SYS_ID]        NUMERIC (16)   NULL,
    [OIL_ROYALTY_ENTITY_SYS_ID]    NUMERIC (16)   NULL,
    [COST_CENTRE_CODE]             VARCHAR (16)   NULL,
    [WELL_ID]                      VARCHAR (16)   NOT NULL,
    [PA_RESPONSIBLE_USER_ID]       VARCHAR (30)   NOT NULL,
    [WATER_TYPE_CODE]              VARCHAR (16)   NULL,
    [ON_SHORE_TOWNSHIP]            VARCHAR (16)   NULL,
    [WELL_DEPTH]                   NUMERIC (5, 1) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

