CREATE TABLE [STAGE_METRIX].[t_stg_metrix_sales_details] (
    [CREATE_USER]                    VARCHAR (30)    NULL,
    [CREATE_PROGRAM]                 VARCHAR (120)   NULL,
    [CREATE_DATE_TIME]               DATETIME2 (7)   NULL,
    [LAST_UPDATE_USER]               VARCHAR (30)    NULL,
    [LAST_UPDATE_PROGRAM]            VARCHAR (120)   NULL,
    [LAST_UPDATE_DATE_TIME]          DATETIME2 (7)   NULL,
    [LAST_UPDATE_AUDIT_ID]           NUMERIC (18)    NULL,
    [VERSION]                        NUMERIC (18)    NULL,
    [SYS_ID]                         NUMERIC (18)    NULL,
    [PRODUCTION_DATE]                NUMERIC (18)    NULL,
    [DELIVERY_SEQUENCE]              NUMERIC (18)    NULL,
    [PURCHASER_SEQUENCE]             NUMERIC (18)    NULL,
    [PURCHASER_TYPE]                 VARCHAR (6)     NULL,
    [SALES_VOLUME]                   NUMERIC (9, 1)  NULL,
    [REVENUE_NOT_RECEIVED_REASON]    VARCHAR (6)     NULL,
    [GAS_ANALYSIS_FACTOR]            NUMERIC (11, 8) NULL,
    [THEORETICAL_GIGAJOULES]         NUMERIC (12)    NULL,
    [ACTUAL_GIGAJOULES]              NUMERIC (12)    NULL,
    [ALLOCATION_NUMBER]              NUMERIC (2)     NULL,
    [SPECIAL_PLANT_RECEIPT]          VARCHAR (1)     NULL,
    [SPLIT_LOAD_OIL]                 VARCHAR (1)     NULL,
    [DOI_SUB_USED]                   VARCHAR (12)    NULL,
    [WORKING_INTEREST_PERCENT]       NUMERIC (11, 8) NULL,
    [DEFAULT_SOURCE_WELL]            VARCHAR (16)    NULL,
    [INJECTION_WELL_USER_DEFINED1]   VARCHAR (16)    NULL,
    [TOTAL_VALUE]                    NUMERIC (11, 2) NULL,
    [TOTAL_VOLUME]                   NUMERIC (9, 1)  NULL,
    [SALES_VALUE]                    NUMERIC (11, 2) NULL,
    [SALES_VALUE_NET_OF_TRANSPORT]   NUMERIC (11, 2) NULL,
    [BATTERY_FACILITY_ID]            VARCHAR (16)    NULL,
    [ORIGINAL_BATTERY_FACILITY_ID]   VARCHAR (16)    NULL,
    [CONTROL_GROUP_ID]               VARCHAR (16)    NULL,
    [ROYALTY_OBLIGATION_SYS_ID]      NUMERIC (18)    NULL,
    [FACILITY_SYS_ID]                NUMERIC (18)    NULL,
    [DELIVERY_FACILITY_SYS_ID]       NUMERIC (18)    NULL,
    [TRANSFER_FACILITY_SYS_ID]       NUMERIC (18)    NULL,
    [OWNER_ID]                       VARCHAR (16)    NULL,
    [REFERENCE_OWNER_ID]             VARCHAR (16)    NULL,
    [PURCHASER_ID]                   VARCHAR (16)    NULL,
    [WELL_TRACT_SYS_ID]              NUMERIC (18)    NULL,
    [INJECTION_WELL_ID]              VARCHAR (16)    NULL,
    [PRODUCT_CODE]                   VARCHAR (16)    NULL,
    [DELIVERY_DISPOSITION_TYPE_CODE] VARCHAR (16)    NULL,
    [DELIVERY_SYSTEM_ID]             VARCHAR (16)    NULL,
    [FLOW_GROUP_ID]                  VARCHAR (16)    NULL,
    [OWNER_TYPE_CODE]                VARCHAR (16)    NULL,
    [REPORT_AS_PRODUCT_CODE]         VARCHAR (16)    NULL,
    [PRICING_USER_DEFINED1]          VARCHAR (16)    NULL,
    [PURCHASE_FLAG]                  VARCHAR (1)     NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

