CREATE TABLE [STAGE_METRIX].[t_stg_metrix_participant_availables] (
    [CREATE_USER]                   VARCHAR (30)    NOT NULL,
    [CREATE_PROGRAM]                VARCHAR (120)   NULL,
    [CREATE_DATE_TIME]              DATETIME2 (7)   NOT NULL,
    [LAST_UPDATE_USER]              VARCHAR (30)    NOT NULL,
    [LAST_UPDATE_PROGRAM]           VARCHAR (120)   NULL,
    [LAST_UPDATE_DATE_TIME]         DATETIME2 (7)   NOT NULL,
    [LAST_UPDATE_AUDIT_ID]          NUMERIC (16)    NULL,
    [VERSION]                       NUMERIC (10)    NOT NULL,
    [SYS_ID]                        NUMERIC (16)    NOT NULL,
    [PRODUCTION_DATE]               NUMERIC (6)     NOT NULL,
    [DOI_SUB_USED]                  VARCHAR (16)    NULL,
    [WORKING_INTEREST_PERCENT]      NUMERIC (11, 8) NULL,
    [DEFAULT_SOURCE_WELL]           VARCHAR (16)    NULL,
    [OPENING_INVENTORY]             NUMERIC (9, 1)  NULL,
    [TRANSFER_RECEIVED]             NUMERIC (9, 1)  NULL,
    [CLOSING_INVENTORY]             NUMERIC (9, 1)  NULL,
    [PRODUCTION_VOLUME]             NUMERIC (9, 1)  NULL,
    [TRANSFER_VOLUME]               NUMERIC (9, 1)  NULL,
    [AVAILABLE_FOR_SALE_VOLUME]     NUMERIC (9, 1)  NULL,
    [SALES_VOLUME]                  NUMERIC (9, 1)  NULL,
    [OPENING_GIGAJOULES]            NUMERIC (12)    NULL,
    [PRODUCTION_GIGAJOULES]         NUMERIC (12)    NULL,
    [SALES_GIGAJOULES]              NUMERIC (12)    NULL,
    [CLOSING_GIGAJOULES]            NUMERIC (12)    NULL,
    [SPECIAL_PLANT_RECEIPT]         VARCHAR (1)     NULL,
    [SENDING_BATTERY_FACILITY_ID]   VARCHAR (16)    NULL,
    [RECEIVING_BATTERY_FACILITY_ID] VARCHAR (16)    NULL,
    [ROYALTY_OBLIGATION_SYS_ID]     NUMERIC (16)    NULL,
    [FACILITY_SYS_ID]               NUMERIC (16)    NOT NULL,
    [TRANSFER_FACILITY_SYS_ID]      NUMERIC (16)    NULL,
    [OWNER_ID]                      VARCHAR (16)    NULL,
    [WORKING_INTEREST_OWNER_ID]     VARCHAR (16)    NULL,
    [WELL_TRACT_SYS_ID]             NUMERIC (16)    NULL,
    [PRODUCT_CODE]                  VARCHAR (16)    NOT NULL,
    [FLOW_GROUP_ID]                 VARCHAR (16)    NULL,
    [PARTICIPANT_TYPE_CODE]         VARCHAR (16)    NULL,
    [VOLUME_SENT_FOR_FRAC]          NUMERIC (9, 1)  NULL,
    [VOLUME_FROM_FRAC]              NUMERIC (9, 1)  NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

