CREATE TABLE [data_mart].[t_dim_account_hierarchy] (
    [account_key]               INT             NULL,
    [parent_key]                INT             NULL,
    [account_id]                VARCHAR (500)   NULL,
    [parent_id]                 VARCHAR (500)   NULL,
    [account_desc]              VARCHAR (4000)  NULL,
    [gl_account]                VARCHAR (50)    NULL,
    [gl_account_description]    VARCHAR (4000)  NULL,
    [account_level_01]          VARCHAR (500)   NULL,
    [account_level_02]          VARCHAR (500)   NULL,
    [account_level_03]          VARCHAR (500)   NULL,
    [account_level_04]          VARCHAR (500)   NULL,
    [account_level_05]          VARCHAR (500)   NULL,
    [account_level_06]          VARCHAR (500)   NULL,
    [account_level_07]          VARCHAR (500)   NULL,
    [account_level_08]          VARCHAR (500)   NULL,
    [account_level_09]          VARCHAR (500)   NULL,
    [account_level_10]          VARCHAR (500)   NULL,
    [major_account]             VARCHAR (4)     NULL,
    [minor_account]             VARCHAR (4)     NULL,
    [major_account_description] VARCHAR (4000)  NULL,
    [major_class_code]          VARCHAR (4000)  NULL,
    [class_code_description]    VARCHAR (100)   NULL,
    [product_code]              VARCHAR (50)    NULL,
    [si_to_imp_conv_factor]     VARCHAR (50)    NULL,
    [boe_thermal]               VARCHAR (50)    NULL,
    [mcfe6_thermal]             VARCHAR (50)    NULL,
    [product_description]       VARCHAR (100)   NULL,
    [account_group]             VARCHAR (50)    NULL,
    [display_sequence_number]   VARCHAR (4)     NULL,
    [gross_or_net_code]         VARCHAR (25)    NULL,
    [unary_operator]            VARCHAR (10)    NULL,
    [account_level_01_sort_key] VARCHAR (500)   NULL,
    [account_level_02_sort_key] VARCHAR (500)   NULL,
    [account_level_03_sort_key] VARCHAR (500)   NULL,
    [account_level_04_sort_key] VARCHAR (500)   NULL,
    [account_level_05_sort_key] VARCHAR (500)   NULL,
    [account_level_06_sort_key] VARCHAR (500)   NULL,
    [account_level_07_sort_key] VARCHAR (500)   NULL,
    [account_level_08_sort_key] VARCHAR (500)   NULL,
    [account_level_09_sort_key] VARCHAR (500)   NULL,
    [account_level_10_sort_key] VARCHAR (500)   NULL,
    [is_leaseops]               INT             NULL,
    [is_capital]                INT             NULL,
    [is_volumes]                INT             NULL,
    [is_valnav]                 INT             NULL,
    [zero_level]                INT             NULL,
    [Hierarchy_Path]            NVARCHAR (1000) NULL,
    [source]                    VARCHAR (100)   NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

