CREATE TABLE [data_mart].[t_dim_authorization_for_expenditure] (
    [afe_key]                            BIGINT           IDENTITY (1, 1) NOT NULL,
    [afe_num]                            VARCHAR (10)     NOT NULL,
    [afe_name]                           VARCHAR (40)     NULL,
    [client_id]                          VARCHAR (50)     NULL,
    [client_name]                        VARCHAR (100)    NULL,
    [op_nonop]                           VARCHAR (10)     NULL,
    [ref_org_id]                         VARCHAR (50)     NULL,
    [afe_type_code]                      VARCHAR (30)     NULL,
    [afe_type_description]               VARCHAR (100)    NULL,
    [afe_status_code]                    VARCHAR (30)     NULL,
    [afe_status_description]             VARCHAR (100)    NULL,
    [cost_centre]                        VARCHAR (10)     NULL,
    [cost_centre_name]                   VARCHAR (4000)   NULL,
    [corp_code]                          VARCHAR (10)     NULL,
    [corp_name]                          VARCHAR (4000)   NULL,
    [region]                             VARCHAR (100)    NULL,
    [region_code]                        VARCHAR (100)    NULL,
    [region_name]                        VARCHAR (4000)   NULL,
    [district]                           VARCHAR (100)    NULL,
    [district_code]                      VARCHAR (100)    NULL,
    [district_name]                      VARCHAR (4000)   NULL,
    [area]                               VARCHAR (100)    NULL,
    [area_code]                          VARCHAR (100)    NULL,
    [area_name]                          VARCHAR (4000)   NULL,
    [facility]                           VARCHAR (100)    NULL,
    [facility_code]                      VARCHAR (100)    NULL,
    [facility_name]                      VARCHAR (4000)   NULL,
    [curr_code]                          VARCHAR (6)      NULL,
    [ownership_org_id]                   NUMERIC (4)      NULL,
    [jib_flag]                           VARCHAR (1)      NULL,
    [cip_transfer_flag]                  VARCHAR (1)      NULL,
    [use_jibe_edits_flag]                VARCHAR (1)      NULL,
    [accrual_flag]                       VARCHAR (1)      NULL,
    [create_date]                        DATETIME         NULL,
    [create_user]                        VARCHAR (30)     NULL,
    [last_updt_date]                     DATETIME         NULL,
    [last_updt_user]                     VARCHAR (32)     NULL,
    [term_date]                          DATETIME         NULL,
    [term_user]                          VARCHAR (32)     NULL,
    [effective_date]                     DATETIME         NULL,
    [proposal_date]                      DATETIME         NULL,
    [due_date]                           DATETIME         NULL,
    [commitment_date]                    DATETIME         NULL,
    [afe_approval_date]                  DATETIME         NULL,
    [afe_start_date]                     DATETIME         NULL,
    [budget_activity_year]               VARCHAR (25)     NULL,
    [extrapolated_budget_year]           INT              NULL,
    [project_approval_status]            VARCHAR (50)     NULL,
    [project_execution_status]           VARCHAR (50)     NULL,
    [afe_date]                           DATETIME         NULL,
    [acct_yr]                            INT              NULL,
    [alloc_amt]                          NUMERIC (14, 2)  NULL,
    [tax_code]                           VARCHAR (10)     NULL,
    [capital_accrual_method_code]        VARCHAR (6)      NULL,
    [managing_org_id]                    VARCHAR (50)     NULL,
    [net_estimate_pct]                   NUMERIC (14, 10) NULL,
    [internal_approver]                  VARCHAR (40)     NULL,
    [manager_name]                       VARCHAR (20)     NULL,
    [success_effort_type_code]           VARCHAR (1)      NULL,
    [capital_accrual_cc_num]             VARCHAR (10)     NULL,
    [equip_component_amt]                NUMERIC (14, 2)  NULL,
    [wrhse_component_amt]                NUMERIC (14, 2)  NULL,
    [translation_rate]                   NUMERIC (14, 10) NULL,
    [original_alloc_amt]                 NUMERIC (14, 2)  NULL,
    [reporting_alloc_amt]                NUMERIC (14, 2)  NULL,
    [allow_other_orgs_code]              VARCHAR (1)      NULL,
    [province]                           VARCHAR (2)      NULL,
    [engineer_assigned]                  VARCHAR (50)     NULL,
    [geologist_assigned]                 VARCHAR (40)     NULL,
    [geophysicist_assigned]              VARCHAR (40)     NULL,
    [last_updt_status_user]              VARCHAR (32)     NULL,
    [last_updt_status_date]              DATETIME         NULL,
    [doi_type_code]                      VARCHAR (8)      NULL,
    [afe_class_code]                     VARCHAR (6)      NULL,
    [default_gl_sub_code]                VARCHAR (6)      NULL,
    [overhead_start_date]                DATETIME         NULL,
    [overhead_end_date]                  DATETIME         NULL,
    [capital_or_dry_hole_exp_code]       VARCHAR (1)      NULL,
    [last_accrued_date]                  DATETIME         NULL,
    [country_code]                       VARCHAR (2)      NULL,
    [survey_system_code]                 VARCHAR (6)      NULL,
    [primary_uwi]                        VARCHAR (56)     NULL,
    [uwi_alias]                          VARCHAR (8000)   NULL,
    [primary_location]                   VARCHAR (4000)   NULL,
    [sorted_uwi]                         VARCHAR (34)     NULL,
    [uwi_sort_element_1]                 VARCHAR (1)      NULL,
    [uwi_sort_element_2]                 VARCHAR (7)      NULL,
    [uwi_sort_element_3]                 VARCHAR (7)      NULL,
    [uwi_sort_element_4]                 VARCHAR (3)      NULL,
    [uwi_sort_element_5]                 VARCHAR (7)      NULL,
    [uwi_sort_element_6]                 VARCHAR (7)      NULL,
    [uwi_sort_element_7]                 VARCHAR (7)      NULL,
    [uwi_sort_element_8]                 VARCHAR (7)      NULL,
    [uwi_sort_element_9]                 VARCHAR (2)      NULL,
    [afe_udf_1_code]                     VARCHAR (50)     NULL,
    [afe_udf_5_code]                     VARCHAR (50)     NULL,
    [afe_udf_7_code]                     VARCHAR (50)     NULL,
    [afe_udf_20_code]                    VARCHAR (50)     NULL,
    [project_justification_comments]     VARCHAR (4000)   NULL,
    [budget_activity_year_desc]          VARCHAR (100)    NULL,
    [afe_type_group]                     VARCHAR (50)     NULL,
    [afe_type_group_desc]                VARCHAR (500)    NULL,
    [job_start_date]                     VARCHAR (20)     NULL,
    [rig_number]                         VARCHAR (50)     NULL,
    [rig_name]                           VARCHAR (100)    NULL,
    [zone_play]                          VARCHAR (100)    NULL,
    [wellview_spud_date]                 VARCHAR (20)     NULL,
    [wellview_rig_release_date]          VARCHAR (20)     NULL,
    [wellview_total_depth]               FLOAT (53)       NULL,
    [wellview_intermediate_casing_depth] FLOAT (53)       NULL,
    [wellview_horizontal_depth]          FLOAT (53)       NULL,
    [AFE_GCA_FCC]                        VARCHAR (50)     NULL,
    [cc_list]                            VARCHAR (500)    NULL,
    [Number_of_CCs]                      INT              NULL,
    [job_end_date]                       VARCHAR (20)     NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

