CREATE TABLE [data_mart].[t_fact_gl] (
    [li_id]                 INT            NULL,
    [voucher_id]            INT            NULL,
    [entity_key]            VARCHAR (500)  NULL,
    [afe_key]               VARCHAR (100)  NULL,
    [account_key]           VARCHAR (20)   NULL,
    [accounting_month_key]  INT            NULL,
    [activity_month_key]    INT            NULL,
    [organization_key]      INT            NULL,
    [gross_net_key]         INT            NULL,
    [vendor_key]            INT            NULL,
    [scenario_key]          VARCHAR (1000) NULL,
    [cad]                   FLOAT (53)     NULL,
    [qb_cad]                FLOAT (53)     NULL,
    [usd]                   FLOAT (53)     NULL,
    [metric_volume]         FLOAT (53)     NULL,
    [qb_metric_volume]      FLOAT (53)     NULL,
    [imperial_volume]       FLOAT (53)     NULL,
    [qb_imperial_volume]    FLOAT (53)     NULL,
    [boe_volume]            FLOAT (53)     NULL,
    [qb_boe_volume]         FLOAT (53)     NULL,
    [mcfe_volume]           FLOAT (53)     NULL,
    [qb_mcfe_volume]        FLOAT (53)     NULL,
    [cad_fixed]             FLOAT (53)     NULL,
    [cad_variable]          FLOAT (53)     NULL,
    [cad_econ_fixed]        FLOAT (53)     NULL,
    [cad_econ_variable_gas] FLOAT (53)     NULL,
    [cad_econ_variable_oil] FLOAT (53)     NULL,
    [is_leaseops]           INT            NULL,
    [is_capital]            INT            NULL,
    [is_volumes]            INT            NULL,
    [is_valnav]             INT            NULL,
    [is_finance]            INT            NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

