CREATE EXTERNAL FILE FORMAT [ADFCopyGeneratedFileFormat_3bc100bd-554b-40d9-9a55-0c8a570a5c6a]
    WITH (
    FORMAT_TYPE = DELIMITEDTEXT,
    FORMAT_OPTIONS (FIELD_TERMINATOR = N'⯑', FIRST_ROW = 2, ENCODING = N'UTF8')
    );

