CREATE VIEW [dbo].[v_fact_ap_ar_open]
AS select distinct invc_type_code,
       ba_id,
	   invc_id,
	   invc_num,
	   invoice_date,
	   org_id,
	   accounting_month,
	   due_date,
	   voucher_id,
	   voucher_type_code,
	   voucher_num,
	   cad_open,
	   max(invoice_amount) over (partition by invc_type_code,
       ba_id,
	   invc_id,
	   invc_num,
	   invoice_date,
	   org_id,
	   accounting_month,
	   due_date,
	   voucher_id,
	   voucher_type_code,
	   voucher_num) invoice_amount
from [data_mart].t_fact_ap_ar_open;