CREATE TABLE [data_mart_metrix].[t_dim_well] (
    [Well_Tract_Sys_ID]           NUMERIC (16)    NULL,
    [Well_Tract_ID]               VARCHAR (50)    NULL,
    [Well_Tract_Type_Code]        VARCHAR (50)    NOT NULL,
    [Well_Tract_Type]             VARCHAR (50)    NOT NULL,
    [Well_Tract_Province]         VARCHAR (50)    NULL,
    [Well_Tract_Name]             VARCHAR (100)   NULL,
    [Cost_Centre_Code]            VARCHAR (50)    NULL,
    [Unique_Identifier]           VARCHAR (50)    NULL,
    [UWI]                         VARCHAR (100)   NULL,
    [Formatted_UWI]               VARCHAR (100)   NULL,
    [Production_Status]           VARCHAR (50)    NULL,
    [Primary_Product]             VARCHAR (20)    NULL,
    [Well_Facility_id]            VARCHAR (50)    NULL,
    [Well_PA_Responsible_User_ID] VARCHAR (50)    NULL,
    [Well_PA_Responsible_User]    VARCHAR (500)   NULL,
    [cost_centre_name]            VARCHAR (1000)  NULL,
    [corp]                        VARCHAR (50)    NULL,
    [corp_name]                   VARCHAR (1000)  NULL,
    [region]                      VARCHAR (50)    NULL,
    [region_name]                 VARCHAR (1000)  NULL,
    [region_code]                 VARCHAR (100)   NULL,
    [district]                    VARCHAR (50)    NULL,
    [district_name]               VARCHAR (1000)  NULL,
    [district_code]               VARCHAR (100)   NULL,
    [area]                        VARCHAR (50)    NULL,
    [area_name]                   VARCHAR (1000)  NULL,
    [area_code]                   VARCHAR (100)   NULL,
    [facility]                    VARCHAR (50)    NULL,
    [facility_name]               VARCHAR (1000)  NULL,
    [facility_code]               VARCHAR (100)   NULL,
    [cc_type]                     VARCHAR (50)    NULL,
    [cc_type_code]                VARCHAR (50)    NULL,
    [Report_Liquid_as_Condensate] VARCHAR (1)     NULL,
    [Unit_ID]                     VARCHAR (50)    NULL,
    [Unit_Name]                   VARCHAR (50)    NULL,
    [Unit_Province]               VARCHAR (50)    NULL,
    [Unit_Govt_Code]              VARCHAR (50)    NULL,
    [Unit_Cost_Centre_Code]       VARCHAR (50)    NULL,
    [spud_date]                   VARCHAR (50)    NULL,
    [rig_release_date]            VARCHAR (50)    NULL,
    [on_production_date]          VARCHAR (50)    NULL,
    [create_date]                 VARCHAR (50)    NULL,
    [cc_term_date]                VARCHAR (50)    NULL,
    [cgu]                         VARCHAR (100)   NULL,
    [current_reserves_property]   VARCHAR (200)   NULL,
    [year_end_reserves_property]  VARCHAR (200)   NULL,
    [disposition_package]         VARCHAR (200)   NULL,
    [Royalty_Entity_ID]           VARCHAR (30)    NULL,
    [Oil_Royalty_Entity_ID]       VARCHAR (30)    NULL,
    [Reserve_Code]                VARCHAR (100)   NULL,
    [crown_royalty_percent]       NUMERIC (11, 8) NULL,
    [freehold_royalty_percent]    NUMERIC (11, 8) NULL,
    [federal_percent]             NUMERIC (11, 8) NULL,
    [acquired_from]               VARCHAR (100)   NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

